// Copyright (c) Ryan Bliss and contributors. All rights reserved.
// Licensed under the MIT License.

#nullable enable

using System;
using System.Collections.Generic;
using NeoCompose.Runtime.Json;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace NeoCompose.Runtime
{
    /// <summary>
    /// Unity asset database generated by the Neo Compose editor sync.
    /// Maps Neo Compose file ids to imported Unity asset paths so runtime
    /// code can resolve file-backed attributes after a scene reload.
    /// </summary>
    public sealed class NeoAssetDatabase : ScriptableObject
    {
        [SerializeField]
        private List<NeoAssetDatabaseEntry> files = new();
        [SerializeField]
        private List<NeoAssetDatabaseTileEntry> tileAssets = new();

        /// <summary>
        /// Loads the default synchronized asset database from Resources.
        /// Generated project loaders use this when the caller does not pass
        /// an explicit database.
        /// </summary>
        public static NeoAssetDatabase? LoadDefault()
        {
            return Resources.Load<NeoAssetDatabase>(NeoComposeDefaults.AssetDatabaseResourcePath);
        }

        /// <summary>
        /// Read-only entries keyed by Neo Compose file id.
        /// </summary>
        public IReadOnlyList<NeoAssetDatabaseEntry> Files => files;

        /// <summary>
        /// Read-only generated Tile/RuleTile assets keyed by Neo tile value id.
        /// </summary>
        public IReadOnlyList<NeoAssetDatabaseTileEntry> TileAssets => tileAssets;

        /// <summary>
        /// Returns the imported asset path for <paramref name="fileId"/>,
        /// or <c>null</c> when the file has not been synchronized yet.
        /// </summary>
        public string? TryGetAssetPath(string fileId)
        {
            var entry = TryGetEntry(fileId);
            return entry?.AssetPath;
        }

        /// <summary>
        /// Resolves a synchronized sprite by file id and canonical slice index.
        /// Falls back to Resources path loading when the serialized reference
        /// has not been populated yet.
        /// </summary>
        public Sprite? TryGetSprite(string fileId, int sliceIndex)
        {
            var entry = TryGetEntry(fileId);
            if (entry == null || sliceIndex < 0) return null;
            if (entry.Sprites.Length > sliceIndex && entry.Sprites[sliceIndex] != null)
            {
                return entry.Sprites[sliceIndex];
            }

            return null;
        }

        /// <summary>
        /// Resolves a synchronized audio clip by file id.
        /// </summary>
        public AudioClip? TryGetAudioClip(string fileId)
        {
            return TryGetEntry(fileId)?.AudioClip;
        }

        /// <summary>
        /// Resolves an editor-generated Tile or RuleTile asset by Neo tile value id.
        /// Runtime renderers use this before falling back to transient tile creation.
        /// </summary>
        public TileBase? TryGetTileBase(string tileValueId)
        {
            return TryGetTileEntry(tileValueId)?.TileBase;
        }

        /// <summary>
        /// Reverse-resolves a Unity Sprite into the persisted file reference
        /// expected by Sprite attributes.
        /// </summary>
        public SpriteValue? TryGetValueForSprite(Sprite sprite)
        {
            var entry = TryGetEntryForSprite(sprite, out var sliceIndex);
            return entry == null
                ? null
                : new SpriteValue { fileId = entry.FileId, sliceIndex = sliceIndex };
        }

        /// <summary>
        /// Reverse-resolves a Unity AudioClip into the persisted file reference
        /// expected by Audio attributes.
        /// </summary>
        public FileValue? TryGetValueForAudioClip(AudioClip audioClip)
        {
            var entry = TryGetEntryForAudioClip(audioClip);
            return entry == null ? null : new FileValue { fileId = entry.FileId };
        }

        /// <summary>
        /// Reverse-resolves a Unity Sprite to its synchronized file metadata.
        /// </summary>
        public NeoAssetDatabaseEntry? TryGetEntryForSprite(Sprite sprite, out int sliceIndex)
        {
            sliceIndex = -1;
            if (sprite == null) return null;
            foreach (var entry in files)
            {
                for (var index = 0; index < entry.Sprites.Length; index++)
                {
                    if (entry.Sprites[index] == sprite)
                    {
                        sliceIndex = index;
                        return entry;
                    }
                }
            }

            return null;
        }

        /// <summary>
        /// Reverse-resolves a Unity AudioClip to its synchronized file metadata.
        /// </summary>
        public NeoAssetDatabaseEntry? TryGetEntryForAudioClip(AudioClip audioClip)
        {
            if (audioClip == null) return null;
            foreach (var entry in files)
            {
                if (entry.AudioClip == audioClip) return entry;
            }

            return null;
        }

        /// <summary>
        /// Returns the synchronized entry for <paramref name="fileId"/>,
        /// or <c>null</c> when the file has not been synchronized yet.
        /// </summary>
        public NeoAssetDatabaseEntry? TryGetEntry(string fileId)
        {
            if (string.IsNullOrWhiteSpace(fileId)) return null;
            foreach (var entry in files)
            {
                if (entry.FileId == fileId) return entry;
            }

            return null;
        }

        /// <summary>
        /// Returns the generated Tile/RuleTile entry for <paramref name="tileValueId"/>,
        /// or <c>null</c> when editor sync has not produced one yet.
        /// </summary>
        public NeoAssetDatabaseTileEntry? TryGetTileEntry(string tileValueId)
        {
            if (string.IsNullOrWhiteSpace(tileValueId)) return null;
            foreach (var entry in tileAssets)
            {
                if (entry.TileValueId == tileValueId) return entry;
            }

            return null;
        }

        /// <summary>
        /// Upserts a file mapping after the editor has downloaded and
        /// imported the matching Unity asset.
        /// </summary>
        public void SetFile(
            string fileId,
            string fileName,
            string assetPath,
            string updatedAt,
            string lastDownloadedAt,
            string fileRecordHash,
            string? templateId,
            string templateRecordHash,
            string importSettingsVersion,
            Sprite[]? sprites = null,
            AudioClip? audioClip = null)
        {
            if (string.IsNullOrWhiteSpace(fileId))
            {
                throw new ArgumentException("File id cannot be empty.", nameof(fileId));
            }

            if (string.IsNullOrWhiteSpace(assetPath))
            {
                throw new ArgumentException("Asset path cannot be empty.", nameof(assetPath));
            }

            var entry = TryGetEntry(fileId);
            if (entry == null)
            {
                entry = new NeoAssetDatabaseEntry();
                files.Add(entry);
            }

            entry.FileId = fileId;
            entry.FileName = fileName;
            entry.AssetPath = assetPath;
            entry.FileUpdatedAt = updatedAt;
            entry.LastDownloadedAt = lastDownloadedAt;
            entry.FileRecordHash = fileRecordHash;
            entry.TemplateId = templateId;
            entry.TemplateRecordHash = templateRecordHash;
            entry.ImportSettingsVersion = importSettingsVersion;
            entry.Sprites = sprites ?? Array.Empty<Sprite>();
            entry.AudioClip = audioClip;
        }

        /// <summary>
        /// Upserts a generated Tile/RuleTile asset mapping after editor sync has
        /// created or refreshed the deterministic Unity asset.
        /// </summary>
        public void SetTileAsset(
            string tileValueId,
            string? tileTypeId,
            string assetPath,
            string contentHash,
            TileBase tileBase)
        {
            if (string.IsNullOrWhiteSpace(tileValueId))
            {
                throw new ArgumentException("Tile value id cannot be empty.", nameof(tileValueId));
            }

            if (string.IsNullOrWhiteSpace(assetPath))
            {
                throw new ArgumentException("Asset path cannot be empty.", nameof(assetPath));
            }

            if (tileBase == null)
            {
                throw new ArgumentNullException(nameof(tileBase));
            }

            var entry = TryGetTileEntry(tileValueId);
            if (entry == null)
            {
                entry = new NeoAssetDatabaseTileEntry();
                tileAssets.Add(entry);
            }

            entry.TileValueId = tileValueId;
            entry.TileTypeId = tileTypeId ?? "";
            entry.AssetPath = assetPath;
            entry.ContentHash = contentHash;
            entry.TileBase = tileBase;
        }

        /// <summary>
        /// Returns stale file mappings whose ids are no longer present in the
        /// latest Neo Compose export.
        /// </summary>
        public NeoAssetDatabaseEntry[] FindMissingFiles(ISet<string> fileIds)
        {
            var missing = new List<NeoAssetDatabaseEntry>();
            foreach (var entry in files)
            {
                if (!fileIds.Contains(entry.FileId)) missing.Add(entry);
            }

            return missing.ToArray();
        }

        /// <summary>
        /// Returns generated tile asset mappings whose tile value ids are no
        /// longer referenced by the latest Neo Compose export.
        /// </summary>
        public NeoAssetDatabaseTileEntry[] FindMissingTileAssets(ISet<string> tileValueIds)
        {
            var missing = new List<NeoAssetDatabaseTileEntry>();
            foreach (var entry in tileAssets)
            {
                if (!tileValueIds.Contains(entry.TileValueId)) missing.Add(entry);
            }

            return missing.ToArray();
        }

        /// <summary>
        /// Removes a synchronized file mapping.
        /// </summary>
        public void RemoveFile(string fileId)
        {
            files.RemoveAll(entry => entry.FileId == fileId);
        }

        /// <summary>
        /// Removes a generated Tile/RuleTile asset mapping.
        /// </summary>
        public void RemoveTileAsset(string tileValueId)
        {
            tileAssets.RemoveAll(entry => entry.TileValueId == tileValueId);
        }
    }

    /// <summary>
    /// Serialized mapping for a single synchronized file-backed Unity asset.
    /// </summary>
    [Serializable]
    public sealed class NeoAssetDatabaseEntry
    {
        [SerializeField]
        private string fileId = "";
        [SerializeField]
        private string fileName = "";
        [SerializeField]
        private string assetPath = "";
        [SerializeField]
        private string fileUpdatedAt = "";
        [SerializeField]
        private string lastDownloadedAt = "";
        [SerializeField]
        private string fileRecordHash = "";
        [SerializeField]
        private string? templateId;
        [SerializeField]
        private string templateRecordHash = "";
        [SerializeField]
        private string importSettingsVersion = "";
        [SerializeField]
        private Sprite[] sprites = Array.Empty<Sprite>();
        [SerializeField]
        private AudioClip? audioClip;

        /// <summary>Neo Compose file id.</summary>
        public string FileId
        {
            get => fileId;
            set => fileId = value;
        }

        /// <summary>Original Neo Compose file name.</summary>
        public string FileName
        {
            get => fileName;
            set => fileName = value;
        }

        /// <summary>Project-relative Unity asset path.</summary>
        public string AssetPath
        {
            get => assetPath;
            set => assetPath = value;
        }

        /// <summary>File metadata timestamp from project.json.</summary>
        public string FileUpdatedAt
        {
            get => fileUpdatedAt;
            set => fileUpdatedAt = value;
        }

        /// <summary>Timestamp when the file bytes were last downloaded.</summary>
        public string LastDownloadedAt
        {
            get => lastDownloadedAt;
            set => lastDownloadedAt = value;
        }

        /// <summary>
        /// Content hash of the exported file record captured when the file was
        /// last downloaded. Editor sync skips the download while the incoming
        /// record hashes to the same value.
        /// </summary>
        public string FileRecordHash
        {
            get => fileRecordHash;
            set => fileRecordHash = value;
        }

        /// <summary>Template id used for the last applied import settings.</summary>
        public string? TemplateId
        {
            get => templateId;
            set => templateId = value;
        }

        /// <summary>
        /// Content hash of the resolved import-settings template record captured
        /// when the file was last downloaded (empty when the file uses no
        /// template). Editor sync re-imports when the template's hash changes.
        /// </summary>
        public string TemplateRecordHash
        {
            get => templateRecordHash;
            set => templateRecordHash = value;
        }

        /// <summary>Neo Compose importer implementation version used for the last import.</summary>
        public string ImportSettingsVersion
        {
            get => importSettingsVersion;
            set => importSettingsVersion = value;
        }

        /// <summary>Imported sprites in canonical slice order.</summary>
        public Sprite[] Sprites
        {
            get => sprites ?? Array.Empty<Sprite>();
            set => sprites = value ?? Array.Empty<Sprite>();
        }

        /// <summary>Imported audio clip reference.</summary>
        public AudioClip? AudioClip
        {
            get => audioClip;
            set => audioClip = value;
        }
    }

    /// <summary>
    /// Serialized mapping for an editor-generated Tile/RuleTile asset.
    /// </summary>
    [Serializable]
    public sealed class NeoAssetDatabaseTileEntry
    {
        [SerializeField]
        private string tileValueId = "";
        [SerializeField]
        private string tileTypeId = "";
        [SerializeField]
        private string assetPath = "";
        [SerializeField]
        private string contentHash = "";
        [SerializeField]
        private TileBase? tileBase;

        /// <summary>Neo Compose tile value id.</summary>
        public string TileValueId
        {
            get => tileValueId;
            set => tileValueId = value;
        }

        /// <summary>Neo Compose tile custom type id.</summary>
        public string TileTypeId
        {
            get => tileTypeId;
            set => tileTypeId = value;
        }

        /// <summary>Project-relative generated Unity asset path.</summary>
        public string AssetPath
        {
            get => assetPath;
            set => assetPath = value;
        }

        /// <summary>Stable sync hash used to detect stale generated tile assets.</summary>
        public string ContentHash
        {
            get => contentHash;
            set => contentHash = value;
        }

        /// <summary>Generated Unity Tile or RuleTile asset.</summary>
        public TileBase? TileBase
        {
            get => tileBase;
            set => tileBase = value;
        }
    }
}
