// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using NeoCompose.Runtime;
using NeoCompose.Runtime.Json;
using NeoCompose.Runtime.NeoScript;

namespace HelloWorld.Assets.Scripts.Neo
{
    public sealed class HelloWorldNeo
    {
        public NeoClient Runtime { get; }
        public Assets Assets { get; }
        public SaveSaved Save { get; }

        public HelloWorldNeo(NeoClient runtime)
        {
            Runtime = runtime;
            Assets = new Assets(runtime, runtime.assets);
            Save = new SaveSaved(runtime, runtime.save);
        }

        public static HelloWorldNeo Load(string projectJson, NeoClient.LoadSave loadSave, NeoClient.HandleSave handleSave)
        {
            var runtime = new NeoLoader().Load(projectJson, loadSave, handleSave);
            return new HelloWorldNeo(runtime);
        }
    }

    public sealed class Planet : IEquatable<Planet>
    {
        private static readonly Dictionary<string, Planet> values = new Dictionary<string, Planet>();
        public string optionId { get; }

        private Planet(string optionId)
        {
            this.optionId = optionId;
        }

        public const string mercury = "mercury";
        public const string venus = "venus";
        public const string earth = "earth";
        public const string mars = "mars";
        public const string jupiter = "jupiter";

        public static Planet FromOptionId(string optionId)
        {
            if (values.TryGetValue(optionId, out var known)) return known;
            var created = new Planet(optionId);
            values[optionId] = created;
            return created;
        }

        public static string[] ToOptionIds(IEnumerable<Planet>? options)
        {
            if (options is null) return Array.Empty<string>();
            var ids = new List<string>();
            foreach (var option in options) ids.Add(option.optionId);
            return ids.ToArray();
        }

        public static bool IsKnown(string id)
        {
            return id switch
            {
                mercury => true,
                venus => true,
                earth => true,
                mars => true,
                jupiter => true,
                _ => false,
            };
        }

        public static implicit operator string(Planet value) => value.optionId;
        public static implicit operator Planet(string optionId) => FromOptionId(optionId);
        public override string ToString() => optionId;
        public bool Equals(Planet? other) => other is not null && optionId == other.optionId;
        public override bool Equals(object? obj) => Equals(obj as Planet);
        public override int GetHashCode() => optionId.GetHashCode();
    }

    public partial class Assets : NeoNode, IDisposable
    {
        protected readonly NeoAttributeCustom node;
        private bool isDisposed;
        public event Action? OnChanged;
        public string? valueId => node.overrideValueId ?? node.value?.id;

        public Assets(NeoClient client, NeoAttributeCustom node)
            : base(client)
        {
            this.node = node;
            this.node.OnChanged += HandleNodeChanged;
            this.node.OnDisposed += HandleNodeDisposed;
        }

        public NeoLookupSelection ToLookupSelection()
        {
            if (valueId is null) throw new InvalidOperationException("This generated value is not bound to a lookup-selectable value id.");
            return new NeoLookupSelection(valueId);
        }

        public NeoValuePayload ToNeoValuePayload()
        {
            return new NeoValuePayload(node.value?.value, node.value?.typeId ?? "dd0bbe5a-47ef-4164-9421-caea07f6f56f");
        }

        public virtual void Dispose()
        {
            if (isDisposed) return;
            isDisposed = true;
            node.OnChanged -= HandleNodeChanged;
            node.OnDisposed -= HandleNodeDisposed;
        }

        private void HandleNodeChanged(NeoAttribute changed)
        {
            OnChanged?.Invoke();
        }

        private void HandleNodeDisposed(NeoAttribute disposed)
        {
            Dispose();
        }

        public static NeoValuePayload factory(NeoClient client, NeoValuePayload? computed = null)
        {
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (computed is not null)
            {
                var computedValueId = Guid.NewGuid().ToString();
                value["computed"] = computedValueId;
                foreach (var row in computed.valueRows) valueRows.Add(row);
                valueRows.Add(new ObjectAttributeValue
                {
                    id = computedValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = computed.value as Dictionary<string, string>,
                    typeId = computed.typeId,
                });
            }
            return new NeoValuePayload(value, "dd0bbe5a-47ef-4164-9421-caea07f6f56f", valueRows);
        }

        internal static Assets Create(NeoClient client, NeoAttributeCustom node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new Assets(client, node),
            };
        }

        public ComputedText computed
        {
            get
            {
                return ComputedText.Create(client, node.Get<NeoAttributeCustom>("computed"));
            }
        }
    }

    public partial class AssetsSaved : Assets
    {
        public AssetsSaved(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        internal static AssetsSaved CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new AssetsSaved(client, node),
            };
        }

        public new ComputedTextSaved computed
        {
            get
            {
                return ComputedTextSaved.CreateSaved(client, node.Get<NeoAttributeCustomSaved>("computed"));
            }
            set
            {
                savedNode.SetValue("computed", value?.ToNeoValuePayload());
            }
        }

        public void Setcomputed(NeoValuePayload? value)
        {
            savedNode.SetValue("computed", value);
        }
    }
    public partial class Save : NeoNode, IDisposable
    {
        protected readonly NeoAttributeCustom node;
        private bool isDisposed;
        public event Action? OnChanged;
        public string? valueId => node.overrideValueId ?? node.value?.id;

        public Save(NeoClient client, NeoAttributeCustom node)
            : base(client)
        {
            this.node = node;
            this.node.OnChanged += HandleNodeChanged;
            this.node.OnDisposed += HandleNodeDisposed;
        }

        public NeoLookupSelection ToLookupSelection()
        {
            if (valueId is null) throw new InvalidOperationException("This generated value is not bound to a lookup-selectable value id.");
            return new NeoLookupSelection(valueId);
        }

        public NeoValuePayload ToNeoValuePayload()
        {
            return new NeoValuePayload(node.value?.value, node.value?.typeId ?? "96e8284d-ae43-4e91-919d-86c25ce098e0");
        }

        public virtual void Dispose()
        {
            if (isDisposed) return;
            isDisposed = true;
            node.OnChanged -= HandleNodeChanged;
            node.OnDisposed -= HandleNodeDisposed;
        }

        private void HandleNodeChanged(NeoAttribute changed)
        {
            OnChanged?.Invoke();
        }

        private void HandleNodeDisposed(NeoAttribute disposed)
        {
            Dispose();
        }

        public static NeoValuePayload factory(NeoClient client, Planet? world = null, IEnumerable<NeoValuePayload>? visited = null)
        {
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (world is not null)
            {
                var worldValueId = Guid.NewGuid().ToString();
                value["world"] = worldValueId;
                valueRows.Add(new ArrayAttributeValue
                {
                    id = worldValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = world is null ? null : new[] { world.optionId },
                });
            }
            if (visited is not null)
            {
                var visitedValueId = Guid.NewGuid().ToString();
                value["visited"] = visitedValueId;
                var visitedIds = new List<string>();
                foreach (var entry in visited)
                {
                    var entryValueId = Guid.NewGuid().ToString();
                    visitedIds.Add(entryValueId);
                    foreach (var row in entry.valueRows) valueRows.Add(row);
                    valueRows.Add(new ObjectAttributeValue
                    {
                        id = entryValueId,
                        createdAt = nowIso,
                        updatedAt = nowIso,
                        value = entry.value as Dictionary<string, string>,
                        typeId = entry.typeId,
                    });
                }
                valueRows.Add(new ArrayAttributeValue
                {
                    id = visitedValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = visitedIds.ToArray(),
                });
            }
            return new NeoValuePayload(value, "96e8284d-ae43-4e91-919d-86c25ce098e0", valueRows);
        }

        internal static Save Create(NeoClient client, NeoAttributeCustom node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new Save(client, node),
            };
        }

        public Planet world
        {
            get
            {
                var selected = NeoGeneratedTypesSupport.ReadSingleSelected(node.Get<NeoAttributeEnum>("world"));
                return selected is null ? throw new InvalidOperationException("Required enum 'world' has no selected option.") : Planet.FromOptionId(selected);
            }
        }

        public NeoReadOnlyList<PlanetVisit> visited
        {
            get
            {
                return new NeoReadOnlyList<PlanetVisit>(client, node.Get<NeoAttributeList>("visited"), (client, child) => PlanetVisit.Create(client, (NeoAttributeCustom)child));
            }
        }
    }

    public partial class SaveSaved : Save
    {
        public SaveSaved(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        internal static SaveSaved CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new SaveSaved(client, node),
            };
        }

        public new Planet world
        {
            get
            {
                var selected = NeoGeneratedTypesSupport.ReadSingleSelected(node.Get<NeoAttributeEnum>("world"));
                return selected is null ? throw new InvalidOperationException("Required enum 'world' has no selected option.") : Planet.FromOptionId(selected);
            }
            set
            {
                savedNode.SetValue("world", new[] { value.optionId });
            }
        }

        public new NeoList<PlanetVisitSaved> visited
        {
            get
            {
                return new NeoList<PlanetVisitSaved>(client, node.Get<NeoAttributeListSaved>("visited"), (client, child) => PlanetVisitSaved.CreateSaved(client, (NeoAttributeCustomSaved)child), item => item.ToNeoValuePayload());
            }
        }

        public void SetvisitedValue(object? value)
        {
            savedNode.SetValue("visited", value);
        }
    }
    public partial class ComputedText : NeoNode, IDisposable
    {
        protected readonly NeoAttributeCustom node;
        private bool isDisposed;
        public event Action? OnChanged;
        public string? valueId => node.overrideValueId ?? node.value?.id;

        public ComputedText(NeoClient client, NeoAttributeCustom node)
            : base(client)
        {
            this.node = node;
            this.node.OnChanged += HandleNodeChanged;
            this.node.OnDisposed += HandleNodeDisposed;
        }

        public NeoLookupSelection ToLookupSelection()
        {
            if (valueId is null) throw new InvalidOperationException("This generated value is not bound to a lookup-selectable value id.");
            return new NeoLookupSelection(valueId);
        }

        public NeoValuePayload ToNeoValuePayload()
        {
            return new NeoValuePayload(node.value?.value, node.value?.typeId ?? "2ab1bc07-da0b-47fc-b77b-54cc511575bb");
        }

        public virtual void Dispose()
        {
            if (isDisposed) return;
            isDisposed = true;
            node.OnChanged -= HandleNodeChanged;
            node.OnDisposed -= HandleNodeDisposed;
        }

        private void HandleNodeChanged(NeoAttribute changed)
        {
            OnChanged?.Invoke();
        }

        private void HandleNodeDisposed(NeoAttribute disposed)
        {
            Dispose();
        }

        public static NeoValuePayload factory(NeoClient client, string? baseText = null, string? optionalSuffix = null)
        {
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (baseText is not null)
            {
                var baseTextValueId = Guid.NewGuid().ToString();
                value["baseText"] = baseTextValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = baseTextValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = baseText,
                });
            }
            if (optionalSuffix is not null)
            {
                var optionalSuffixValueId = Guid.NewGuid().ToString();
                value["optionalSuffix"] = optionalSuffixValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = optionalSuffixValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = optionalSuffix,
                });
            }
            return new NeoValuePayload(value, "2ab1bc07-da0b-47fc-b77b-54cc511575bb", valueRows);
        }

        internal static ComputedText Create(NeoClient client, NeoAttributeCustom node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new ComputedText(client, node),
            };
        }

        public string baseText
        {
            get
            {
                return node.Get<NeoAttributeString>("baseText").value?.value ?? throw new InvalidOperationException("Required string 'baseText' has no value.");
            }
        }

        public string? optionalSuffix
        {
            get
            {
                return node.Get<NeoAttributeString>("optionalSuffix").value?.value;
            }
        }

        public string fullText
        {
            get
            {
                var result = node.Get<NeoAttributeNSGetter>("fullText").Compute();
                if (!result.ok) throw new InvalidOperationException(result.error ?? "NSGetter evaluation failed.");
                return (string)result.value!;
            }
        }
    }

    public partial class ComputedTextSaved : ComputedText
    {
        public ComputedTextSaved(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        internal static ComputedTextSaved CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new ComputedTextSaved(client, node),
            };
        }

        public new string baseText
        {
            get
            {
                return node.Get<NeoAttributeString>("baseText").value?.value ?? throw new InvalidOperationException("Required string 'baseText' has no value.");
            }
            set
            {
                savedNode.SetValue("baseText", value);
            }
        }

        public new string? optionalSuffix
        {
            get
            {
                return node.Get<NeoAttributeString>("optionalSuffix").value?.value;
            }
            set
            {
                savedNode.SetValue("optionalSuffix", value);
            }
        }

        public new string fullText
        {
            get
            {
                var result = node.Get<NeoAttributeNSGetter>("fullText").Compute();
                if (!result.ok) throw new InvalidOperationException(result.error ?? "NSGetter evaluation failed.");
                return (string)result.value!;
            }
        }
    }
    public partial class PlanetVisit : NeoNode, IDisposable
    {
        protected readonly NeoAttributeCustom node;
        private bool isDisposed;
        public event Action? OnChanged;
        public string? valueId => node.overrideValueId ?? node.value?.id;

        public PlanetVisit(NeoClient client, NeoAttributeCustom node)
            : base(client)
        {
            this.node = node;
            this.node.OnChanged += HandleNodeChanged;
            this.node.OnDisposed += HandleNodeDisposed;
        }

        public NeoLookupSelection ToLookupSelection()
        {
            if (valueId is null) throw new InvalidOperationException("This generated value is not bound to a lookup-selectable value id.");
            return new NeoLookupSelection(valueId);
        }

        public NeoValuePayload ToNeoValuePayload()
        {
            return new NeoValuePayload(node.value?.value, node.value?.typeId ?? "7755a905-f2a1-4e5d-8b60-78cbdd2b2042");
        }

        public virtual void Dispose()
        {
            if (isDisposed) return;
            isDisposed = true;
            node.OnChanged -= HandleNodeChanged;
            node.OnDisposed -= HandleNodeDisposed;
        }

        private void HandleNodeChanged(NeoAttribute changed)
        {
            OnChanged?.Invoke();
        }

        private void HandleNodeDisposed(NeoAttribute disposed)
        {
            Dispose();
        }

        public static NeoValuePayload factory(NeoClient client, Planet? world = null, int? dateUnix = null)
        {
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (world is not null)
            {
                var worldValueId = Guid.NewGuid().ToString();
                value["world"] = worldValueId;
                valueRows.Add(new ArrayAttributeValue
                {
                    id = worldValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = world is null ? null : new[] { world.optionId },
                });
            }
            if (dateUnix is not null)
            {
                var dateUnixValueId = Guid.NewGuid().ToString();
                value["dateUnix"] = dateUnixValueId;
                valueRows.Add(new NumberAttributeValue
                {
                    id = dateUnixValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = dateUnix.HasValue ? dateUnix.Value : (double?)null,
                });
            }
            return new NeoValuePayload(value, "7755a905-f2a1-4e5d-8b60-78cbdd2b2042", valueRows);
        }

        internal static PlanetVisit Create(NeoClient client, NeoAttributeCustom node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new PlanetVisit(client, node),
            };
        }

        public Planet world
        {
            get
            {
                var selected = NeoGeneratedTypesSupport.ReadSingleSelected(node.Get<NeoAttributeEnum>("world"));
                return selected is null ? throw new InvalidOperationException("Required enum 'world' has no selected option.") : Planet.FromOptionId(selected);
            }
        }

        public int dateUnix
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("dateUnix")) ?? throw new InvalidOperationException("Required int 'dateUnix' has no value.");
            }
        }
    }

    public partial class PlanetVisitSaved : PlanetVisit
    {
        public PlanetVisitSaved(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        internal static PlanetVisitSaved CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var runtimeTypeId = node.value?.typeId;
            return runtimeTypeId switch
            {
                _ => new PlanetVisitSaved(client, node),
            };
        }

        public new Planet world
        {
            get
            {
                var selected = NeoGeneratedTypesSupport.ReadSingleSelected(node.Get<NeoAttributeEnum>("world"));
                return selected is null ? throw new InvalidOperationException("Required enum 'world' has no selected option.") : Planet.FromOptionId(selected);
            }
            set
            {
                savedNode.SetValue("world", new[] { value.optionId });
            }
        }

        public new int dateUnix
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("dateUnix")) ?? throw new InvalidOperationException("Required int 'dateUnix' has no value.");
            }
            set
            {
                savedNode.SetValue("dateUnix", value);
            }
        }
    }
}
