// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using NeoCompose.Runtime;
using NeoCompose.Runtime.Json;
using NeoCompose.Runtime.NeoScript;

namespace Assets.Scripts.Neo
{
    public sealed class TestProjectNeo : INeoClient
    {
        public static TestProjectNeo Instance { get; private set; } = null!;

        internal static TestProjectNeo RequireInstance() => Instance ?? throw new InvalidOperationException("TestProjectNeo.Instance has not been initialized.");

        public NeoClient Client { get; }
        public ReadOnlyRoot Assets { get; }
        public Root Save { get; }
        public NeoDialogues Dialogues { get; }

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.ReadOnlyCustomFactory> DialogueReadOnlyValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.ReadOnlyCustomFactory>
            {
                ["type-base"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyBase.Create(client, node),
                ["type-choice-log"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyNeoChoiceLog.Create(client, node),
                ["type-derived"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyDerived.Create(client, node),
                ["type-dialogue-memory"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyNeoDialogueMemory.Create(client, node),
                ["type-hero"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyHero.Create(client, node),
                ["type-neo-memory"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyNeoMemory.Create(client, node),
                ["type-override"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyOverride.Create(client, node),
                ["type-root"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyRoot.Create(client, node),
                ["type-text-node-memory"] = (client, node) => global::Assets.Scripts.Neo.ReadOnlyNeoTextNodeMemory.Create(client, node),
            };

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.SavedCustomFactory> DialogueSavedValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.SavedCustomFactory>
            {
                ["type-base"] = (client, node) => global::Assets.Scripts.Neo.Base.CreateSaved(client, node),
                ["type-choice-log"] = (client, node) => global::Assets.Scripts.Neo.NeoChoiceLog.CreateSaved(client, node),
                ["type-derived"] = (client, node) => global::Assets.Scripts.Neo.Derived.CreateSaved(client, node),
                ["type-dialogue-memory"] = (client, node) => global::Assets.Scripts.Neo.NeoDialogueMemory.CreateSaved(client, node),
                ["type-hero"] = (client, node) => global::Assets.Scripts.Neo.Hero.CreateSaved(client, node),
                ["type-neo-memory"] = (client, node) => global::Assets.Scripts.Neo.NeoMemory.CreateSaved(client, node),
                ["type-override"] = (client, node) => global::Assets.Scripts.Neo.Override.CreateSaved(client, node),
                ["type-root"] = (client, node) => global::Assets.Scripts.Neo.Root.CreateSaved(client, node),
                ["type-text-node-memory"] = (client, node) => global::Assets.Scripts.Neo.NeoTextNodeMemory.CreateSaved(client, node),
            };

        internal object? ResolveDialogueValue(string valueId) =>
            NeoGeneratedTypesSupport.ResolveCustomValue(
                Client,
                valueId,
                DialogueReadOnlyValueFactories,
                DialogueSavedValueFactories);

        public TestProjectNeo(NeoClient client, NeoDialogueRuntimeOptions? dialogueOptions = null)
        {
            Client = client;
            Instance = this;
            Assets = new ReadOnlyRoot(client, client.assets);
            Save = new Root(client, client.save);
            Dialogues = new NeoDialogues(this, dialogueOptions);
        }

        public static TestProjectNeo Load(string projectJson, NeoClient.LoadSave loadSave, NeoClient.HandleSave handleSave, NeoDialogueRuntimeOptions? dialogueOptions = null)
        {
            var client = new NeoLoader().Load(projectJson, loadSave, handleSave);
            return new TestProjectNeo(client, dialogueOptions);
        }

        public string SerializeSaveData() => Client.SerializeSaveData();

        public void Commit() => Client.Commit();

        public int RunGarbageCollector() => Client.RunGarbageCollector();

        public IReadOnlyList<string> FindUnlinkedSaveValueIds() => Client.FindUnlinkedSaveValueIds();
    }

    public sealed class NeoDialogues : NeoDialoguesBase
    {
        public StandardDialogues Standard { get; }

        internal NeoDialogues(TestProjectNeo project, NeoDialogueRuntimeOptions? options)
            : base(project.Client, options, project.Save.NeoMemory, project.ResolveDialogueValue)
        {
            Standard = new StandardDialogues(this, "dialogue-group-standard");
        }
    }

    public sealed class StandardDialogues : NeoStandardDialogueGroup
    {
        internal StandardDialogues(NeoDialogues root, string groupId)
            : base(root, groupId)
        {
        }

        public bool TryTrigger(out NeoDialogue dialogue) =>
            TryTriggerStandard(out dialogue);

        public bool TryTrigger(out NeoDialogueTriggerResult result) =>
            TryTriggerStandard(out result);
    }

    public partial class NeoMemory : INeoDialogueMemoryStore
    {
        public INeoDialogueMemory GetOrCreateDialogueMemory(string dialogueId)
        {
            if (DialogueMemories.TryGetValue(dialogueId, out var memory)) return memory;
            memory = NeoDialogueMemory.CreateSaved(
                client,
                NeoGeneratedTypesSupport.CreateSavedCustomValue(
                    client,
                    "type-dialogue-memory",
                    new Dictionary<string, string>(),
                    Array.Empty<AttributeValue>()));
            DialogueMemories[dialogueId] = memory;
            return memory;
        }

        public INeoDialogueMemory? FindDialogueMemory(string dialogueId)
        {
            return DialogueMemories.TryGetValue(dialogueId, out var memory) ? memory : null;
        }
    }

    public partial class NeoDialogueMemory : INeoDialogueMemory
    {
        public INeoTextNodeMemory GetOrCreateTextNodeMemory(string textNodeId)
        {
            if (TextNodeMemories.TryGetValue(textNodeId, out var memory)) return memory;
            memory = NeoTextNodeMemory.CreateSaved(
                client,
                NeoGeneratedTypesSupport.CreateSavedCustomValue(
                    client,
                    "type-text-node-memory",
                    new Dictionary<string, string>(),
                    Array.Empty<AttributeValue>()));
            TextNodeMemories[textNodeId] = memory;
            return memory;
        }

        public INeoTextNodeMemory? FindTextNodeMemory(string textNodeId)
        {
            return TextNodeMemories.TryGetValue(textNodeId, out var memory) ? memory : null;
        }
    }

    public partial class NeoTextNodeMemory : INeoTextNodeMemory
    {
        public bool HasChoice(string choiceId)
        {
            foreach (var choice in ChoiceHistory)
            {
                if (choice.ChoiceId == choiceId) return true;
            }
            return false;
        }

        public void AddChoice(string choiceId, string createdAt)
        {
            if (HasChoice(choiceId)) return;
            var choiceIdValueId = Guid.NewGuid().ToString();
            var value = new Dictionary<string, string>
            {
                ["ChoiceId"] = choiceIdValueId,
            };
            var valueRows = new List<AttributeValue>
            {
                new StringAttributeValue
                {
                    id = choiceIdValueId,
                    createdAt = createdAt,
                    updatedAt = createdAt,
                    value = choiceId,
                },
            };
            ChoiceHistory.Add(NeoChoiceLog.CreateSaved(
                client,
                NeoGeneratedTypesSupport.CreateSavedCustomValue(
                    client,
                    "type-choice-log",
                    value,
                    valueRows)));
        }
    }

    public sealed class Element : IEquatable<Element>
    {
        private static readonly Dictionary<string, Element> values = new Dictionary<string, Element>();
        public string optionId { get; }

        private Element(string optionId)
        {
            this.optionId = optionId;
        }

        public const string fire = "fire";
        public const string ice = "ice";

        public static Element FromOptionId(string optionId)
        {
            if (values.TryGetValue(optionId, out var known)) return known;
            var created = new Element(optionId);
            values[optionId] = created;
            return created;
        }

        public static string[] ToOptionIds(IEnumerable<Element>? options)
        {
            if (options is null) return Array.Empty<string>();
            var ids = new List<string>();
            foreach (var option in options) ids.Add(option.optionId);
            return ids.ToArray();
        }

        public static bool IsKnown(string id)
        {
            return id switch
            {
                fire => true,
                ice => true,
                _ => false,
            };
        }

        public static implicit operator string(Element value) => value.optionId;
        public static implicit operator Element(string optionId) => FromOptionId(optionId);
        public override string ToString() => optionId;
        public bool Equals(Element? other) => other is not null && optionId == other.optionId;
        public override bool Equals(object? obj) => Equals(obj as Element);
        public override int GetHashCode() => optionId.GetHashCode();
    }

    public partial class ReadOnlyHero : NeoGeneratedCustomValue
    {
        internal ReadOnlyHero(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-hero")
        {
        }

        internal static ReadOnlyHero Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyHero(client, node),
            };
        }

        public string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
        }

        public int? Health
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("Health"));
            }
        }
    }

    public partial class Hero : ReadOnlyHero
    {
        internal Hero(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public Hero(string? Name = null, int? Health = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(Name, Health))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(string? Name = null, int? Health = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (Name is not null)
            {
                var NameValueId = Guid.NewGuid().ToString();
                value["Name"] = NameValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = NameValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Name,
                });
            }
            if (Health is not null)
            {
                var HealthValueId = Guid.NewGuid().ToString();
                value["Health"] = HealthValueId;
                valueRows.Add(new NumberAttributeValue
                {
                    id = HealthValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Health.HasValue ? Health.Value : (double?)null,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-hero", value, valueRows);
        }

        internal static Hero CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new Hero(client, node),
            };
        }

        public new string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Name", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new int? Health
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("Health"));
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Health", NeoGeneratedTypesSupport.Value(value));
            }
        }
    }
    public partial class ReadOnlyRoot : NeoGeneratedCustomValue
    {
        internal ReadOnlyRoot(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-root")
        {
        }

        internal static ReadOnlyRoot Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyRoot(client, node),
            };
        }

        public NeoReadOnlyList<ReadOnlyHero> Heroes
        {
            get
            {
                return new NeoReadOnlyList<ReadOnlyHero>(client, node.Get<NeoAttributeList>("Heroes"), (client, child) => ReadOnlyHero.Create(client, (NeoAttributeCustom)child));
            }
        }

        public string Manifest
        {
            get
            {
                var result = node.Get<NeoAttributeNSGetter>("Manifest").Compute();
                if (!result.ok) throw new InvalidOperationException(result.error ?? "NSGetter evaluation failed.");
                return (string)result.value!;
            }
        }

        public ReadOnlyNeoMemory NeoMemory
        {
            get
            {
                return ReadOnlyNeoMemory.Create(client, node.Get<NeoAttributeCustom>("NeoMemory"));
            }
        }
    }

    public partial class Root : ReadOnlyRoot
    {
        internal Root(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public Root(IEnumerable<Hero>? Heroes = null, NeoMemory? NeoMemory = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(Heroes, NeoMemory))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(IEnumerable<Hero>? Heroes = null, NeoMemory? NeoMemory = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (Heroes is not null)
            {
                var HeroesValueId = Guid.NewGuid().ToString();
                value["Heroes"] = HeroesValueId;
                var HeroesIds = new List<string>();
                foreach (var entry in Heroes)
                {
                    HeroesIds.Add(NeoGeneratedTypesSupport.LookupSelectionId(entry.valueId));
                }
                valueRows.Add(new ArrayAttributeValue
                {
                    id = HeroesValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = HeroesIds.ToArray(),
                });
            }
            if (NeoMemory is not null)
            {
                value["NeoMemory"] = NeoGeneratedTypesSupport.LookupSelectionId(NeoMemory.valueId);
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-root", value, valueRows);
        }

        internal static Root CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new Root(client, node),
            };
        }

        public new NeoList<Hero> Heroes
        {
            get
            {
                return new NeoList<Hero>(client, savedNode.GetOrCreateCollection<NeoAttributeListSaved>("Heroes"), (client, child) => Hero.CreateSaved(client, (NeoAttributeCustomSaved)child), item => NeoGeneratedTypesSupport.ValueReference(item));
            }
        }

        public new string Manifest
        {
            get
            {
                var result = node.Get<NeoAttributeNSGetter>("Manifest").Compute();
                if (!result.ok) throw new InvalidOperationException(result.error ?? "NSGetter evaluation failed.");
                return (string)result.value!;
            }
        }

        public new NeoMemory NeoMemory
        {
            get
            {
                return NeoMemory.CreateSaved(client, node.Get<NeoAttributeCustomSaved>("NeoMemory"));
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "NeoMemory", NeoGeneratedTypesSupport.ValueReference(value));
            }
        }
    }
    public partial class ReadOnlyBase : NeoGeneratedCustomValue
    {
        internal ReadOnlyBase(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-base")
        {
        }

        internal static ReadOnlyBase Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                "type-derived" => new ReadOnlyDerived(client, node),
                "type-override" => new ReadOnlyOverride(client, node),
                _ => new ReadOnlyBase(client, node),
            };
        }

        public string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
        }
    }

    public partial class Base : ReadOnlyBase
    {
        internal Base(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public Base(string? Name = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(Name))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(string? Name = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (Name is not null)
            {
                var NameValueId = Guid.NewGuid().ToString();
                value["Name"] = NameValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = NameValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Name,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-base", value, valueRows);
        }

        internal static Base CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                "type-derived" => new Derived(client, node),
                "type-override" => new Override(client, node),
                _ => new Base(client, node),
            };
        }

        public new string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Name", NeoGeneratedTypesSupport.Value(value));
            }
        }
    }
    public partial class ReadOnlyDerived : ReadOnlyBase
    {
        internal ReadOnlyDerived(NeoClient client, NeoAttributeCustom node)
            : base(client, node)
        {
        }

        internal static ReadOnlyDerived Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyDerived(client, node),
            };
        }

        public int? Health
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("Health"));
            }
        }
    }

    public partial class Derived : Base
    {
        internal Derived(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public Derived(string? Name = null, int? Health = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(Name, Health))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(string? Name = null, int? Health = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (Name is not null)
            {
                var NameValueId = Guid.NewGuid().ToString();
                value["Name"] = NameValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = NameValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Name,
                });
            }
            if (Health is not null)
            {
                var HealthValueId = Guid.NewGuid().ToString();
                value["Health"] = HealthValueId;
                valueRows.Add(new NumberAttributeValue
                {
                    id = HealthValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Health.HasValue ? Health.Value : (double?)null,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-derived", value, valueRows);
        }

        internal static Derived CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new Derived(client, node),
            };
        }

        public new string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Name", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new int? Health
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("Health"));
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Health", NeoGeneratedTypesSupport.Value(value));
            }
        }
    }
    public partial class ReadOnlyOverride : ReadOnlyBase
    {
        internal ReadOnlyOverride(NeoClient client, NeoAttributeCustom node)
            : base(client, node)
        {
        }

        internal static ReadOnlyOverride Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyOverride(client, node),
            };
        }

        public string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
        }
    }

    public partial class Override : Base
    {
        internal Override(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public Override(string? Name = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(Name))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(string? Name = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (Name is not null)
            {
                var NameValueId = Guid.NewGuid().ToString();
                value["Name"] = NameValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = NameValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = Name,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-override", value, valueRows);
        }

        internal static Override CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new Override(client, node),
            };
        }

        public new string? Name
        {
            get
            {
                return node.Get<NeoAttributeString>("Name").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "Name", NeoGeneratedTypesSupport.Value(value));
            }
        }
    }
    public partial class ReadOnlyNeoChoiceLog : NeoGeneratedCustomValue
    {
        internal ReadOnlyNeoChoiceLog(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-choice-log")
        {
        }

        internal static ReadOnlyNeoChoiceLog Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyNeoChoiceLog(client, node),
            };
        }

        public string ChoiceId
        {
            get
            {
                return node.Get<NeoAttributeString>("ChoiceId").value?.value ?? throw new InvalidOperationException("Required string 'ChoiceId' has no value.");
            }
        }
    }

    public partial class NeoChoiceLog : ReadOnlyNeoChoiceLog
    {
        internal NeoChoiceLog(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public NeoChoiceLog(string ChoiceId)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(ChoiceId))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(string ChoiceId)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            var ChoiceIdValueId = Guid.NewGuid().ToString();
            value["ChoiceId"] = ChoiceIdValueId;
            valueRows.Add(new StringAttributeValue
            {
                id = ChoiceIdValueId,
                createdAt = nowIso,
                updatedAt = nowIso,
                value = ChoiceId,
            });
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-choice-log", value, valueRows);
        }

        internal static NeoChoiceLog CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new NeoChoiceLog(client, node),
            };
        }

        public new string ChoiceId
        {
            get
            {
                return node.Get<NeoAttributeString>("ChoiceId").value?.value ?? throw new InvalidOperationException("Required string 'ChoiceId' has no value.");
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "ChoiceId", NeoGeneratedTypesSupport.Value(value));
            }
        }
    }
    public partial class ReadOnlyNeoTextNodeMemory : NeoGeneratedCustomValue
    {
        internal ReadOnlyNeoTextNodeMemory(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-text-node-memory")
        {
        }

        internal static ReadOnlyNeoTextNodeMemory Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyNeoTextNodeMemory(client, node),
            };
        }

        public int VisitCount
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("VisitCount")) ?? throw new InvalidOperationException("Required int 'VisitCount' has no value.");
            }
        }

        public string? LastVisitedAt
        {
            get
            {
                return node.Get<NeoAttributeString>("LastVisitedAt").value?.value;
            }
        }

        public string? MostRecentChoiceId
        {
            get
            {
                return node.Get<NeoAttributeString>("MostRecentChoiceId").value?.value;
            }
        }

        public NeoReadOnlyList<ReadOnlyNeoChoiceLog> ChoiceHistory
        {
            get
            {
                return new NeoReadOnlyList<ReadOnlyNeoChoiceLog>(client, node.Get<NeoAttributeList>("ChoiceHistory"), (client, child) => ReadOnlyNeoChoiceLog.Create(client, (NeoAttributeCustom)child));
            }
        }
    }

    public partial class NeoTextNodeMemory : ReadOnlyNeoTextNodeMemory
    {
        internal NeoTextNodeMemory(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public NeoTextNodeMemory(int? VisitCount = null, string? LastVisitedAt = null, string? MostRecentChoiceId = null, IEnumerable<NeoChoiceLog>? ChoiceHistory = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(VisitCount, LastVisitedAt, MostRecentChoiceId, ChoiceHistory))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(int? VisitCount = null, string? LastVisitedAt = null, string? MostRecentChoiceId = null, IEnumerable<NeoChoiceLog>? ChoiceHistory = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (VisitCount is not null)
            {
                var VisitCountValueId = Guid.NewGuid().ToString();
                value["VisitCount"] = VisitCountValueId;
                valueRows.Add(new NumberAttributeValue
                {
                    id = VisitCountValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = VisitCount.HasValue ? VisitCount.Value : (double?)null,
                });
            }
            if (LastVisitedAt is not null)
            {
                var LastVisitedAtValueId = Guid.NewGuid().ToString();
                value["LastVisitedAt"] = LastVisitedAtValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = LastVisitedAtValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = LastVisitedAt,
                });
            }
            if (MostRecentChoiceId is not null)
            {
                var MostRecentChoiceIdValueId = Guid.NewGuid().ToString();
                value["MostRecentChoiceId"] = MostRecentChoiceIdValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = MostRecentChoiceIdValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = MostRecentChoiceId,
                });
            }
            if (ChoiceHistory is not null)
            {
                var ChoiceHistoryValueId = Guid.NewGuid().ToString();
                value["ChoiceHistory"] = ChoiceHistoryValueId;
                var ChoiceHistoryIds = new List<string>();
                foreach (var entry in ChoiceHistory)
                {
                    ChoiceHistoryIds.Add(NeoGeneratedTypesSupport.LookupSelectionId(entry.valueId));
                }
                valueRows.Add(new ArrayAttributeValue
                {
                    id = ChoiceHistoryValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = ChoiceHistoryIds.ToArray(),
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-text-node-memory", value, valueRows);
        }

        internal static NeoTextNodeMemory CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new NeoTextNodeMemory(client, node),
            };
        }

        public new int VisitCount
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("VisitCount")) ?? throw new InvalidOperationException("Required int 'VisitCount' has no value.");
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "VisitCount", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new string? LastVisitedAt
        {
            get
            {
                return node.Get<NeoAttributeString>("LastVisitedAt").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "LastVisitedAt", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new string? MostRecentChoiceId
        {
            get
            {
                return node.Get<NeoAttributeString>("MostRecentChoiceId").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "MostRecentChoiceId", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new NeoList<NeoChoiceLog> ChoiceHistory
        {
            get
            {
                return new NeoList<NeoChoiceLog>(client, savedNode.GetOrCreateCollection<NeoAttributeListSaved>("ChoiceHistory"), (client, child) => NeoChoiceLog.CreateSaved(client, (NeoAttributeCustomSaved)child), item => NeoGeneratedTypesSupport.ValueReference(item));
            }
        }
    }
    public partial class ReadOnlyNeoDialogueMemory : NeoGeneratedCustomValue
    {
        internal ReadOnlyNeoDialogueMemory(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-dialogue-memory")
        {
        }

        internal static ReadOnlyNeoDialogueMemory Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyNeoDialogueMemory(client, node),
            };
        }

        public int VisitCount
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("VisitCount")) ?? throw new InvalidOperationException("Required int 'VisitCount' has no value.");
            }
        }

        public string? LastVisitedAt
        {
            get
            {
                return node.Get<NeoAttributeString>("LastVisitedAt").value?.value;
            }
        }

        public NeoReadOnlyDictionary<ReadOnlyNeoTextNodeMemory> TextNodeMemories
        {
            get
            {
                return new NeoReadOnlyDictionary<ReadOnlyNeoTextNodeMemory>(client, node.Get<NeoAttributeDictionary>("TextNodeMemories"), (client, child) => ReadOnlyNeoTextNodeMemory.Create(client, (NeoAttributeCustom)child));
            }
        }
    }

    public partial class NeoDialogueMemory : ReadOnlyNeoDialogueMemory
    {
        internal NeoDialogueMemory(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public NeoDialogueMemory(int? VisitCount = null, string? LastVisitedAt = null, IDictionary<string, NeoTextNodeMemory>? TextNodeMemories = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(VisitCount, LastVisitedAt, TextNodeMemories))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(int? VisitCount = null, string? LastVisitedAt = null, IDictionary<string, NeoTextNodeMemory>? TextNodeMemories = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (VisitCount is not null)
            {
                var VisitCountValueId = Guid.NewGuid().ToString();
                value["VisitCount"] = VisitCountValueId;
                valueRows.Add(new NumberAttributeValue
                {
                    id = VisitCountValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = VisitCount.HasValue ? VisitCount.Value : (double?)null,
                });
            }
            if (LastVisitedAt is not null)
            {
                var LastVisitedAtValueId = Guid.NewGuid().ToString();
                value["LastVisitedAt"] = LastVisitedAtValueId;
                valueRows.Add(new StringAttributeValue
                {
                    id = LastVisitedAtValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = LastVisitedAt,
                });
            }
            if (TextNodeMemories is not null)
            {
                var TextNodeMemoriesValueId = Guid.NewGuid().ToString();
                value["TextNodeMemories"] = TextNodeMemoriesValueId;
                var TextNodeMemoriesIds = new Dictionary<string, string>();
                foreach (var pair in TextNodeMemories)
                {
                    TextNodeMemoriesIds[pair.Key] = NeoGeneratedTypesSupport.LookupSelectionId(pair.Value.valueId);
                }
                valueRows.Add(new ObjectAttributeValue
                {
                    id = TextNodeMemoriesValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = TextNodeMemoriesIds,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-dialogue-memory", value, valueRows);
        }

        internal static NeoDialogueMemory CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new NeoDialogueMemory(client, node),
            };
        }

        public new int VisitCount
        {
            get
            {
                return NeoGeneratedTypesSupport.ReadInt(node.Get<NeoAttributeInt>("VisitCount")) ?? throw new InvalidOperationException("Required int 'VisitCount' has no value.");
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "VisitCount", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new string? LastVisitedAt
        {
            get
            {
                return node.Get<NeoAttributeString>("LastVisitedAt").value?.value;
            }
            set
            {
                NeoGeneratedTypesSupport.SetValue(savedNode, "LastVisitedAt", NeoGeneratedTypesSupport.Value(value));
            }
        }

        public new NeoDictionary<NeoTextNodeMemory> TextNodeMemories
        {
            get
            {
                return new NeoDictionary<NeoTextNodeMemory>(client, savedNode.GetOrCreateCollection<NeoAttributeDictionarySaved>("TextNodeMemories"), (client, child) => NeoTextNodeMemory.CreateSaved(client, (NeoAttributeCustomSaved)child), item => NeoGeneratedTypesSupport.ValueReference(item));
            }
        }
    }
    public partial class ReadOnlyNeoMemory : NeoGeneratedCustomValue
    {
        internal ReadOnlyNeoMemory(NeoClient client, NeoAttributeCustom node)
            : base(client, node, "type-neo-memory")
        {
        }

        internal static ReadOnlyNeoMemory Create(NeoClient client, NeoAttributeCustom node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new ReadOnlyNeoMemory(client, node),
            };
        }

        public NeoReadOnlyDictionary<ReadOnlyNeoDialogueMemory> DialogueMemories
        {
            get
            {
                return new NeoReadOnlyDictionary<ReadOnlyNeoDialogueMemory>(client, node.Get<NeoAttributeDictionary>("DialogueMemories"), (client, child) => ReadOnlyNeoDialogueMemory.Create(client, (NeoAttributeCustom)child));
            }
        }
    }

    public partial class NeoMemory : ReadOnlyNeoMemory
    {
        internal NeoMemory(NeoClient client, NeoAttributeCustomSaved node)
            : base(client, node)
        {
        }

        protected NeoAttributeCustomSaved savedNode => (NeoAttributeCustomSaved)node;

        public NeoMemory(IDictionary<string, NeoDialogueMemory>? DialogueMemories = null)
            : this(TestProjectNeo.RequireInstance().Client, CreateFactoryNode(DialogueMemories))
        {
        }

        private static NeoAttributeCustomSaved CreateFactoryNode(IDictionary<string, NeoDialogueMemory>? DialogueMemories = null)
        {
            var client = TestProjectNeo.RequireInstance().Client;
            var nowIso = DateTime.UtcNow.ToString("o");
            var value = new Dictionary<string, string>();
            var valueRows = new List<AttributeValue>();
            if (DialogueMemories is not null)
            {
                var DialogueMemoriesValueId = Guid.NewGuid().ToString();
                value["DialogueMemories"] = DialogueMemoriesValueId;
                var DialogueMemoriesIds = new Dictionary<string, string>();
                foreach (var pair in DialogueMemories)
                {
                    DialogueMemoriesIds[pair.Key] = NeoGeneratedTypesSupport.LookupSelectionId(pair.Value.valueId);
                }
                valueRows.Add(new ObjectAttributeValue
                {
                    id = DialogueMemoriesValueId,
                    createdAt = nowIso,
                    updatedAt = nowIso,
                    value = DialogueMemoriesIds,
                });
            }
            return NeoGeneratedTypesSupport.CreateSavedCustomValue(client, "type-neo-memory", value, valueRows);
        }

        internal static NeoMemory CreateSaved(NeoClient client, NeoAttributeCustomSaved node)
        {
            var clientTypeId = node.value?.typeId;
            return clientTypeId switch
            {
                _ => new NeoMemory(client, node),
            };
        }

        public new NeoDictionary<NeoDialogueMemory> DialogueMemories
        {
            get
            {
                return new NeoDictionary<NeoDialogueMemory>(client, savedNode.GetOrCreateCollection<NeoAttributeDictionarySaved>("DialogueMemories"), (client, child) => NeoDialogueMemory.CreateSaved(client, (NeoAttributeCustomSaved)child), item => NeoGeneratedTypesSupport.ValueReference(item));
            }
        }
    }
}
