// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NeoCompose.Runtime;
using NeoCompose.Runtime.Json;
using NeoCompose.Runtime.NeoScript;
using UnityEngine;

namespace NeoCompose.StaticCompileFixture
{
    public sealed class StaticCompileSmokeNeo : INeoClient
    {
        public static StaticCompileSmokeNeo Instance { get; private set; } = null!;

        internal static StaticCompileSmokeNeo RequireInstance() => Instance ?? throw new InvalidOperationException("StaticCompileSmokeNeo.Instance has not been initialized.");

        public NeoClient Client { get; }
        public NeoMemberClass AssetsRoot => Client.AssetsRoot;
        public NeoMemberClassWritable SaveRoot => Client.SaveRoot;
        public NeoMemberClassWritable SessionRoot => Client.SessionRoot;
        public NeoLocalization Localization => Client.Localization;
        public IReadOnlySmokeRoot Assets { get; }
        public SmokeRoot Save { get; }
        public SmokeRoot Session { get; }
        public NeoDialogues Dialogues { get; }

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.ReadOnlyClassFactory> DialogueReadOnlyValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.ReadOnlyClassFactory>
            {
                ["static-smoke-item-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeItem.Create(client, node),
                ["static-smoke-root-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRoot.Create(client, node),
                ["static-smoke-rules-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRules.Create(client, node),
            };

        internal static IReadOnlyDictionary<string, NeoGeneratedTypesSupport.ReadOnlyClassFactory> NeoReadOnlyValueFactories =>
            DialogueReadOnlyValueFactories;

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.WritableClassFactory> DialogueWritableValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.WritableClassFactory>
            {
                ["static-smoke-item-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeItem.CreateWritable(client, node),
                ["static-smoke-root-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRoot.CreateWritable(client, node),
                ["static-smoke-rules-class"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRules.CreateWritable(client, node),
            };

        internal static IReadOnlyDictionary<string, NeoGeneratedTypesSupport.WritableClassFactory> NeoWritableValueFactories =>
            DialogueWritableValueFactories;

        internal static readonly IReadOnlyDictionary<Type, string> NeoClassIdsByType =
            new Dictionary<Type, string>
            {
                [typeof(global::NeoCompose.StaticCompileFixture.SmokeItem)] = "static-smoke-item-class",
                [typeof(global::NeoCompose.StaticCompileFixture.SmokeRoot)] = "static-smoke-root-class",
                [typeof(global::NeoCompose.StaticCompileFixture.SmokeRules)] = "static-smoke-rules-class",
            };

        internal object? ResolveDialogueValue(string valueId) =>
            NeoGeneratedTypesSupport.ResolveClassValue(
                Client,
                valueId,
                DialogueReadOnlyValueFactories,
                DialogueWritableValueFactories);

        private static readonly IReadOnlyDictionary<string, NeoClient.NeoNativeFunctionInvoker> NativeFunctionInvokers =
            new Dictionary<string, NeoClient.NeoNativeFunctionInvoker>
            {
                ["static-smoke-reset"] = (client, receiver, args) =>
                {
                var amount = Convert.ToInt32(args[0]);
                var rate = NeoDecimalValues.Parse((string)args[1]!);
                var dir = SmokeDirection.FromOptionId(NeoGeneratedTypesSupport.ToStringArray(args[2])[0]);
                return global::NeoCompose.StaticCompileFixture.SmokeRules.Reset(amount, rate, dir);
                },
                ["static-smoke-greet"] = (client, receiver, args) =>
                {
                var target = NeoGeneratedTypesSupport.ResolveNativeFunctionReceiver<SmokeRules>(
                    client,
                    receiver,
                    DialogueReadOnlyValueFactories,
                    DialogueWritableValueFactories,
                    "Greet",
                    "static-smoke-greet");
                var name = (string)args[0]!;
                return target.Greet(name);
                },
            };

        private static readonly IReadOnlyDictionary<string, NeoClient.NeoDeferredNativeFunctionInvoker> DeferredNativeFunctionInvokers =
            new Dictionary<string, NeoClient.NeoDeferredNativeFunctionInvoker>
            {
                ["static-smoke-wait"] = (client, receiver, args, deferred) =>
                {
                if (global::NeoCompose.StaticCompileFixture.SmokeRules.StaticFunctionHandler is null)
                {
                    throw new NeoFunctionHandlerMissingException(
                        "Cannot invoke static deferred Function 'Wait' because SmokeRules.StaticFunctionHandler is not set.");
                }
                var typedDeferred = NeoGeneratedTypesSupport.ResolveDeferredFunction<NeoDeferredFunction>(deferred, "Wait");
                global::NeoCompose.StaticCompileFixture.SmokeRules.StaticFunctionHandler.Wait(typedDeferred);
                },
            };

        public StaticCompileSmokeNeo(NeoClient client, NeoDialogueRuntimeOptions? dialogueOptions = null)
        {
            if (Instance is not null)
            {
                throw new InvalidOperationException("Only one active StaticCompileSmokeNeo is allowed while generated static members are enabled. Dispose the existing project client first.");
            }
            Client = client;
            Client.RegisterGeneratedClassFactories(DialogueReadOnlyValueFactories, DialogueWritableValueFactories);
            Client.RegisterNativeFunctionInvokers(NativeFunctionInvokers);
            Client.RegisterDeferredNativeFunctionInvokers(DeferredNativeFunctionInvokers);
            Instance = this;
            Assets = new SmokeRoot(client, client.assets, true, NeoValueOwnership.Asset);
            Save = new SmokeRoot(client, client.save, false, client.save.ownership);
            Session = new SmokeRoot(client, client.session, false, client.session.ownership);
            Dialogues = new NeoDialogues(this, dialogueOptions);
        }

        public static async Awaitable<StaticCompileSmokeNeo> Load(INeoSaveLoader synchronizer, NeoDialogueRuntimeOptions? dialogueOptions = null, NeoAssetDatabase? assetDatabase = null, NeoLocalizationOptions? localizationOptions = null, NeoSaveOptions? saveOptions = null)
        {
            var client = await new NeoLoader().Load(synchronizer, assetDatabase, localizationOptions, null, saveOptions);
            return new StaticCompileSmokeNeo(client, dialogueOptions);
        }

        public INeoSaveLoader Synchronizer => Client.Synchronizer;

        public INeoApiClient? ApiClient => Client.ApiClient;

        public NeoAuthentication? Authentication => Client.Authentication;

        public string SerializeSaveData() => Client.SerializeSaveData();

        public Awaitable CommitAsync(bool replaceSnapshot = false) => Client.CommitAsync(replaceSnapshot);

        public int RunGarbageCollector() => Client.RunGarbageCollector();

        public IReadOnlyList<string> FindUnlinkedSaveValueIds() => Client.FindUnlinkedSaveValueIds();

        public void Dispose()
        {
            Client.Dispose();
            if (ReferenceEquals(Instance, this)) Instance = null!;
        }
    }

    public sealed class NeoDialogues : NeoDialoguesBase
    {
        internal NeoDialogues(StaticCompileSmokeNeo project, NeoDialogueRuntimeOptions? options)
            : base(project.Client, options, null, project.ResolveDialogueValue)
        {
        }
    }

    public sealed class SmokeDirection : IEquatable<SmokeDirection>, global::NeoCompose.Runtime.INeoEnumOption
    {
        private static readonly Dictionary<string, SmokeDirection> values = new Dictionary<string, SmokeDirection>();
        public string optionId { get; }
        public string Text => TextForOptionId(optionId);
        public string TextId => TextIdForOptionId(optionId);

        private SmokeDirection(string optionId)
        {
            this.optionId = optionId;
        }

        public static readonly SmokeDirection North = FromOptionId("static-smoke-direction-north");
        public static readonly SmokeDirection South = FromOptionId("static-smoke-direction-south");

        public static SmokeDirection FromOptionId(string optionId)
        {
            if (values.TryGetValue(optionId, out var known)) return known;
            var created = new SmokeDirection(optionId);
            values[optionId] = created;
            return created;
        }

        public static string[] ToOptionIds(IEnumerable<SmokeDirection>? options)
        {
            if (options is null) return Array.Empty<string>();
            var ids = new List<string>();
            foreach (var option in options) ids.Add(option.optionId);
            return ids.ToArray();
        }

        public static bool IsKnown(string id)
        {
            return id switch
            {
                "static-smoke-direction-north" => true,
                "static-smoke-direction-south" => true,
                _ => false,
            };
        }

        public static string TextIdForOptionId(string optionId)
        {
            return optionId switch
            {
                "static-smoke-direction-north" => "North",
                "static-smoke-direction-south" => "South",
                _ => optionId,
            };
        }

        public static string TextForOptionId(string optionId, NeoClient? client = null)
        {
            return (client ?? StaticCompileSmokeNeo.RequireInstance().Client).Localization.ResolveText(TextIdForOptionId(optionId));
        }

        public static implicit operator string(SmokeDirection value) => value.optionId;
        public static implicit operator SmokeDirection(string optionId) => FromOptionId(optionId);
        public override string ToString() => optionId;
        public bool Equals(SmokeDirection? other) => other is not null && optionId == other.optionId;
        public override bool Equals(object? obj) => Equals(obj as SmokeDirection);
        public override int GetHashCode() => optionId.GetHashCode();
        public static bool operator ==(SmokeDirection? left, SmokeDirection? right) => ReferenceEquals(left, right) || (left is not null && left.Equals(right));
        public static bool operator !=(SmokeDirection? left, SmokeDirection? right) => !(left == right);
    }

    public interface ISmokeGreeter
    {
        string Greet(string name = "friend");
    }

    public interface IReadOnlySmokeRoot : INeoValueReference
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeRoot Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeRoot writable);
    }

    public partial class SmokeRoot : NeoGeneratedClassValue, IReadOnlySmokeRoot
    {
        internal SmokeRoot(NeoClient client, NeoMemberClass node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-root-class", isReadOnly, inheritedStorageOwnership)
        {
        }

        public SmokeRoot()
            : this(StaticCompileSmokeNeo.RequireInstance().Client, CreateFactoryNode(), false, NeoValueOwnership.Session)
        {
        }

        private static NeoMemberClassWritable CreateFactoryNode()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return NeoGeneratedTypesSupport.CreateWritableClassValue(client, "static-smoke-root-class");
        }

        internal static SmokeRoot Create(NeoClient client, NeoMemberClass node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeRoot>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeRoot(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeRoot CreateWritable(NeoClient client, NeoMemberClassWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeRoot>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeRoot(client, node, false, node.ownership),
                };
            });
        }

        public SmokeRoot Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneClassValue(client, this));
        }

        IReadOnlySmokeRoot IReadOnlySmokeRoot.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeRoot writable)
        {
            return TryWritable<SmokeRoot>(out writable);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }
    public interface IReadOnlySmokeItem : INeoValueReference
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeItem Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeItem writable);
    }

    public partial class SmokeItem : NeoGeneratedClassValue, IReadOnlySmokeItem
    {
        internal SmokeItem(NeoClient client, NeoMemberClass node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-item-class", isReadOnly, inheritedStorageOwnership)
        {
        }

        public SmokeItem(string label, string motto = "GO\n\"far\"", SmokeDirection? dir = null, string? nick = null)
            : this(StaticCompileSmokeNeo.RequireInstance().Client, NeoGeneratedTypesSupport.EvaluateDeclaredConstructor(StaticCompileSmokeNeo.RequireInstance().Client, "static-smoke-item-class", "static-smoke-item-ctor", new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument[] { new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("label", label), new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("motto", motto), new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("dir", dir ?? SmokeDirection.North), new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("nick", nick) }), false, NeoValueOwnership.Session)
        {
        }

        internal static SmokeItem Create(NeoClient client, NeoMemberClass node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeItem>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeItem(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeItem CreateWritable(NeoClient client, NeoMemberClassWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeItem>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeItem(client, node, false, node.ownership),
                };
            });
        }

        public SmokeItem Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneClassValue(client, this));
        }

        IReadOnlySmokeItem IReadOnlySmokeItem.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeItem writable)
        {
            return TryWritable<SmokeItem>(out writable);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }
    public interface ISmokeRulesStaticFunctionHandler
    {
        int Reset(int amount, decimal rate, SmokeDirection dir);
        void Wait(NeoDeferredFunction deferred);
    }

    public interface ISmokeRulesFunctionHandler
    {
        string Greet(string name);
    }

    public interface IReadOnlySmokeRules : INeoValueReference, ISmokeGreeter
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeRules Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeRules writable);

        new string Greet(string name = "friend");
    }

    public partial class SmokeRules : NeoGeneratedClassValue, IReadOnlySmokeRules
    {
        internal SmokeRules(NeoClient client, NeoMemberClass node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-rules-class", isReadOnly, inheritedStorageOwnership)
        {
        }

        public static int GlobalCount
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-count", NeoValueOwnership.Session);
                var child = binding.GetRequiredNode<NeoMemberInt>();
                return NeoGeneratedTypesSupport.ReadInt((NeoMemberInt)child) ?? throw new InvalidOperationException("Required int 'Global Count' has no value.");
            }
            set
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-count", NeoValueOwnership.Session);
                binding.SetValue(NeoGeneratedTypesSupport.Value(value));
            }
        }

        public static string Motto
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-motto", NeoValueOwnership.Asset);
                var child = binding.GetRequiredNode<NeoMemberString>();
                return ((NeoMemberString)child).value?.value ?? throw new InvalidOperationException("Required string 'Motto' has no value.");
            }
        }

        public static NeoList<string> Names
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-names", NeoValueOwnership.Save);
                var child = binding.GetNodeOrEmpty<NeoMemberListWritable>();
                return new NeoList<string>(client, child, () => binding.GetOrCreateWritableNode<NeoMemberListWritable>(Array.Empty<string>()), (client, child) => ((NeoMemberString)child).value?.value ?? throw new InvalidOperationException("Required string 'Entry' has no value."), item => NeoGeneratedTypesSupport.Value(item));
            }
        }

        public static SmokeItem? Current
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-current", NeoValueOwnership.Session);
                if (!binding.TryGetNode<NeoMemberClassWritable>(out var child) || child is null) return null;
                return ((NeoMemberClass)child).value is null ? null : global::NeoCompose.StaticCompileFixture.SmokeItem.CreateWritable(client, (NeoMemberClassWritable)child);
            }
            set
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-current", NeoValueOwnership.Session);
                binding.BindValue(value);
            }
        }

        public static int Reset(int amount, decimal rate = 2.75m, SmokeDirection? dir = null)
        {
            var dirValue = dir ?? SmokeDirection.South;
            if (SmokeRules.StaticFunctionHandler is null)
            {
                throw new NeoFunctionHandlerMissingException("Cannot invoke static Function 'Reset' because SmokeRules.StaticFunctionHandler is not set.");
            }
            return SmokeRules.StaticFunctionHandler.Reset(amount, rate, dirValue);
        }

        public static Task Wait()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return client.InvokeDeferredNativeFunction("static-smoke-wait", null, new object?[] { });
        }

        public static int Calculate(int amount, int bonus = -1)
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            var node = new NeoMemberNSFunction(client, "static-smoke-calculate", null, NeoValueOwnership.Session);
            var result = node.InvokeStatic(new object?[] { amount, bonus });
            return Convert.ToInt32(result);
        }

        public static ISmokeRulesStaticFunctionHandler? StaticFunctionHandler { get; set; }

        public ISmokeRulesFunctionHandler? FunctionHandler
        {
            get => FunctionHandlerObject as ISmokeRulesFunctionHandler;
            set => FunctionHandlerObject = value;
        }

        public SmokeRules(string tag, int seed = -3)
            : this(StaticCompileSmokeNeo.RequireInstance().Client, NeoGeneratedTypesSupport.EvaluateDeclaredConstructor(StaticCompileSmokeNeo.RequireInstance().Client, "static-smoke-rules-class", "static-smoke-rules-ctor", new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument[] { new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("tag", tag), new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument("seed", seed) }), false, NeoValueOwnership.Session)
        {
        }

        public SmokeRules()
            : this(StaticCompileSmokeNeo.RequireInstance().Client, NeoGeneratedTypesSupport.EvaluateDeclaredConstructor(StaticCompileSmokeNeo.RequireInstance().Client, "static-smoke-rules-class", null, new global::NeoCompose.Runtime.NeoDeclaredConstructorArgument[] { }), false, NeoValueOwnership.Session)
        {
        }

        internal static SmokeRules Create(NeoClient client, NeoMemberClass node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeRules>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeRules(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeRules CreateWritable(NeoClient client, NeoMemberClassWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedClassValue<SmokeRules>(client, node, () =>
            {
                var clientClassId = node.value?.classId;
                return clientClassId switch
                {
                    _ => new SmokeRules(client, node, false, node.ownership),
                };
            });
        }

        public SmokeRules Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneClassValue(client, this));
        }

        IReadOnlySmokeRules IReadOnlySmokeRules.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeRules writable)
        {
            return TryWritable<SmokeRules>(out writable);
        }


        public string Greet(string name = "friend")
        {
            if (FunctionHandler is null)
            {
                var valueDescription = valueId is null ? "without a backing value id" : $"for value '{valueId}'";
                throw new NeoFunctionHandlerMissingException(
                    $"Cannot invoke Function 'Greet' on {GetType().Name} {valueDescription} because FunctionHandler is not set.");
            }
            return FunctionHandler.Greet(name);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }

}
