// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using NeoCompose.Runtime;
using NeoCompose.Runtime.Json;
using NeoCompose.Runtime.NeoScript;
using UnityEngine;

namespace NeoCompose.StaticCompileFixture
{
    public sealed class StaticCompileSmokeNeo : INeoClient
    {
        public static StaticCompileSmokeNeo Instance { get; private set; } = null!;

        internal static StaticCompileSmokeNeo RequireInstance() => Instance ?? throw new InvalidOperationException("StaticCompileSmokeNeo.Instance has not been initialized.");

        public NeoClient Client { get; }
        public NeoAttributeCustom AssetsRoot => Client.AssetsRoot;
        public NeoAttributeCustomWritable SaveRoot => Client.SaveRoot;
        public NeoAttributeCustomWritable SessionRoot => Client.SessionRoot;
        public NeoLocalization Localization => Client.Localization;
        public IReadOnlySmokeRoot Assets { get; }
        public SmokeRoot Save { get; }
        public SmokeRoot Session { get; }
        public NeoDialogues Dialogues { get; }

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.ReadOnlyCustomFactory> DialogueReadOnlyValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.ReadOnlyCustomFactory>
            {
                ["static-smoke-item-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeItem.Create(client, node),
                ["static-smoke-root-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRoot.Create(client, node),
                ["static-smoke-rules-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRules.Create(client, node),
            };

        internal static IReadOnlyDictionary<string, NeoGeneratedTypesSupport.ReadOnlyCustomFactory> NeoReadOnlyValueFactories =>
            DialogueReadOnlyValueFactories;

        private static readonly IReadOnlyDictionary<string, NeoGeneratedTypesSupport.WritableCustomFactory> DialogueWritableValueFactories =
            new Dictionary<string, NeoGeneratedTypesSupport.WritableCustomFactory>
            {
                ["static-smoke-item-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeItem.CreateWritable(client, node),
                ["static-smoke-root-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRoot.CreateWritable(client, node),
                ["static-smoke-rules-type"] = (client, node) => global::NeoCompose.StaticCompileFixture.SmokeRules.CreateWritable(client, node),
            };

        internal static IReadOnlyDictionary<string, NeoGeneratedTypesSupport.WritableCustomFactory> NeoWritableValueFactories =>
            DialogueWritableValueFactories;

        internal object? ResolveDialogueValue(string valueId) =>
            NeoGeneratedTypesSupport.ResolveCustomValue(
                Client,
                valueId,
                DialogueReadOnlyValueFactories,
                DialogueWritableValueFactories);

        private static readonly IReadOnlyDictionary<string, NeoClient.NeoNativeFunctionInvoker> NativeFunctionInvokers =
            new Dictionary<string, NeoClient.NeoNativeFunctionInvoker>
            {
                ["static-smoke-reset"] = (client, receiver, args) =>
                {
                var amount = Convert.ToInt32(args[0]);
                return global::NeoCompose.StaticCompileFixture.SmokeRules.Reset(amount);
                },
            };

        private static readonly IReadOnlyDictionary<string, NeoClient.NeoDeferredNativeFunctionInvoker> DeferredNativeFunctionInvokers =
            new Dictionary<string, NeoClient.NeoDeferredNativeFunctionInvoker>
            {
                ["static-smoke-wait"] = (client, receiver, args, deferred) =>
                {
                if (global::NeoCompose.StaticCompileFixture.SmokeRules.StaticFunctionHandler is null)
                {
                    throw new NeoFunctionHandlerMissingException(
                        "Cannot invoke static deferred Function 'Wait' because SmokeRules.StaticFunctionHandler is not set.");
                }
                var typedDeferred = NeoGeneratedTypesSupport.ResolveDeferredFunction<NeoDeferredFunction>(deferred, "Wait");
                global::NeoCompose.StaticCompileFixture.SmokeRules.StaticFunctionHandler.Wait(typedDeferred);
                },
            };

        public StaticCompileSmokeNeo(NeoClient client, NeoDialogueRuntimeOptions? dialogueOptions = null)
        {
            if (Instance is not null)
            {
                throw new InvalidOperationException("Only one active StaticCompileSmokeNeo is allowed while generated static members are enabled. Dispose the existing project client first.");
            }
            Client = client;
            Client.RegisterNativeFunctionInvokers(NativeFunctionInvokers);
            Client.RegisterDeferredNativeFunctionInvokers(DeferredNativeFunctionInvokers);
            Instance = this;
            Assets = new SmokeRoot(client, client.assets, true, NeoValueOwnership.Asset);
            Save = new SmokeRoot(client, client.save, false, client.save.ownership);
            Session = new SmokeRoot(client, client.session, false, client.session.ownership);
            Dialogues = new NeoDialogues(this, dialogueOptions);
        }

        public static async Awaitable<StaticCompileSmokeNeo> Load(INeoSaveLoader synchronizer, NeoDialogueRuntimeOptions? dialogueOptions = null, NeoAssetDatabase? assetDatabase = null, NeoLocalizationOptions? localizationOptions = null, NeoSaveOptions? saveOptions = null)
        {
            var client = await new NeoLoader().Load(synchronizer, assetDatabase, localizationOptions, null, saveOptions);
            return new StaticCompileSmokeNeo(client, dialogueOptions);
        }

        public INeoSaveLoader Synchronizer => Client.Synchronizer;

        public INeoApiClient? ApiClient => Client.ApiClient;

        public NeoAuthentication? Authentication => Client.Authentication;

        public string SerializeSaveData() => Client.SerializeSaveData();

        public Awaitable CommitAsync(bool replaceSnapshot = false) => Client.CommitAsync(replaceSnapshot);

        public int RunGarbageCollector() => Client.RunGarbageCollector();

        public IReadOnlyList<string> FindUnlinkedSaveValueIds() => Client.FindUnlinkedSaveValueIds();

        public void Dispose()
        {
            Client.Dispose();
            if (ReferenceEquals(Instance, this)) Instance = null!;
        }
    }

    public sealed class NeoDialogues : NeoDialoguesBase
    {
        internal NeoDialogues(StaticCompileSmokeNeo project, NeoDialogueRuntimeOptions? options)
            : base(project.Client, options, null, project.ResolveDialogueValue)
        {
        }
    }


    public interface IReadOnlySmokeRoot : INeoValueReference
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeRoot Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeRoot writable);
    }

    public partial class SmokeRoot : NeoGeneratedCustomValue, IReadOnlySmokeRoot
    {
        internal SmokeRoot(NeoClient client, NeoAttributeCustom node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-root-type", isReadOnly, inheritedStorageOwnership)
        {
        }

        public SmokeRoot()
            : this(StaticCompileSmokeNeo.RequireInstance().Client, CreateFactoryNode(), false, NeoValueOwnership.Session)
        {
        }

        private static NeoAttributeCustomWritable CreateFactoryNode()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return NeoGeneratedTypesSupport.CreateWritableCustomValue(client, "static-smoke-root-type");
        }

        internal static SmokeRoot Create(NeoClient client, NeoAttributeCustom node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeRoot>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeRoot(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeRoot CreateWritable(NeoClient client, NeoAttributeCustomWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeRoot>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeRoot(client, node, false, node.ownership),
                };
            });
        }

        public SmokeRoot Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneCustomValue(client, this));
        }

        IReadOnlySmokeRoot IReadOnlySmokeRoot.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeRoot writable)
        {
            return TryWritable<SmokeRoot>(out writable);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }
    public interface IReadOnlySmokeItem : INeoValueReference
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeItem Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeItem writable);
    }

    public partial class SmokeItem : NeoGeneratedCustomValue, IReadOnlySmokeItem
    {
        internal SmokeItem(NeoClient client, NeoAttributeCustom node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-item-type", isReadOnly, inheritedStorageOwnership)
        {
        }

        public SmokeItem()
            : this(StaticCompileSmokeNeo.RequireInstance().Client, CreateFactoryNode(), false, NeoValueOwnership.Session)
        {
        }

        private static NeoAttributeCustomWritable CreateFactoryNode()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return NeoGeneratedTypesSupport.CreateWritableCustomValue(client, "static-smoke-item-type");
        }

        internal static SmokeItem Create(NeoClient client, NeoAttributeCustom node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeItem>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeItem(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeItem CreateWritable(NeoClient client, NeoAttributeCustomWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeItem>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeItem(client, node, false, node.ownership),
                };
            });
        }

        public SmokeItem Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneCustomValue(client, this));
        }

        IReadOnlySmokeItem IReadOnlySmokeItem.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeItem writable)
        {
            return TryWritable<SmokeItem>(out writable);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }
    public interface ISmokeRulesStaticFunctionHandler
    {
        int Reset(int amount);
        void Wait(NeoDeferredFunction deferred);
    }

    public interface IReadOnlySmokeRules : INeoValueReference
    {
        bool IsReadOnly { get; }

        IReadOnlySmokeRules Clone();

        bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference;

        bool TryWritable(out SmokeRules writable);
    }

    public partial class SmokeRules : NeoGeneratedCustomValue, IReadOnlySmokeRules
    {
        internal SmokeRules(NeoClient client, NeoAttributeCustom node, bool isReadOnly, NeoValueOwnership inheritedStorageOwnership = NeoValueOwnership.Asset)
            : base(client, node, "static-smoke-rules-type", isReadOnly, inheritedStorageOwnership)
        {
        }

        public static int GlobalCount
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-count", NeoValueOwnership.Session);
                var child = binding.GetRequiredNode<NeoAttributeInt>();
                return NeoGeneratedTypesSupport.ReadInt((NeoAttributeInt)child) ?? throw new InvalidOperationException("Required int 'Global Count' has no value.");
            }
            set
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-count", NeoValueOwnership.Session);
                binding.SetValue(NeoGeneratedTypesSupport.Value(value));
            }
        }

        public static string Motto
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-motto", NeoValueOwnership.Asset);
                var child = binding.GetRequiredNode<NeoAttributeString>();
                return ((NeoAttributeString)child).value?.value ?? throw new InvalidOperationException("Required string 'Motto' has no value.");
            }
        }

        public static NeoList<string> Names
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-names", NeoValueOwnership.Save);
                var child = binding.GetNodeOrEmpty<NeoAttributeListWritable>();
                return new NeoList<string>(client, child, () => binding.GetOrCreateWritableNode<NeoAttributeListWritable>(Array.Empty<string>()), (client, child) => ((NeoAttributeString)child).value?.value ?? throw new InvalidOperationException("Required string 'Entry' has no value."), item => NeoGeneratedTypesSupport.Value(item));
            }
        }

        public static SmokeItem? Current
        {
            get
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-current", NeoValueOwnership.Session);
                if (!binding.TryGetNode<NeoAttributeCustomWritable>(out var child) || child is null) return null;
                return ((NeoAttributeCustom)child).value is null ? null : global::NeoCompose.StaticCompileFixture.SmokeItem.CreateWritable(client, (NeoAttributeCustomWritable)child);
            }
            set
            {
                var client = StaticCompileSmokeNeo.RequireInstance().Client;
                var binding = NeoGeneratedTypesSupport.StaticBinding(client, "static-smoke-current", NeoValueOwnership.Session);
                binding.BindValue(value);
            }
        }

        public static int Reset(int amount)
        {
            if (SmokeRules.StaticFunctionHandler is null)
            {
                throw new NeoFunctionHandlerMissingException("Cannot invoke static Function 'Reset' because SmokeRules.StaticFunctionHandler is not set.");
            }
            return SmokeRules.StaticFunctionHandler.Reset(amount);
        }

        public static Task Wait()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return client.InvokeDeferredNativeFunction("static-smoke-wait", null, new object?[] { });
        }

        public static int Calculate(int amount)
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            var node = new NeoAttributeNSFunction(client, "static-smoke-calculate", null, NeoValueOwnership.Session);
            var result = node.InvokeStatic(new object?[] { amount });
            return Convert.ToInt32(result);
        }

        public static ISmokeRulesStaticFunctionHandler? StaticFunctionHandler { get; set; }

        public SmokeRules()
            : this(StaticCompileSmokeNeo.RequireInstance().Client, CreateFactoryNode(), false, NeoValueOwnership.Session)
        {
        }

        private static NeoAttributeCustomWritable CreateFactoryNode()
        {
            var client = StaticCompileSmokeNeo.RequireInstance().Client;
            return NeoGeneratedTypesSupport.CreateWritableCustomValue(client, "static-smoke-rules-type");
        }

        internal static SmokeRules Create(NeoClient client, NeoAttributeCustom node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeRules>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeRules(client, node, true, NeoValueOwnership.Asset),
                };
            });
        }

        internal static SmokeRules CreateWritable(NeoClient client, NeoAttributeCustomWritable node)
        {
            return NeoGeneratedTypesSupport.GetOrCreateGeneratedCustomValue<SmokeRules>(client, node, () =>
            {
                var clientTypeId = node.value?.typeId;
                return clientTypeId switch
                {
                    _ => new SmokeRules(client, node, false, node.ownership),
                };
            });
        }

        public SmokeRules Clone()
        {
            return CreateWritable(client, NeoGeneratedTypesSupport.CloneCustomValue(client, this));
        }

        IReadOnlySmokeRules IReadOnlySmokeRules.Clone()
        {
            return Clone();
        }

        public new bool TryWritable<TWritable>(out TWritable writable) where TWritable : class, INeoValueReference
        {
            return base.TryWritable(out writable);
        }

        public bool TryWritable(out SmokeRules writable)
        {
            return TryWritable<SmokeRules>(out writable);
        }

        public sealed class Fields
        {
            private Fields() {}
        }

        private IReadOnlyDictionary<INeoField, Func<string?>> LocalizedTextIdReaders()
        {
            return new Dictionary<INeoField, Func<string?>>
            {
            };
        }

        public string? GetLocalizedTextId<T>(NeoField<T> field)
        {
            var readers = LocalizedTextIdReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return reader();
        }

        private IReadOnlyDictionary<INeoField, Func<object?>> ChangedFieldReaders()
        {
            return new Dictionary<INeoField, Func<object?>>
            {
            };
        }

        public IDisposable OnChanged<T>(NeoField<T> field, Action<T, NeoChangeSource> handler)
        {
            var readers = ChangedFieldReaders();
            if (!readers.TryGetValue(field, out var reader))
            {
                throw new ArgumentException($"Field '{field.Key}' is not defined on this generated type.", nameof(field));
            }
            return WatchField(field, handler, reader);
        }

        public IDisposable OnChanged(Action<NeoChangedArgs<Fields>> handler)
        {
            return WatchChanges(ChangedFieldReaders(), handler);
        }
    }

}
