// Copyright (c) Ryan Bliss and contributors. All rights reserved.
// Licensed under the MIT License.

using System.IO;
using System.Collections.Generic;
using System.Linq;
using NeoCompose.Runtime.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NUnit.Framework;

namespace NeoCompose.Tests
{
    /// <summary>
    /// Newtonsoft.Json round-trip coverage for <see cref="ProjectData"/>
    /// and the full IR tree rooted on <see cref="Member.getter"/>.
    ///
    /// Two fixtures back the suite:
    ///
    ///  - <c>synth-example.json</c> — generated by the TS-side dump
    ///    script (`scripts/dump-synth-export.ts`). Designed to exercise
    ///    every IR variant: list / dict literals, force-unwrap,
    ///    isCheck, callGetter, coalesce, where / count functions, both
    ///    arithmetic + boolean operations, and the four instruction
    ///    kinds (variable / if / return / throw, plus the bare
    ///    <c>return;</c> null-pointer case).
    ///  - <c>project-example.json</c> — a real-world export captured
    ///    from a live Neo-Compose authoring session.
    ///
    /// Tests load each fixture from
    /// <c>Packages/com.ryanbliss.neocompose/Tests/</c> (the canonical
    /// Unity Package Manager path for local-path references and
    /// registry installs alike) and pass the JSON through
    /// <see cref="JsonConvert.DeserializeObject{T}(string)"/>.
    /// </summary>
    public class ProjectExportRoundTripTests
    {
        private const string PackageRoot =
            "Packages/com.ryanbliss.neocompose/Tests";

        private static string LoadFixture(string fileName)
        {
            return File.ReadAllText(Path.Combine(PackageRoot, fileName));
        }

        private static ProjectData Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<ProjectData>(json);
        }

        [Test]
        public void AnimationMemberMetadata_RoundTripsPartialFunctionRefAndUiBody()
        {
            const string classJson = @"{
  'id':'partial','projectId':'project','name':'Overrides','kind':7,
  'locked':true,'required':false,'isStatic':false,'accessModifierKind':'public',
  'classId':'target','partial':true,'createdAt':'x','updatedAt':'x'
}";
            var partial = (ClassMember)JsonConvert.DeserializeObject<Member>(classJson)!;
            Assert.AreEqual(true, partial.partial);

            const string genericJson = @"{
  'id':'generic-partial','projectId':'project','name':'Overrides','kind':21,
  'locked':true,'required':false,'isStatic':false,'accessModifierKind':'public',
  'genericParamId':'target-param','partial':true,'createdAt':'x','updatedAt':'x'
}";
            var generic = (GenericMember)JsonConvert.DeserializeObject<Member>(genericJson)!;
            Assert.AreEqual(true, generic.partial);

            const string functionRefJson = @"{
  'id':'action-ref','projectId':'project','name':'Action','kind':24,
  'locked':true,'required':true,'isStatic':false,'accessModifierKind':'public',
  'defaultValue':{'value':{'functionMemberId':'function-a'}},
  'createdAt':'x','updatedAt':'x'
}";
            var functionRef = (FunctionRefMember)JsonConvert.DeserializeObject<Member>(functionRefJson)!;
            Assert.AreEqual(24, (int)functionRef.kind);
            Assert.AreEqual("function-a", functionRef.defaultValue!.value!["functionMemberId"]);

            const string nsFunctionJson = @"{
  'id':'ui-function','projectId':'project','name':'OnFrame','kind':23,
  'locked':false,'required':false,'isStatic':false,'accessModifierKind':'public',
  'code':'return;','bodyMode':'ui','returnTypeInfo':{'type':'Void','required':true},
  'argumentTypes':[],'deferred':false,'createdAt':'x','updatedAt':'x',
  'uiAction':{'parameters':[],'instructions':[],'typeInfo':{'type':0,'required':true}},
  'action':{'parameters':[],'instructions':[],'typeInfo':{'type':0,'required':true}}
}";
            var nsFunction = (NSFunctionMember)JsonConvert.DeserializeObject<Member>(nsFunctionJson)!;
            Assert.AreEqual("ui", nsFunction.bodyMode);
            Assert.IsNotNull(nsFunction.uiAction);

            JObject serialized = JObject.Parse(JsonConvert.SerializeObject(nsFunction));
            Assert.AreEqual("ui", serialized.Value<string>("bodyMode"));
            Assert.IsNotNull(serialized["uiAction"]);

            const string placedChildJson = @"{
  'id':'placed-child','classId':'sprite-child','sourceValueId':'authored-child',
  'createdAt':'x','updatedAt':'x','value':{}
}";
            var placedChild = (ObjectMemberValue)JsonConvert
                .DeserializeObject<MemberValue>(placedChildJson)!;
            Assert.AreEqual("authored-child", placedChild.sourceValueId);
            JObject serializedChild = JObject.Parse(
                JsonConvert.SerializeObject(placedChild));
            Assert.AreEqual(
                "authored-child",
                serializedChild.Value<string>("sourceValueId"));
        }

        [Test]
        public void NSPropertySetter_RoundTripsAuthoredCodeCompiledIrAndWritability()
        {
            var typeInfo = new PrimitiveTypeInfo
            {
                type = MemberKind.Int,
                required = true,
            };
            var source = new NSPropertyMember
            {
                id = "property-with-setter",
                projectId = "project",
                name = "Score",
                kind = MemberKind.NSProperty,
                isStatic = true,
                accessModifierKind = "public",
                code = "return root.Save.Score;",
                returnTypeInfo = typeInfo,
                getter = new FunctionWithReturnType
                {
                    parameters = System.Array.Empty<Variable>(),
                    instructions = System.Array.Empty<Instruction>(),
                    typeInfo = typeInfo,
                },
                setterCode = "root.Save.Score = value;",
                setter = new FunctionWithReturnType
                {
                    parameters = System.Array.Empty<Variable>(),
                    instructions = new Instruction[]
                    {
                        new AssignInstruction
                        {
                            type = InstructionKind.Assign,
                            target = new WriteTarget
                            {
                                pointer = new ReferencePointer
                                {
                                    type = PointerKind.Reference,
                                    valueId = "score-value",
                                },
                                typeInfo = typeInfo,
                                writability = WritabilityKind.Setter,
                            },
                            operatorValue = "=",
                            pointer = new VariablePointer
                            {
                                type = PointerKind.Variable,
                                variableId = "__value__",
                            },
                        },
                    },
                    typeInfo = new PrimitiveTypeInfo
                    {
                        type = MemberKind.Null,
                        required = true,
                    },
                },
                createdAt = "x",
                updatedAt = "x",
            };

            string json = JsonConvert.SerializeObject(source);
            var roundTripped = (NSPropertyMember)JsonConvert
                .DeserializeObject<Member>(json)!;

            Assert.AreEqual(source.setterCode, roundTripped.setterCode);
            Assert.IsTrue(roundTripped.isStatic);
            Assert.IsNotNull(roundTripped.setter);
            var assign = (AssignInstruction)roundTripped.setter!.instructions[0];
            Assert.AreEqual(WritabilityKind.Setter, assign.target.writability);
            Assert.AreEqual("__value__", ((VariablePointer)assign.pointer).variableId);
        }

        [Test]
        public void WriteTarget_RuntimeWritabilityAndSchemaEightVocabularyRoundTrip()
        {
            var source = new WriteTarget
            {
                pointer = new ReferencePointer
                {
                    type = PointerKind.Reference,
                    valueId = "runtime-value",
                },
                typeInfo = new PrimitiveTypeInfo
                {
                    type = MemberKind.Int,
                    required = true,
                },
                writability = WritabilityKind.Runtime,
            };

            var roundTripped = JsonConvert.DeserializeObject<WriteTarget>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual("runtime", roundTripped.writability);
            Assert.AreEqual("immutable", WritabilityKind.Immutable);
            Assert.AreEqual("immutableToSaveLookup", WritabilityKind.ImmutableToSaveLookup);
            Assert.AreEqual("immutableToSessionLookup", WritabilityKind.ImmutableToSessionLookup);
        }

        /// <summary>
        /// P43 §1 — a computed member default carries source plus compiled IR
        /// and no baked <c>value</c>.
        /// </summary>
        [Test]
        public void MemberDefault_InitBodyRoundTrips()
        {
            const string json = @"{
  ""id"": ""member-loud"",
  ""projectId"": ""project"",
  ""name"": ""Loud"",
  ""kind"": 3,
  ""locked"": false,
  ""required"": true,
  ""isStatic"": false,
  ""accessModifierKind"": ""public"",
  ""defaultValue"": {
    ""init"": {
      ""code"": ""StaticFunc(\""bar\"")"",
      ""compiled"": {
        ""compilerRevision"": 3,
        ""parameters"": [],
        ""instructions"": [],
        ""typeInfo"": { ""type"": 3, ""required"": true }
      }
    }
  },
  ""createdAt"": ""x"",
  ""updatedAt"": ""x""
}";

            var member = (StringMember)JsonConvert.DeserializeObject<Member>(json)!;

            Assert.IsNotNull(member.defaultValue!.init);
            Assert.AreEqual("StaticFunc(\"bar\")", member.defaultValue.init!.code);
            Assert.AreEqual(3, member.defaultValue.init.compiled!.compilerRevision);
            Assert.IsNull(member.defaultValue.value);
            Assert.IsNull(member.defaultValue.classId);
        }

        /// <summary>
        /// P43 §1.1a — a stored value ROW may carry an initializer too, which
        /// is what keeps a literal list's entries addressable while each entry
        /// computes its own interior.
        /// </summary>
        [Test]
        public void MemberValueRow_InitBodyRoundTrips()
        {
            const string json = @"{
  ""id"": ""value-eyes-left"",
  ""projectId"": ""project"",
  ""init"": { ""code"": ""new EyePart(IsRight: false)"" },
  ""createdAt"": ""x"",
  ""updatedAt"": ""x""
}";

            var row = JsonConvert.DeserializeObject<MemberValue>(json)!;

            Assert.AreEqual("value-eyes-left", row.id);
            Assert.AreEqual("new EyePart(IsRight: false)", row.init!.code);
            Assert.IsNull(row.init.compiled);
        }

        [Test]
        public void MemberValueRow_CarryingBothValueAndInitIsRejected()
        {
            const string json = @"{
  ""id"": ""value-conflict"",
  ""projectId"": ""project"",
  ""value"": ""literal"",
  ""init"": { ""code"": ""Compute()"" },
  ""createdAt"": ""x"",
  ""updatedAt"": ""x""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<MemberValue>(json));

            Assert.That(
                error!.Message,
                Does.Contain("carries both 'value' and 'init'"));
        }

        [Test]
        public void MemberValueRow_CarryingBothClassIdAndInitIsRejected()
        {
            const string json = @"{
  ""id"": ""value-conflict"",
  ""projectId"": ""project"",
  ""classId"": ""class-foo"",
  ""init"": { ""code"": ""Compute()"" },
  ""createdAt"": ""x"",
  ""updatedAt"": ""x""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<MemberValue>(json));

            Assert.That(
                error!.Message,
                Does.Contain("carries both 'classId' and 'init'"));
        }

        /// <summary>
        /// P43 §6.2 — the hydrated constructor record, and §6.3's ordered
        /// <c>constructorIds</c> on the class that owns it.
        /// </summary>
        [Test]
        public void ConstructorRecord_AndClassConstructorIdsRoundTrip()
        {
            const string json = @"{
  ""metadata"": { ""schemaVersion"": 15, ""projectId"": ""project"", ""versionId"": ""v"" },
  ""project"": { ""id"": ""project"", ""name"": ""P"" },
  ""members"": {},
  ""values"": {},
  ""enums"": {},
  ""classes"": {
    ""class-foo"": {
      ""id"": ""class-foo"",
      ""projectId"": ""project"",
      ""name"": ""Foo"",
      ""schema"": {},
      ""hiddenInMemberSelector"": false,
      ""isAbstract"": false,
      ""constructorIds"": [""ctor-foo"", ""ctor-foo-loud""],
      ""createdAt"": ""x"",
      ""updatedAt"": ""x""
    }
  },
  ""constructors"": {
    ""ctor-foo"": {
      ""id"": ""ctor-foo"",
      ""projectId"": ""project"",
      ""classId"": ""class-foo"",
      ""argumentTypes"": [{ ""name"": ""AllCaps"", ""type"": 1, ""required"": true }],
      ""code"": ""\t\tif (AllCaps) {\n\t\t\tthis.Bar = \""BAR\"";\n\t\t}"",
      ""action"": {
        ""compilerRevision"": 3,
        ""parameters"": [],
        ""instructions"": [],
        ""typeInfo"": { ""type"": 0, ""required"": true }
      },
      ""baseArguments"": [{ ""name"": ""Seed"", ""code"": ""AllCaps"" }],
      ""compiledBaseArguments"": [{
        ""compilerRevision"": 3,
        ""parameters"": [],
        ""instructions"": [],
        ""typeInfo"": { ""type"": 1, ""required"": true }
      }],
      ""createdAt"": ""x"",
      ""updatedAt"": ""x""
    }
  }
}";

            var data = Deserialize(json);

            Assert.That(
                data.classes["class-foo"].constructorIds,
                Is.EqualTo(new[] { "ctor-foo", "ctor-foo-loud" }));
            ConstructorRecord record = data.constructors["ctor-foo"];
            Assert.AreEqual("class-foo", record.classId);
            Assert.AreEqual("AllCaps", record.argumentTypes[0].name);
            Assert.AreEqual(MemberKind.Bool, record.argumentTypes[0].type);
            Assert.AreEqual(MemberKind.Null, record.action.typeInfo.type);
            Assert.IsTrue(record.action.typeInfo.required);
            Assert.AreEqual("Seed", record.baseArguments![0].name);
            Assert.AreEqual("AllCaps", record.baseArguments[0].code);
            Assert.AreEqual(1, record.compiledBaseArguments!.Length);
        }

        /// <summary>
        /// P49 §1.1/§1.5 — a required constructor is reached through its own
        /// class field rather than <c>constructorIds</c>, and a base clause may
        /// carry an initializer block beside its arguments.
        /// </summary>
        [Test]
        public void RequiredConstructorId_AndBaseInitializerFieldsRoundTrip()
        {
            const string json = @"{
  ""metadata"": { ""schemaVersion"": 15, ""projectId"": ""project"", ""versionId"": ""v"" },
  ""project"": { ""id"": ""project"", ""name"": ""P"" },
  ""members"": {},
  ""values"": {},
  ""enums"": {},
  ""classes"": {
    ""class-bar"": {
      ""id"": ""class-bar"",
      ""projectId"": ""project"",
      ""name"": ""Bar"",
      ""schema"": {},
      ""hiddenInMemberSelector"": false,
      ""isAbstract"": false,
      ""extendsClassId"": ""class-foo"",
      ""requiredConstructorId"": ""ctor-bar"",
      ""createdAt"": ""x"",
      ""updatedAt"": ""x""
    }
  },
  ""constructors"": {
    ""ctor-bar"": {
      ""id"": ""ctor-bar"",
      ""projectId"": ""project"",
      ""classId"": ""class-bar"",
      ""argumentTypes"": [{ ""name"": ""bar"", ""type"": 3, ""required"": true }],
      ""code"": """",
      ""action"": {
        ""compilerRevision"": 3,
        ""parameters"": [],
        ""instructions"": [],
        ""typeInfo"": { ""type"": 0, ""required"": true }
      },
      ""baseInitializerFields"": [{ ""name"": ""Bar"", ""code"": ""bar"" }],
      ""compiledBaseInitializerFields"": [{
        ""compilerRevision"": 3,
        ""parameters"": [],
        ""instructions"": [],
        ""typeInfo"": { ""type"": 3, ""required"": true }
      }],
      ""createdAt"": ""x"",
      ""updatedAt"": ""x""
    }
  }
}";

            var data = Deserialize(json);

            Assert.AreEqual(
                "ctor-bar",
                data.classes["class-bar"].requiredConstructorId);
            Assert.IsNull(data.classes["class-bar"].constructorIds);
            ConstructorRecord record = data.constructors["ctor-bar"];
            Assert.AreEqual("Bar", record.baseInitializerFields![0].name);
            Assert.AreEqual("bar", record.baseInitializerFields[0].code);
            Assert.AreEqual(1, record.compiledBaseInitializerFields!.Length);
            Assert.IsNull(record.baseArguments);
        }

        /// <summary>
        /// P43 §6.1 — the <c>declaredConstructor</c> IR variant, which is
        /// distinct from the schema-derived <c>classConstructor</c>.
        /// </summary>
        [Test]
        public void DeclaredConstructorFunction_RoundTrips()
        {
            const string json = @"{
  ""type"": ""declaredConstructor"",
  ""info"": {
    ""schemaClassInfo"": { ""type"": 7, ""required"": true, ""classId"": ""class-foo"" },
    ""constructorId"": ""ctor-foo"",
    ""args"": [{
      ""name"": ""AllCaps"",
      ""valuePointer"": {
        ""type"": ""value"",
        ""value"": { ""typeInfo"": { ""type"": 1, ""required"": true }, ""value"": true }
      }
    }],
    ""fields"": [{
      ""schemaKey"": ""Bar"",
      ""memberId"": ""member-foo-bar"",
      ""valuePointer"": {
        ""type"": ""value"",
        ""value"": { ""typeInfo"": { ""type"": 3, ""required"": true }, ""value"": ""custom"" }
      }
    }]
  }
}";

            var declared = (DeclaredConstructorFunction)
                JsonConvert.DeserializeObject<Function>(json)!;

            Assert.AreEqual(FunctionKind.DeclaredConstructor, declared.type);
            Assert.AreEqual("ctor-foo", declared.info.constructorId);
            Assert.AreEqual("class-foo", declared.info.schemaClassInfo.classId);
            Assert.AreEqual("AllCaps", declared.info.args[0].name);
            Assert.IsInstanceOf<ValuePointer>(declared.info.args[0].valuePointer);
            Assert.AreEqual("Bar", declared.info.fields[0].schemaKey);
        }

        /// <summary>
        /// P43 §6.1.2 — the implicit <c>new()</c> a class keeps even after
        /// declaring constructors carries a null constructor id.
        /// </summary>
        [Test]
        public void DeclaredConstructorFunction_NullConstructorIdRoundTrips()
        {
            const string json = @"{
  ""type"": ""declaredConstructor"",
  ""info"": {
    ""schemaClassInfo"": { ""type"": 7, ""required"": true, ""classId"": ""class-foo"" },
    ""constructorId"": null,
    ""args"": [],
    ""fields"": []
  }
}";

            var declared = (DeclaredConstructorFunction)
                JsonConvert.DeserializeObject<Function>(json)!;

            Assert.IsNull(declared.info.constructorId);
            Assert.AreEqual(0, declared.info.args.Length);
        }

        [Test]
        public void CompilerRevision_ThreeIsTheCurrentCeiling()
        {
            Assert.AreEqual(3, FunctionWithReturnType.CurrentCompilerRevision);
        }

        [Test]
        public void Member_MissingIsStaticIsRejected()
        {
            var source = new IntMember
            {
                id = "member-missing-static",
                projectId = "project",
                name = "Count",
                kind = MemberKind.Int,
                accessModifierKind = "public",
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json.Remove("isStatic");

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain("Missing required field 'isStatic' on IntMember."));
        }

        [Test]
        public void Member_OldTypeDiscriminatorIsRejectedWithoutAlias()
        {
            const string json = @"{
  ""id"": ""member-count"",
  ""projectId"": ""project"",
  ""name"": ""Count"",
  ""type"": 2,
  ""isStatic"": false, ""accessModifierKind"": ""public"",
  ""createdAt"": ""1970-01-01T00:00:00.000Z"",
  ""updatedAt"": ""1970-01-01T00:00:00.000Z""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'type'; schema 8 requires 'kind'"));
        }

        [Test]
        public void MemberValue_OldTypeIdIsRejectedWithoutAlias()
        {
            const string json = @"{
  ""id"": ""value-profile"",
  ""projectId"": ""project"",
  ""value"": {},
  ""typeId"": ""class-profile"",
  ""createdAt"": ""1970-01-01T00:00:00.000Z"",
  ""updatedAt"": ""1970-01-01T00:00:00.000Z""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<MemberValue>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'typeId'; schema 8 requires 'classId'"));
        }

        [Test]
        public void Member_OldCustomTypeIdIsRejectedWithoutAlias()
        {
            const string json = @"{
  ""id"": ""member-profile"",
  ""projectId"": ""project"",
  ""name"": ""Profile"",
  ""kind"": 7,
  ""customTypeId"": ""class-profile"",
  ""isStatic"": false, ""accessModifierKind"": ""public"",
  ""createdAt"": ""1970-01-01T00:00:00.000Z"",
  ""updatedAt"": ""1970-01-01T00:00:00.000Z""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'customTypeId'; schema 8 requires 'classId'"));
        }

        [Test]
        public void TypeInfo_OldTypeIdIsRejectedWithoutAlias()
        {
            const string json = @"{
  ""type"": 7,
  ""required"": true,
  ""typeId"": ""class-profile""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<TypeInfo>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'typeId'; schema 8 requires 'classId'"));
        }

        [Test]
        public void GenericBinding_OldAttributeIdIsRejectedWithoutAlias()
        {
            const string json = @"{
  ""kind"": ""member"",
  ""attributeId"": ""member-entry""
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<GenericBinding>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'attributeId'; schema 8 requires 'memberId'"));
        }

        [Test]
        public void ProjectData_OldMemberTypeIsRejectedEvenWhenKindIsPresent()
        {
            const string json = @"{
  ""project"": {},
  ""members"": {
    ""member-count"": {
      ""id"": ""member-count"",
      ""projectId"": ""project"",
      ""name"": ""Count"",
      ""kind"": 2,
      ""type"": 2,
      ""isStatic"": false, ""accessModifierKind"": ""public""
    }
  },
  ""values"": {},
  ""classes"": {},
  ""enums"": {}
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<ProjectData>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'type'; schema 8 requires 'kind'"));
        }

        [TestCase("extendsTypeId", "extendsClassId")]
        [TestCase("ownerTypeId", "ownerClassId")]
        [TestCase("receiverTypeId", "receiverClassId")]
        [TestCase("analyzerRootTypeId", "analyzerRootClassId")]
        [TestCase("schemaClassId", "classId")]
        [TestCase("entryAttributeId", "entryMemberId")]
        [TestCase("collectionAttributeId", "collectionMemberId")]
        [TestCase("ownerAttributeId", "ownerMemberId")]
        [TestCase("valueAttributeId", "valueMemberId")]
        [TestCase("attributeType", "memberKind")]
        public void ProjectData_NestedOldReferenceFieldIsRejected(
            string removedField,
            string replacementField)
        {
            var json = JObject.Parse(@"{
  ""project"": {},
  ""members"": {},
  ""values"": {},
  ""classes"": {
    ""class-profile"": {
      ""id"": ""class-profile"",
      ""projectId"": ""project"",
      ""name"": ""Profile"",
      ""schema"": {}
    }
  },
  ""enums"": {}
}");
            json["classes"]!["class-profile"]![removedField] = "legacy-id";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<ProjectData>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain(
                    $"removed field '{removedField}'; schema 8 requires '{replacementField}'"));
        }

        [Test]
        public void ProjectData_OldTopLevelCollectionsAreRejectedWithoutAlias()
        {
            const string json = @"{
  ""project"": {},
  ""attributes"": {},
  ""values"": {},
  ""classes"": {},
  ""enums"": {}
}";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<ProjectData>(json));

            Assert.That(
                error!.Message,
                Does.Contain("removed field 'attributes'; schema 8 requires 'members'"));
        }

        [Test]
        public void ProjectData_UserValueKeysThatMatchOldFieldsRemainOpaque()
        {
            const string json = @"{
  ""project"": {},
  ""members"": {},
  ""values"": {
    ""value-profile"": {
      ""id"": ""value-profile"",
      ""projectId"": ""project"",
      ""value"": {
        ""attributeId"": ""authored dictionary key"",
        ""typeId"": ""another authored dictionary key""
      },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""classes"": {},
  ""enums"": {},
  ""futureExportField"": true
}";

            var projectData = JsonConvert.DeserializeObject<ProjectData>(json)!;
            var value = (ObjectMemberValue)projectData.values["value-profile"];

            Assert.AreEqual(
                "authored dictionary key",
                value.value!["attributeId"]);
            Assert.AreEqual(
                "another authored dictionary key",
                value.value["typeId"]);
        }

        [Test]
        public void ProjectData_AuthoredSchemaKeysThatMatchOldFieldsRemainKeys()
        {
            const string json = @"{
  ""project"": {},
  ""members"": {},
  ""values"": {},
  ""classes"": {
    ""class-profile"": {
      ""id"": ""class-profile"",
      ""projectId"": ""project"",
      ""name"": ""Profile"",
      ""schema"": {
        ""attributeId"": ""member-attribute-id"",
        ""customTypeId"": ""member-custom-type-id""
      }
    }
  },
  ""enums"": {},
  ""futureExportObject"": {
    ""attributeId"": ""unrelated future field""
  }
}";

            var projectData = JsonConvert.DeserializeObject<ProjectData>(json)!;

            Assert.AreEqual(
                "member-attribute-id",
                projectData.classes["class-profile"].schema["attributeId"]);
            Assert.AreEqual(
                "member-custom-type-id",
                projectData.classes["class-profile"].schema["customTypeId"]);
        }

        [Test]
        public void Member_NonBooleanIsStaticIsRejected()
        {
            var source = new IntMember
            {
                id = "invalid-member",
                projectId = "project",
                name = "Count",
                kind = MemberKind.Int,
                accessModifierKind = "public",
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json["isStatic"] = "false";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain("Field 'isStatic' on IntMember must be a boolean."));
        }

        [Test]
        public void Member_MissingAccessModifierKindIsRejected()
        {
            var source = new IntMember
            {
                id = "member-missing-access",
                projectId = "project",
                name = "Count",
                kind = MemberKind.Int,
                accessModifierKind = "public",
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json.Remove("accessModifierKind");

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain(
                    "Missing required field 'accessModifierKind' on IntMember."));
        }

        [Test]
        public void Member_NonStringAccessModifierKindIsRejected()
        {
            var source = new IntMember
            {
                id = "member-non-string-access",
                projectId = "project",
                name = "Count",
                kind = MemberKind.Int,
                accessModifierKind = "public",
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json["accessModifierKind"] = true;

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain(
                    "Field 'accessModifierKind' on IntMember must be a string."));
        }

        [Test]
        public void Member_UnknownAccessModifierKindIsRejected()
        {
            var source = new IntMember
            {
                id = "member-unknown-access",
                projectId = "project",
                name = "Count",
                kind = MemberKind.Int,
                accessModifierKind = "public",
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json["accessModifierKind"] = "internal";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Member>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain(
                    "Field 'accessModifierKind' on IntMember has unknown value 'internal'"));
        }

        [Test]
        public void Member_AccessModifierKindRoundTripsAllLiterals()
        {
            foreach (string literal in new[] { "public", "protected", "private" })
            {
                var source = new IntMember
                {
                    id = $"member-access-{literal}",
                    projectId = "project",
                    name = "Count",
                    kind = MemberKind.Int,
                    accessModifierKind = literal,
                    createdAt = "x",
                    updatedAt = "x",
                };

                var roundTripped = JsonConvert.DeserializeObject<Member>(
                    JsonConvert.SerializeObject(source))!;

                Assert.AreEqual(literal, roundTripped.accessModifierKind);
            }
        }

        [Test]
        public void InterfaceMember_MissingAccessModifierKindIsRejected()
        {
            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""property"",
  ""typeInfo"": { ""type"": 2, ""required"": true },
  ""settable"": false
}"));

            Assert.That(
                error!.Message,
                Does.Contain(
                    "Interface member is missing required field 'accessModifierKind'."));
        }

        [Test]
        public void InterfaceMember_UnknownAccessModifierKindIsRejected()
        {
            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""property"",
  ""accessModifierKind"": ""internal"",
  ""typeInfo"": { ""type"": 2, ""required"": true },
  ""settable"": false
}"));

            Assert.That(
                error!.Message,
                Does.Contain(
                    "Interface member field 'accessModifierKind' has unknown value 'internal'"));
        }

        [Test]
        public void TypeInfo_GenericAndConstructedClassArgumentsRoundTrip()
        {
            var source = new ClassTypeInfo
            {
                type = MemberKind.Class,
                required = true,
                classId = "class-box",
                typeArguments = new Dictionary<string, TypeInfo>
                {
                    ["param-t"] = new GenericTypeInfo
                    {
                        type = MemberKind.Generic,
                        required = true,
                        ownerClassId = "class-owner",
                        genericParamId = "param-t",
                    },
                },
            };

            var roundTripped = (ClassTypeInfo)JsonConvert.DeserializeObject<TypeInfo>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual("class-box", roundTripped.classId);
            Assert.IsNotNull(roundTripped.typeArguments);
            var generic = (GenericTypeInfo)roundTripped.typeArguments!["param-t"];
            Assert.AreEqual("class-owner", generic.ownerClassId);
            Assert.AreEqual("param-t", generic.genericParamId);
        }

        [Test]
        public void TypeInfo_InterfaceRoundTripsReferencedId()
        {
            var source = new InterfaceTypeInfo
            {
                type = MemberKind.Interface,
                required = true,
                interfaceId = "interface-entity",
            };

            var roundTripped = (InterfaceTypeInfo)JsonConvert.DeserializeObject<TypeInfo>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual(MemberKind.Interface, roundTripped.type);
            Assert.IsTrue(roundTripped.required);
            Assert.AreEqual("interface-entity", roundTripped.interfaceId);
        }

        [Test]
        public void InterfaceExport_RoundTripsMembersTypeInfoAndImplementsList()
        {
            Assert.AreEqual(22, (int)MemberKind.Interface);

            var source = new ProjectData
            {
                interfaces = new Dictionary<string, Interface>
                {
                    ["interface-damageable"] = new Interface
                    {
                        id = "interface-damageable",
                        projectId = "project",
                        name = "IDamageable",
                        members = new Dictionary<string, InterfaceMember>
                        {
                            ["Health"] = new InterfaceMember
                            {
                                kind = "property",
                                accessModifierKind = "public",
                                typeInfo = new PrimitiveTypeInfo
                                {
                                    type = MemberKind.Int,
                                    required = true,
                                },
                                settable = true,
                            },
                            ["FindTarget"] = new InterfaceMember
                            {
                                kind = "function",
                                accessModifierKind = "public",
                                returnTypeInfo = new InterfaceTypeInfo
                                {
                                    type = MemberKind.Interface,
                                    required = false,
                                    interfaceId = "interface-damageable",
                                },
                                argumentTypes = new List<FunctionArgumentTypeInfo>
                                {
                                    new FunctionArgumentTypeInfo
                                    {
                                        name = "candidate",
                                        type = MemberKind.Interface,
                                        required = true,
                                        interfaceId = "interface-damageable",
                                    },
                                },
                                deferred = true,
                            },
                        },
                        memberKeyOrder = new List<string> { "Health", "FindTarget" },
                        extendsInterfaceIds = new List<string> { "interface-entity" },
                        createdAt = 1000d,
                        updatedAt = 2000d,
                    },
                },
                classes = new Dictionary<string, NeoSchemaClass>
                {
                    ["class-enemy"] = new NeoSchemaClass
                    {
                        id = "class-enemy",
                        projectId = "project",
                        name = "Enemy",
                        schema = new Dictionary<string, string>(),
                        implementsInterfaceIds = new List<string> { "interface-damageable" },
                    },
                },
            };

            var json = JsonConvert.SerializeObject(source);
            var roundTripped = JsonConvert.DeserializeObject<ProjectData>(json)!;

            var declaration = roundTripped.interfaces["interface-damageable"];
            CollectionAssert.AreEqual(
                new[] { "Health", "FindTarget" },
                declaration.memberKeyOrder);
            CollectionAssert.AreEqual(
                new[] { "interface-entity" },
                declaration.extendsInterfaceIds);
            Assert.AreEqual(true, declaration.members["Health"].settable);

            var function = declaration.members["FindTarget"];
            Assert.AreEqual(true, function.deferred);
            var returnType = (InterfaceTypeInfo)function.returnTypeInfo!;
            Assert.AreEqual("interface-damageable", returnType.interfaceId);
            Assert.AreEqual(
                "interface-damageable",
                function.argumentTypes![0].interfaceId);
            CollectionAssert.AreEqual(
                new[] { "interface-damageable" },
                roundTripped.classes["class-enemy"].implementsInterfaceIds);
        }

        [Test]
        public void MissingInterfacesMap_DeserializesToEmptyDictionary()
        {
            var export = Deserialize(@"{
  ""project"": {},
  ""members"": {},
  ""values"": {},
  ""classes"": {},
  ""enums"": {}
}");

            Assert.IsNotNull(export.interfaces);
            Assert.AreEqual(0, export.interfaces.Count);
        }

        [Test]
        public void InterfaceMember_RejectsIncompleteAndUnsupportedSignatures()
        {
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""function"",
  ""accessModifierKind"": ""public"",
  ""returnTypeInfo"": { ""type"": 2, ""required"": true },
  ""argumentTypes"": []
}"));

            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""function"",
  ""accessModifierKind"": ""public"",
  ""returnTypeInfo"": { ""type"": 2, ""required"": true },
  ""argumentTypes"": [
    {
      ""name"": ""value"",
      ""type"": 21,
      ""required"": true,
      ""ownerClassId"": ""class-owner"",
      ""genericParamId"": ""param-t""
    }
  ],
  ""deferred"": false
}"));
        }

        [Test]
        public void CallFunctionPointer_RequiresOneTargetAndCallSiteId()
        {
            var concrete = (CallFunctionPointer)JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""memberId"": ""member-function"",
  ""callSiteId"": ""call-1"",
  ""receiver"": { ""kind"": ""instance"", ""pointer"": { ""type"": ""reference"", ""valueId"": ""value"" } },
  ""args"": []
}")!;
            Assert.AreEqual("member-function", concrete.memberId);
            Assert.IsNull(concrete.memberKey);

            var dynamicMember = (CallFunctionPointer)JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""memberKey"": ""TakeDamage"",
  ""callSiteId"": ""call-2"",
  ""receiver"": { ""kind"": ""instance"", ""pointer"": { ""type"": ""reference"", ""valueId"": ""value"" } },
  ""args"": []
}")!;
            Assert.IsNull(dynamicMember.memberId);
            Assert.AreEqual("TakeDamage", dynamicMember.memberKey);

            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""memberId"": ""member-function"",
  ""memberKey"": ""TakeDamage"",
  ""callSiteId"": ""call-3"",
  ""receiver"": { ""kind"": ""instance"", ""pointer"": { ""type"": ""reference"", ""valueId"": ""value"" } },
  ""args"": []
}"));
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<CallFunctionPointer>(@"{
  ""type"": ""callFunction"",
  ""callSiteId"": ""call-4"",
  ""receiver"": { ""kind"": ""instance"", ""pointer"": { ""type"": ""reference"", ""valueId"": ""value"" } },
  ""args"": []
}"));
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<CallFunctionPointer>(@"{
  ""type"": ""callFunction"",
  ""memberId"": ""member-function"",
  ""receiver"": { ""kind"": ""instance"", ""pointer"": { ""type"": ""reference"", ""valueId"": ""value"" } },
  ""args"": []
}"));
        }

        // --------------------------------------------------------------
        // Synthesized fixture — exercises every IR variant.
        // --------------------------------------------------------------

        [Test]
        public void SynthFixture_DeserializesIntoProjectExport()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));

            Assert.IsNotNull(export);
            Assert.IsNotNull(export.project);
            Assert.IsNotNull(export.members);
            Assert.IsNotNull(export.values);
            Assert.IsNotNull(export.classes);
            Assert.IsNotNull(export.enums);
            Assert.IsNotNull(export.dialogues);
            Assert.IsNotNull(export.dialogueGroups);
            Assert.IsNotNull(export.priorityGroups);
            Assert.Greater(export.members.Count, 0);
        }

        [Test]
        public void SynthFixture_TimestampsRoundTripAsEpochNumbers()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));

            Assert.AreEqual(0d, export.project.createdAt.EpochMilliseconds);
            Assert.AreEqual(0d, export.members["member-name"].updatedAt.EpochMilliseconds);
            Assert.AreEqual(0d, export.values["v-num"].createdAt.EpochMilliseconds);

            var serialized = JObject.Parse(JsonConvert.SerializeObject(export.project));
            Assert.AreNotEqual(JTokenType.String, serialized["createdAt"]!.Type);
            Assert.AreEqual(0d, serialized["createdAt"]!.Value<double>());
        }

        [Test]
        public void MissingDialogueMaps_DeserializeToEmptyDictionaries()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Older Export"",
    ""rootAssetsMemberId"": ""assets-root"",
    ""rootSaveFileMemberId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""members"": {},
  ""values"": {},
  ""classes"": {},
  ""enums"": {}
}";
            var export = Deserialize(json);
            Assert.IsNotNull(export.dialogues);
            Assert.IsNotNull(export.dialogueGroups);
            Assert.IsNotNull(export.priorityGroups);
            Assert.IsNotNull(export.files);
            Assert.IsNotNull(export.textureTemplates);
            Assert.IsNotNull(export.audioClipTemplates);
            Assert.IsNull(export.tileGridContents);
            Assert.AreEqual(0, export.dialogues.Count);
            Assert.AreEqual(0, export.dialogueGroups.Count);
            Assert.AreEqual(0, export.priorityGroups.Count);
            Assert.AreEqual(0, export.files.Count);
            Assert.AreEqual(0, export.textureTemplates.Count);
            Assert.AreEqual(0, export.audioClipTemplates.Count);
        }

        [Test]
        public void LegacyTileGridContents_ParseIntoTheGuardTokenForLoudRejection()
        {
            // Exports at schema version 3+ never carry tileGridContents; the
            // field survives only as a legacy detector so NeoClient can throw
            // a pinpointed error instead of silently dropping tile data.
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Legacy Export"",
    ""rootAssetsMemberId"": ""assets-root"",
    ""rootSaveFileMemberId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""members"": {},
  ""values"": {},
  ""classes"": {},
  ""enums"": {},
  ""tileGridContents"": {
    ""town-grid"": { ""schemaVersion"": 1, ""regions"": [] }
  }
}";

            var export = Deserialize(json);

            Assert.IsNotNull(export.tileGridContents);
            Assert.AreEqual(1, export.tileGridContents!.Count);
            Assert.IsNotNull(export.tileGridContents["town-grid"]);
        }

        [Test]
        public void VersionedExport_DeserializesRecordsWithoutMongoIds()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Versioned Export"",
    ""rootAssetsMemberId"": ""assets-root"",
    ""rootSaveFileMemberId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""members"": {
    ""member-a"": {
      ""id"": ""member-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Title"",
      ""kind"": 4,
      ""locked"": false,
      ""required"": true,
      ""isStatic"": false, ""accessModifierKind"": ""public"",
      ""valueId"": ""value-a"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""values"": {
    ""value-a"": {
      ""id"": ""value-a"",
      ""value"": ""Hello"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""classes"": {},
  ""enums"": {},
  ""files"": {}
}";

            var export = Deserialize(json);

            Assert.IsNotNull(export.members["member-a"]);
            Assert.IsNotNull(export.values["value-a"]);
        }

        [Test]
        public void FileMemberExport_DeserializesFileMetadataTemplatesAndValues()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Files"",
    ""rootAssetsMemberId"": ""assets-root"",
    ""rootSaveFileMemberId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""members"": {
    ""sprite-member"": {
      ""_id"": ""sprite-member"",
      ""id"": ""sprite-member"",
      ""projectId"": ""project-a"",
      ""name"": ""Portrait"",
      ""kind"": 11,
      ""locked"": false,
      ""required"": true,
      ""isStatic"": false, ""accessModifierKind"": ""public"",
      ""templateId"": ""texture-template-1"",
      ""valueId"": ""sprite-value"",
      ""defaultValue"": { ""value"": { ""fileId"": ""file-1"", ""sliceIndex"": 2 } },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    },
    ""audio-member"": {
      ""_id"": ""audio-member"",
      ""id"": ""audio-member"",
      ""projectId"": ""project-a"",
      ""name"": ""Voice"",
      ""kind"": 12,
      ""locked"": false,
      ""required"": false,
      ""isStatic"": false, ""accessModifierKind"": ""public"",
      ""templateId"": ""audio-template-1"",
      ""valueId"": ""audio-value"",
      ""defaultValue"": { ""value"": { ""fileId"": ""file-2"" } },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""values"": {
    ""sprite-value"": {
      ""_id"": ""sprite-value"",
      ""id"": ""sprite-value"",
      ""value"": { ""fileId"": ""file-1"", ""sliceIndex"": 2 },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    },
    ""audio-value"": {
      ""_id"": ""audio-value"",
      ""id"": ""audio-value"",
      ""value"": { ""fileId"": ""file-2"" },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""classes"": {},
  ""enums"": {},
  ""files"": {
    ""file-1"": {
      ""_id"": ""file-1"",
      ""id"": ""file-1"",
      ""projectId"": ""project-a"",
      ""status"": ""uploaded"",
      ""name"": ""portrait.png"",
      ""fileType"": ""image"",
      ""mimeType"": ""image/png"",
      ""byteLength"": 3,
      ""storageKey"": ""projects/project-a/files/file-1"",
      ""storageETag"": ""etag-1"",
      ""unityTextureSettings"": { ""templateId"": ""texture-template-1"", ""type"": ""texture-2d"", ""overridePaths"": [], ""values"": {} },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-02T00:00:00.000Z""
    },
    ""file-2"": {
      ""_id"": ""file-2"",
      ""id"": ""file-2"",
      ""projectId"": ""project-a"",
      ""status"": ""uploaded"",
      ""name"": ""voice.wav"",
      ""fileType"": ""audio"",
      ""mimeType"": ""audio/wav"",
      ""byteLength"": 4,
      ""storageKey"": ""projects/project-a/files/file-2"",
      ""storageETag"": ""etag-2"",
      ""audioDurationSeconds"": 1.25,
      ""unityAudioClipSettings"": { ""templateId"": ""audio-template-1"", ""overridePaths"": [], ""values"": {} },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-02T00:00:00.000Z""
    }
  },
  ""textureTemplates"": {
    ""texture-template-1"": {
      ""_id"": ""texture-template-1"",
      ""id"": ""texture-template-1"",
      ""projectId"": ""project-a"",
      ""name"": ""Sprites"",
      ""type"": ""texture-2d"",
      ""textureType"": ""sprite"",
      ""textureShape"": ""2d"",
      ""sRGBTexture"": true,
      ""alphaSource"": ""input-texture-alpha"",
      ""alphaIsTransparency"": true,
      ""nonPowerOfTwoScale"": ""none"",
      ""ignorePngGamma"": false,
      ""readWriteEnabled"": false,
      ""virtualTextureOnly"": false,
      ""generateMipMaps"": false,
      ""borderMipMaps"": false,
      ""mipMapFiltering"": ""box"",
      ""mipMapsPreserveCoverage"": false,
      ""alphaCutoffValue"": 0.5,
      ""fadeOutMipMaps"": false,
      ""mipMapFadeDistanceStart"": 1,
      ""mipMapFadeDistanceEnd"": 3,
      ""anisoLevel"": 1,
      ""wrapMode"": ""clamp"",
      ""filterMode"": ""point"",
      ""maxTextureSize"": 2048,
      ""resizeAlgorithm"": ""mitchell"",
      ""textureCompression"": ""none"",
      ""compressionQuality"": 50,
      ""crunchedCompression"": false,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-03T00:00:00.000Z""
    }
  },
  ""audioClipTemplates"": {
    ""audio-template-1"": {
      ""_id"": ""audio-template-1"",
      ""id"": ""audio-template-1"",
      ""projectId"": ""project-a"",
      ""name"": ""Voice"",
      ""forceToMono"": false,
      ""normalize"": true,
      ""loadInBackground"": false,
      ""ambisonic"": false,
      ""loadType"": ""decompress-on-load"",
      ""compressionFormat"": ""vorbis"",
      ""quality"": 0.7,
      ""sampleRateSetting"": ""preserve-sample-rate"",
      ""preloadAudioData"": true,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-04T00:00:00.000Z""
    }
  }
}";
            var export = Deserialize(json);

            var spriteMember = (SpriteMember)export.members["sprite-member"];
            var spriteDefault = (SpriteMemberValueBase)spriteMember.defaultValue!;
            Assert.AreEqual(MemberKind.Sprite, spriteMember.kind);
            Assert.AreEqual("texture-template-1", spriteMember.templateId);
            Assert.AreEqual("file-1", spriteDefault.value!.fileId);
            Assert.AreEqual(2, spriteDefault.value.sliceIndex);
            Assert.IsInstanceOf<SpriteMemberValue>(export.values["sprite-value"]);

            var audioMember = (AudioMember)export.members["audio-member"];
            var audioDefault = (FileMemberValueBase)audioMember.defaultValue!;
            Assert.AreEqual(MemberKind.Audio, audioMember.kind);
            Assert.AreEqual("audio-template-1", audioMember.templateId);
            Assert.AreEqual("file-2", audioDefault.value!.fileId);
            Assert.IsInstanceOf<FileMemberValue>(export.values["audio-value"]);

            Assert.AreEqual("portrait.png", export.files["file-1"].name);
            Assert.AreEqual("texture-template-1", export.files["file-1"].unityTextureSettings!.templateId);
            Assert.AreEqual("Sprites", export.textureTemplates["texture-template-1"].name);
            Assert.AreEqual("Voice", export.audioClipTemplates["audio-template-1"].name);
        }

        [Test]
        public void DialogueMaps_DeserializeDialogueGroupPriorityAndActionShapes()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Dialogue Project"",
    ""rootAssetsMemberId"": ""assets-root"",
    ""rootSaveFileMemberId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""members"": {},
  ""enums"": {},
  ""classes"": {},
  ""values"": {},
  ""dialogues"": {
    ""dialogue-a"": {
      ""_id"": ""dialogue-a"",
      ""id"": ""dialogue-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Hello"",
      ""description"": null,
      ""nodes"": {
        ""text-a"": {
          ""id"": ""text-a"",
          ""type"": 1,
          ""layout"": { ""x"": 0, ""y"": 0, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""text"": ""Hello there"",
          ""optionSettings"": {
            ""saveChoice"": true,
            ""options"": [
              {
                ""id"": ""option-a"",
                ""text"": ""Continue"",
                ""toNodeId"": ""actions-a"",
                ""settings"": {
                  ""conditions"": [],
                  ""selectableConditions"": []
                }
              }
            ]
          }
        },
        ""actions-a"": {
          ""id"": ""actions-a"",
          ""type"": 2,
          ""layout"": { ""x"": 0, ""y"": 140, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""actions"": [
            {
              ""id"": ""action-a"",
              ""type"": 0,
              ""logic"": {
                ""type"": 1,
                ""code"": ""Save.Score += 1;"",
                ""action"": {
                  ""parameters"": [],
                  ""typeInfo"": { ""type"": 0, ""required"": true },
                  ""instructions"": [
                    {
                      ""type"": ""assign"",
                      ""target"": {
                        ""pointer"": { ""type"": ""reference"", ""valueId"": ""score-value"" },
                        ""typeInfo"": { ""type"": 2, ""required"": true },
                        ""writability"": ""save""
                      },
                      ""operator"": ""+="",
                      ""pointer"": {
                        ""type"": ""value"",
                        ""value"": {
                          ""typeInfo"": { ""type"": 2, ""required"": true },
                          ""value"": 1
                        }
                      }
                    },
                    {
                      ""type"": ""collectionCall"",
                      ""target"": {
                        ""pointer"": { ""type"": ""reference"", ""valueId"": ""visited-value"" },
                        ""typeInfo"": {
                          ""type"": 8,
                          ""required"": true,
                          ""entryTypeInfo"": { ""type"": 4, ""required"": true }
                        },
                        ""writability"": ""save""
                      },
                      ""mutation"": ""Add"",
                      ""args"": [
                        {
                          ""type"": ""value"",
                          ""value"": {
                            ""typeInfo"": { ""type"": 4, ""required"": true },
                            ""value"": ""Earth""
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          ]
        },
        ""conditions-a"": {
          ""id"": ""conditions-a"",
          ""type"": 3,
          ""layout"": { ""x"": 0, ""y"": 280, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""outcomes"": [
            {
              ""id"": ""outcome-a"",
              ""name"": ""Ready"",
              ""conditions"": [
                {
                  ""type"": 0,
                  ""getter"": {
                    ""parameters"": [],
                    ""typeInfo"": { ""type"": 1, ""required"": true },
                    ""instructions"": [
                      {
                        ""type"": ""return"",
                        ""pointer"": {
                          ""type"": ""value"",
                          ""value"": {
                            ""typeInfo"": { ""type"": 1, ""required"": true },
                            ""value"": true
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      },
      ""linkedValues"": [
        { ""valueId"": ""npc-value"", ""source"": 0 }
      ],
      ""settings"": { ""defaultSaveOptionChoices"": true },
      ""triggerNode"": {
        ""id"": ""trigger-a"",
        ""type"": 0,
        ""layout"": { ""x"": 0, ""y"": -140, ""width"": 320, ""height"": 120, ""isOpen"": true },
        ""linkedValues"": [],
        ""conditions"": [],
        ""dialogueGroupSettings"": {
          ""dialogueGroupId"": ""group-a"",
          ""lookupValueId"": ""npc-value"",
          ""priority"": { ""priorityOptionId"": ""urgent"", ""relativeOrder"": 1 }
        }
      },
      ""primaryLinkedValueId"": ""npc-value"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""dialogueGroups"": {
    ""group-a"": {
      ""_id"": ""group-a"",
      ""id"": ""group-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Talk"",
      ""type"": 1,
      ""parentDialogueGroupId"": null,
      ""conditions"": [],
      ""priorityGroupIdOverride"": ""priority-a"",
      ""collectionMemberId"": ""npcs-member"",
      ""collectionValueId"": ""npcs-value"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""priorityGroups"": {
    ""priority-a"": {
      ""_id"": ""priority-a"",
      ""id"": ""priority-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Default"",
      ""options"": [
        { ""id"": ""urgent"", ""name"": ""Urgent"" },
        { ""id"": ""low"", ""name"": ""Low"" }
      ],
      ""system"": null,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  }
}";

            var export = Deserialize(json);
            var dialogue = export.dialogues["dialogue-a"];
            Assert.AreEqual("Hello", dialogue.name);
            Assert.AreEqual(DialogueLinkedValueSource.Manual, dialogue.linkedValues[0].source);
            Assert.AreEqual("npc-value", dialogue.primaryLinkedValueId);

            var textNode = (DialogueTextNode)dialogue.nodes["text-a"];
            Assert.AreEqual("Hello there", textNode.text);
            Assert.AreEqual("Continue", textNode.optionSettings!.options[0].text);
            Assert.IsNotNull(textNode.optionSettings.options[0].settings);
            Assert.AreEqual(0, textNode.optionSettings.options[0].settings!.conditions!.Length);
            Assert.AreEqual(0, textNode.optionSettings.options[0].settings!.selectableConditions!.Length);

            var actionsNode = (DialogueActionsNode)dialogue.nodes["actions-a"];
            var action = (DialogueLogicEditMemberAction)actionsNode.actions[0];
            var logic = (CodeLogicAction)action.logic;
            Assert.AreEqual("Save.Score += 1;", logic.code);
            Assert.IsInstanceOf<AssignInstruction>(logic.action.instructions[0]);
            Assert.IsInstanceOf<CollectionCallInstruction>(logic.action.instructions[1]);
            Assert.AreEqual("+=", ((AssignInstruction)logic.action.instructions[0]).operatorValue);

            var conditionsNode = (DialogueConditionsNode)dialogue.nodes["conditions-a"];
            var condition = (UILogicCondition)conditionsNode.outcomes[0].conditions[0];
            var returnInstruction = (ReturnInstruction)condition.getter.instructions[0];
            Assert.IsNotNull(returnInstruction.pointer);

            var group = (LookupDialogueGroup)export.dialogueGroups["group-a"];
            Assert.AreEqual("npcs-member", group.collectionMemberId);
            Assert.AreEqual("npcs-value", group.collectionValueId);

            var priority = export.priorityGroups["priority-a"];
            Assert.AreEqual("Urgent", priority.options[0].name);
        }

        [Test]
        public void DialogueAction_Pause_Deserializes()
        {
            var json = @"
{
  ""id"": ""pause-a"",
  ""type"": 1,
  ""reason"": ""cutscene"",
  ""autoResumeDurationSeconds"": 1.25
}";

            var action = (DialoguePauseAction)JsonConvert.DeserializeObject<DialogueAction>(json)!;

            Assert.AreEqual("pause-a", action.id);
            Assert.AreEqual(DialogueActionType.Pause, action.type);
            Assert.AreEqual("cutscene", action.reason);
            Assert.AreEqual(1.25, action.autoResumeDurationSeconds);
        }

        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""autoResumeDurationSeconds"": null }", "reason")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": -1 }", "greater than or equal to zero")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": NaN }", "finite")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": Infinity }", "finite")]
        public void DialogueAction_Pause_RejectsInvalidShape(
            string json,
            string expectedMessage)
        {
            var exception = Assert.Throws<JsonSerializationException>(
                () => { JsonConvert.DeserializeObject<DialogueAction>(json); });

            StringAssert.Contains(expectedMessage, exception!.Message);
            StringAssert.Contains("pause-a", exception.Message);
        }

        [Test]
        public void SynthFixture_ProjectFields_RoundTrip()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            Assert.AreEqual("Test Project", export.project.name);
            Assert.IsNotEmpty(export.project.id);
            Assert.IsNotEmpty(export.project.rootAssetsMemberId);
            Assert.IsNotEmpty(export.project.rootSaveFileMemberId);
        }

        [Test]
        public void SynthFixture_StringMember_DefaultValueIsString()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            // Cast to the concrete typed subclass — `defaultValue`
            // lives on Member<TValue>, so the typed view is
            // `MemberValueBase<string?>?` directly.
            var name = (StringMember)export.members["member-name"];
            Assert.AreEqual(MemberKind.String, name.kind);
            // Context dispatch resolves the typed subclass directly.
            var def = (StringMemberValueBase)name.defaultValue!;
            Assert.AreEqual("Hero", def.value);
        }

        [Test]
        public void SynthFixture_IntMember_DefaultValueIsInt()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var health = (IntMember)export.members["member-health"];
            // Int and Float share MemberValueBase<double?>;
            // disambiguate via the parent member's kind when needed.
            var def = (NumberMemberValueBase)health.defaultValue!;
            Assert.AreEqual(100, (int)def.value!.Value);
        }

        [Test]
        public void SynthFixture_FloatMember_DefaultValueIsFloat()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var speed = (FloatMember)export.members["member-speed"];
            var def = (NumberMemberValueBase)speed.defaultValue!;
            Assert.AreEqual(7.5f, (float)def.value!.Value, 0.0001f);
        }

        [Test]
        public void SynthFixture_BoolMember_DefaultValueIsBool()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var alive = (BoolMember)export.members["member-isalive"];
            var def = (BoolMemberValueBase)alive.defaultValue!;
            Assert.AreEqual(true, def.value);
        }

        [Test]
        public void SynthFixture_DictionaryMember_DefaultValueIsRecord()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var inv = (DictionaryMember)export.members["member-inventory"];
            var def = (ObjectMemberValueBase)inv.defaultValue!;
            Assert.AreEqual("v-sword", def.value!["sword"]);
            Assert.AreEqual("v-shield", def.value["shield"]);
            Assert.AreEqual("member-name", inv.entryMemberId);
        }

        [Test]
        public void SynthFixture_ListMember_DefaultValueIsStringArray()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var tags = (ListMember)export.members["member-tags"];
            var def = (ArrayMemberValueBase)tags.defaultValue!;
            CollectionAssert.AreEqual(new[] { "v-a", "v-b" }, def.value);
            Assert.AreEqual("member-name", tags.entryMemberId);
        }

        [Test]
        public void SynthFixture_NSGetterReturnTypeInfo_IsCollectionTypeInfo()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyMember)export.members["member-score"];
            // The synth fixture's Score returns Int, so returnTypeInfo is
            // PrimitiveTypeInfo. Subclass assertion via `is`.
            Assert.IsInstanceOf<PrimitiveTypeInfo>(score.returnTypeInfo);
            Assert.AreEqual(MemberKind.Int, score.returnTypeInfo.type);
            Assert.IsTrue(score.returnTypeInfo.required);
        }

        [Test]
        public void SynthFixture_NSGetterCompiledIR_DispatchesAllInstructionKinds()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyMember)export.members["member-score"];
            var getter = score.getter;
            Assert.IsNotNull(getter);
            Assert.IsNotEmpty(getter.instructions);

            // The synth fixture's getter walks: variable, variable, if
            // (with nested arithmetic + isCheck + force-unwrap +
            // coalesce + keyOf + listLiteral + where + count), and a
            // bare `return null;`.
            Assert.IsInstanceOf<VariableInstruction>(getter.instructions[0]);
            Assert.IsInstanceOf<VariableInstruction>(getter.instructions[1]);
            Assert.IsInstanceOf<IfInstruction>(getter.instructions[2]);
            Assert.IsInstanceOf<ReturnInstruction>(getter.instructions[3]);

            // The if-instruction's `else` field is renamed to
            // `elseInstructions` on the C# side via [JsonProperty].
            var ifInstr = (IfInstruction)getter.instructions[2];
            Assert.IsNotEmpty(ifInstr.branches);
            Assert.IsNotEmpty(ifInstr.elseInstructions);
            Assert.IsInstanceOf<ThrowInstruction>(ifInstr.elseInstructions[0]);

            // Bare `return;` → wire `pointer: null` → C# null.
            var returnInstr = (ReturnInstruction)getter.instructions[3];
            Assert.IsNull(returnInstr.pointer);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesArithmeticOperationPointer()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyMember)export.members["member-score"];

            // First instruction: `local int x = 1 + 2;`
            var firstVar = ((VariableInstruction)score.getter.instructions[0]).variable;
            var opPointer = (OperationPointer)firstVar.pointer;
            var arithOp = (ArithmeticOperation)opPointer.operation;
            Assert.AreEqual(ArithmeticOpKind.Addition, arithOp.arithmetic.type);
            Assert.AreEqual(2, arithOp.arithmetic.pointers.Length);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesForceUnwrapCoalesceKeyOfChain()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyMember)export.members["member-score"];

            // Second instruction's pointer chain:
            // forceUnwrap(coalesce(keyOf, "Unknown"))
            var secondVar = ((VariableInstruction)score.getter.instructions[1]).variable;
            var force = (ForceUnwrapPointer)secondVar.pointer;
            var coalesce = (CoalescePointer)force.pointer;
            var keyOfPtr = (KeyOfPointer)coalesce.left;
            // `optional` is `bool?` to mirror TS-side `optional?: boolean`.
            // Compare against the boxed value rather than via Assert.IsTrue
            // (which only accepts `bool`).
            Assert.AreEqual(true, keyOfPtr.optional);
            // keyOf wraps a KeyOf body — `pointer.key` is the key
            // expression.
            Assert.IsNotNull(keyOfPtr.keyOf.pointer);
            Assert.IsNotNull(keyOfPtr.keyOf.key);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesFunctionAndListLiteralChain()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyMember)export.members["member-score"];

            // Inside the if branch:
            //   return [1, 2, 3].Where((n) => n != 0).Count();
            var ifInstr = (IfInstruction)score.getter.instructions[2];
            var ret = (ReturnInstruction)ifInstr.branches[0].instructions[0];
            var fnPtr = (FunctionPointer)ret.pointer;
            var countFn = (CountFunction)fnPtr.function;

            // Count's collectionPointer wraps the Where call.
            var whereFnPtr = (FunctionPointer)countFn.info.collectionPointer;
            var whereFn = (WhereFunction)whereFnPtr.function;

            // Where's collectionPointer wraps the list literal.
            var listLit = (ListLiteralPointer)whereFn.info.collectionPointer;
            Assert.IsNotNull(listLit.typeInfo);
            Assert.AreEqual(3, listLit.entries.Length);

            // The lambda body asserts boolean operation.
            var lambdaReturn = (ReturnInstruction)whereFn.info.function.instructions[0];
            var boolOpPtr = (OperationPointer)lambdaReturn.pointer;
            Assert.IsInstanceOf<BooleanOperation>(boolOpPtr.operation);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesStringifyAndDictLiteral()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var manifest = (NSPropertyMember)export.members["member-manifest"];
            var ret = (ReturnInstruction)manifest.getter.instructions[0];
            var stringify = (StringifyPointer)ret.pointer;
            var dictLit = (DictLiteralPointer)stringify.pointer;
            Assert.IsNotNull(dictLit.typeInfo);
            Assert.AreEqual(1, dictLit.entries.Length);
            Assert.IsNotNull(stringify.sourceType);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesCallGetterAndToBool()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var active = (NSPropertyMember)export.members["member-active"];
            var ret = (ReturnInstruction)active.getter.instructions[0];
            var toBool = (ToBoolPointer)ret.pointer;
            var callGetter = (CallGetterPointer)toBool.pointer;
            Assert.AreEqual("member-score", callGetter.memberId);
            // `optional` is `bool?` — absent on the wire means "non-optional";
            // GetValueOrDefault collapses absent / explicit-false to false.
            Assert.IsFalse(callGetter.optional.GetValueOrDefault());
            Assert.IsInstanceOf<VariablePointer>(callGetter.receiver.pointer);
        }

        [Test]
        public void SynthFixture_MemberValues_CoverAllValueShapes()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var values = export.values;

            // Each value dispatches to a polymorphic subclass via
            // MemberValueConverter — typed `value` fields drop the
            // JToken hop. Per-subclass `value` is nullable (a
            // not-required member admits a null payload), so unwrap
            // via .Value for value-typed payloads.
            Assert.AreEqual(42, (int)((NumberMemberValue)values["v-num"]).value!.Value);
            Assert.AreEqual("hello", ((StringMemberValue)values["v-str"]).value);
            Assert.AreEqual(true, ((BoolMemberValue)values["v-flag"]).value);
            Assert.AreEqual(
                3.14f,
                (float)((NumberMemberValue)values["v-float"]).value!.Value,
                0.0001f);

            var listVal = (ArrayMemberValue)values["v-list"];
            CollectionAssert.AreEqual(new[] { "wood", "stone" }, listVal.value);

            var dictVal = (ObjectMemberValue)values["v-dict"];
            Assert.AreEqual("v-name", dictVal.value!["Name"]);
            Assert.AreEqual("class-hero", dictVal.classId);

            // Null wire shape (or absent value field) → NullMemberValue.
            Assert.IsInstanceOf<NullMemberValue>(values["v-null"]);
        }

        [Test]
        public void SynthFixture_NeoSchemaClassSchema_DeserializesAsDictionary()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var hero = export.classes["class-hero"];
            Assert.AreEqual("Hero", hero.name);
            Assert.AreEqual("member-name", hero.schema["Name"]);
            Assert.AreEqual("member-health", hero.schema["Health"]);
        }

        [Test]
        public void SynthFixture_EnumOptions_DeserializeAsDictionary()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var element = export.enums["enum-element"];
            Assert.AreEqual("Element", element.name);
            // Options are keyed by option id, which the fixture's enum owns.
            // Read the ids out of the declared order rather than spelling
            // them, so this stays a round-trip assertion about the shape:
            // every ordered key resolves, and the order is the authored one.
            CollectionAssert.AreEquivalent(
                element.optionKeyOrder,
                element.options.Keys);
            CollectionAssert.AreEqual(
                new[] { "Fire", "Ice" },
                element.optionKeyOrder
                    .Select(optionId => element.options[optionId].text)
                    .ToArray());
        }

        // --------------------------------------------------------------
        // Real-world fixture — captured from a live authoring session.
        // --------------------------------------------------------------

        [Test]
        public void RealWorldFixture_DeserializesIntoProjectExport()
        {
            var export = Deserialize(LoadFixture("project-example.json"));
            Assert.IsNotNull(export);
            Assert.AreEqual("Test", export.project.name);
            Assert.Greater(export.members.Count, 0);
            Assert.Greater(export.values.Count, 0);
            Assert.Greater(export.classes.Count, 0);
        }

        [Test]
        public void RealWorldFixture_NSPropertyMembers_HaveCompiledGetters()
        {
            var export = Deserialize(LoadFixture("project-example.json"));
            int nsGetterCount = 0;
            // C# 7+ pattern-match each Dictionary value against the
            // NSPropertyMember subclass — the converter dispatch made
            // this typed, so iterating the typed projection beats
            // re-reading the discriminator + casting at every site.
            foreach (var pair in export.members)
            {
                if (!(pair.Value is NSPropertyMember nsGetter)) continue;
                nsGetterCount++;
                Assert.IsNotNull(
                    nsGetter.getter,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) lost its compiled getter");
                Assert.IsNotEmpty(
                    nsGetter.getter.instructions,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) has no instructions");
                Assert.IsNotNull(
                    nsGetter.getter.typeInfo,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) lost its typeInfo");
            }
            Assert.Greater(nsGetterCount, 0,
                "Real-world fixture should contain at least one NSProperty");
        }

        [Test]
        public void RealWorldFixture_RoundTripsThroughJsonConvert()
        {
            // Round-trip: deserialize → re-serialize → deserialize again.
            // Verifies Newtonsoft can round-trip our shape without
            // structural drift. (The default-serialize output won't be
            // byte-identical because field ordering / null elision
            // differ, but the rehydrated object graph stays equivalent.)
            var original = LoadFixture("project-example.json");
            var first = Deserialize(original);
            var reserialized = JsonConvert.SerializeObject(first);
            var second = Deserialize(reserialized);

            Assert.AreEqual(first.project.id, second.project.id);
            Assert.AreEqual(first.project.name, second.project.name);
            Assert.AreEqual(first.members.Count, second.members.Count);
            Assert.AreEqual(first.values.Count, second.values.Count);
            Assert.AreEqual(first.classes.Count, second.classes.Count);
            Assert.AreEqual(first.enums.Count, second.enums.Count);
        }

        // --------------------------------------------------------------
        // Null-value paths.
        //
        // The shape-dispatch converter routes wire `value: null` to a
        // *Null* concrete (NullMemberValue / NullMemberValueBase),
        // never to a typed subclass with a null payload. The typed
        // subclasses' `value` properties are still nullable for class-
        // system honesty (the domain admits null when a member is
        // not required, and you can construct a typed instance with
        // `value = null` in C# code), but on the wire null is always a
        // Null* concrete. These tests pin both behaviors down so future
        // refactors don't accidentally regress either side.
        //
        // The tests also confirm `default!` initialization on the
        // generic `TValue value { get; set; } = default!;` doesn't
        // force-unwrap — `default!` is a compile-time annotation only
        // (the `!` is the null-forgiving operator), and at runtime the
        // property reads as null / HasValue=false depending on TValue.
        // --------------------------------------------------------------

        [Test]
        public void TypedSubclass_DefaultInitialization_DoesNotForceUnwrap()
        {
            // For nullable value-type TValues (bool? / double?) the
            // property reads as HasValue=false; for nullable
            // reference-type TValues (string? / string[]? / Dictionary?)
            // it reads as null. Either way: no NullReferenceException,
            // no InvalidOperationException, no "force-unwrap of
            // default" landmine.
            Assert.IsFalse(new BoolMemberValueBase().value.HasValue);
            Assert.IsFalse(new NumberMemberValueBase().value.HasValue);
            Assert.IsNull(new StringMemberValueBase().value);
            Assert.IsNull(new ArrayMemberValueBase().value);
            Assert.IsNull(new ObjectMemberValueBase().value);

            // Same on the stored-row side — confirms the parallel
            // MemberValue<TValue> intermediate also default-inits
            // cleanly.
            Assert.IsFalse(new BoolMemberValue().value.HasValue);
            Assert.IsFalse(new NumberMemberValue().value.HasValue);
            Assert.IsNull(new StringMemberValue().value);
            Assert.IsNull(new ArrayMemberValue().value);
            Assert.IsNull(new ObjectMemberValue().value);
        }

        [Test]
        public void NullValueOnWire_DispatchesToNullMemberValue_AndPopulatesMetadata()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var v = export.values["v-null"];
            Assert.IsInstanceOf<NullMemberValue>(v);
            // Metadata still flows through Populate even when the shape
            // dispatches to the Null subclass — id / timestamps were
            // present on the wire, so they must be present on the
            // deserialized object.
            Assert.AreEqual("v-null", v.id);
            Assert.IsNotNull(v.createdAt);
            Assert.IsNotNull(v.updatedAt);
        }

        [Test]
        public void Member_AbsentDefaultValue_FieldIsNull()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            // member-score is an NSProperty — the synth fixture doesn't
            // emit a defaultValue for it. Cast first because
            // `defaultValue` lives on the typed Member<TValue>.
            var score = (NSPropertyMember)export.members["member-score"];
            Assert.IsNull(score.defaultValue);
        }

        [Test]
        public void Member_DefaultValueWithWireNullValue_DispatchesToTypedConcrete()
        {
            // Context-aware dispatch: a typed StringMember (TValue =
            // string?) with wire `defaultValue: { value: null }` should
            // produce a StringMemberValueBase carrying value=null —
            // NOT a NullMemberValueBase. The converter resolves the
            // concrete from the field's closed-generic type, ignoring
            // the wire's null shape. This preserves class-system
            // identity even when the payload is missing.
            const string json = @"{
                ""_id"": ""member-x"",
                ""id"": ""member-x"",
                ""projectId"": ""p"",
                ""name"": ""X"",
                ""kind"": 3,
                ""locked"": false,
                ""required"": false,
                ""isStatic"": false, ""accessModifierKind"": ""public"",
                ""defaultValue"": { ""value"": null, ""classId"": ""carrier-class"" },
                ""createdAt"": ""1970-01-01T00:00:00.000Z"",
                ""updatedAt"": ""1970-01-01T00:00:00.000Z""
            }";
            var member = (StringMember)JsonConvert.DeserializeObject<Member>(json)!;
            Assert.IsInstanceOf<StringMemberValueBase>(member.defaultValue);
            var def = (StringMemberValueBase)member.defaultValue!;
            Assert.IsNull(def.value);
            Assert.AreEqual("carrier-class", def.classId);
        }

        [Test]
        public void TypedSubclass_RoundTripWithNullValue_DispatchesToNullSubclass()
        {
            // Document and pin the shape-dispatch behavior: a typed
            // subclass with `value = null` serializes as
            // `"value": null`, and on read the converter shape-dispatches
            // that to a Null* concrete — NOT a typed subclass with null
            // payload. Metadata still survives the round-trip.
            var src = new StringMemberValue
            {
                id = "v-x",
                createdAt = "1970-01-01T00:00:00.000Z",
                updatedAt = "1970-01-01T00:00:00.000Z",
                value = null,
            };
            var json = JsonConvert.SerializeObject(src);
            var deser = JsonConvert.DeserializeObject<MemberValue>(json);
            Assert.IsInstanceOf<NullMemberValue>(deser);
            Assert.AreEqual("v-x", deser.id);
        }

        [Test]
        public void GenericInterface_BridgesEmbeddedAndStoredForms()
        {
            // IMemberValueBase<TValue> is the contract that lets one
            // helper reach into either a defaultValue carrier or a
            // values-map row for the same shape. Confirms typed get +
            // set work on both sides, including assigning null.
            IMemberValueBase<double?> carrier =
                new NumberMemberValueBase { value = 42.0 };
            IMemberValueBase<double?> row = new NumberMemberValue
            {
                id = "v",
                createdAt = "x",
                updatedAt = "x",
                value = 42.0,
            };
            Assert.AreEqual(42.0, carrier.value);
            Assert.AreEqual(42.0, row.value);

            carrier.value = null;
            row.value = null;
            Assert.IsNull(carrier.value);
            Assert.IsNull(row.value);
        }
    }
}
