// Copyright (c) Ryan Bliss and contributors. All rights reserved.
// Licensed under the MIT License.

using System.IO;
using System.Collections.Generic;
using NeoCompose.Runtime.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NUnit.Framework;

namespace NeoCompose.Tests
{
    /// <summary>
    /// Newtonsoft.Json round-trip coverage for <see cref="ProjectData"/>
    /// and the full IR tree rooted on <see cref="Attribute.getter"/>.
    ///
    /// Two fixtures back the suite:
    ///
    ///  - <c>synth-example.json</c> — generated by the TS-side dump
    ///    script (`scripts/dump-synth-export.ts`). Designed to exercise
    ///    every IR variant: list / dict literals, force-unwrap,
    ///    isCheck, callGetter, coalesce, where / count functions, both
    ///    arithmetic + boolean operations, and the four instruction
    ///    kinds (variable / if / return / throw, plus the bare
    ///    <c>return;</c> null-pointer case).
    ///  - <c>project-example.json</c> — a real-world export captured
    ///    from a live Neo-Compose authoring session.
    ///
    /// Tests load each fixture from
    /// <c>Packages/com.ryanbliss.neocompose/Tests/</c> (the canonical
    /// Unity Package Manager path for local-path references and
    /// registry installs alike) and pass the JSON through
    /// <see cref="JsonConvert.DeserializeObject{T}(string)"/>.
    /// </summary>
    public class ProjectExportRoundTripTests
    {
        private const string PackageRoot =
            "Packages/com.ryanbliss.neocompose/Tests";

        private static string LoadFixture(string fileName)
        {
            return File.ReadAllText(Path.Combine(PackageRoot, fileName));
        }

        private static ProjectData Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<ProjectData>(json);
        }

        [Test]
        public void NSPropertySetter_RoundTripsAuthoredCodeCompiledIrAndWritability()
        {
            var typeInfo = new PrimitiveTypeInfo
            {
                type = AttributeType.Int,
                required = true,
            };
            var source = new NSPropertyAttribute
            {
                id = "property-with-setter",
                projectId = "project",
                name = "Score",
                type = AttributeType.NSProperty,
                isStatic = true,
                code = "return root.Save.Score;",
                returnTypeInfo = typeInfo,
                getter = new FunctionWithReturnType
                {
                    parameters = System.Array.Empty<Variable>(),
                    instructions = System.Array.Empty<Instruction>(),
                    typeInfo = typeInfo,
                },
                setterCode = "root.Save.Score = value;",
                setter = new FunctionWithReturnType
                {
                    parameters = System.Array.Empty<Variable>(),
                    instructions = new Instruction[]
                    {
                        new AssignInstruction
                        {
                            type = InstructionKind.Assign,
                            target = new WriteTarget
                            {
                                pointer = new ReferencePointer
                                {
                                    type = PointerKind.Reference,
                                    valueId = "score-value",
                                },
                                typeInfo = typeInfo,
                                writability = WritabilityKind.Setter,
                            },
                            operatorValue = "=",
                            pointer = new VariablePointer
                            {
                                type = PointerKind.Variable,
                                variableId = "__value__",
                            },
                        },
                    },
                    typeInfo = new PrimitiveTypeInfo
                    {
                        type = AttributeType.Null,
                        required = true,
                    },
                },
                createdAt = "x",
                updatedAt = "x",
            };

            string json = JsonConvert.SerializeObject(source);
            var roundTripped = (NSPropertyAttribute)JsonConvert
                .DeserializeObject<Attribute>(json)!;

            Assert.AreEqual(source.setterCode, roundTripped.setterCode);
            Assert.IsTrue(roundTripped.isStatic);
            Assert.IsNotNull(roundTripped.setter);
            var assign = (AssignInstruction)roundTripped.setter!.instructions[0];
            Assert.AreEqual(WritabilityKind.Setter, assign.target.writability);
            Assert.AreEqual("__value__", ((VariablePointer)assign.pointer).variableId);
        }

        [Test]
        public void WriteTarget_RuntimeWritabilityAndSchemaSevenVocabularyRoundTrip()
        {
            var source = new WriteTarget
            {
                pointer = new ReferencePointer
                {
                    type = PointerKind.Reference,
                    valueId = "runtime-value",
                },
                typeInfo = new PrimitiveTypeInfo
                {
                    type = AttributeType.Int,
                    required = true,
                },
                writability = WritabilityKind.Runtime,
            };

            var roundTripped = JsonConvert.DeserializeObject<WriteTarget>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual("runtime", roundTripped.writability);
            Assert.AreEqual("immutable", WritabilityKind.Immutable);
            Assert.AreEqual("immutableToSaveLookup", WritabilityKind.ImmutableToSaveLookup);
            Assert.AreEqual("immutableToSessionLookup", WritabilityKind.ImmutableToSessionLookup);
        }

        [Test]
        public void Attribute_MissingIsStaticIsRejected()
        {
            var source = new IntAttribute
            {
                id = "legacy-member",
                projectId = "project",
                name = "Count",
                type = AttributeType.Int,
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json.Remove("isStatic");

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Attribute>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain("Missing required field 'isStatic' on IntAttribute."));
        }

        [Test]
        public void Attribute_NonBooleanIsStaticIsRejected()
        {
            var source = new IntAttribute
            {
                id = "invalid-member",
                projectId = "project",
                name = "Count",
                type = AttributeType.Int,
                createdAt = "x",
                updatedAt = "x",
            };
            var json = JObject.FromObject(source);
            json["isStatic"] = "false";

            var error = Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Attribute>(json.ToString()));

            Assert.That(
                error!.Message,
                Does.Contain("Field 'isStatic' on IntAttribute must be a boolean."));
        }

        [Test]
        public void TypeInfo_GenericAndConstructedCustomArgumentsRoundTrip()
        {
            var source = new CustomTypeInfo
            {
                type = AttributeType.Custom,
                required = true,
                typeId = "type-box",
                typeArguments = new Dictionary<string, TypeInfo>
                {
                    ["param-t"] = new GenericTypeInfo
                    {
                        type = AttributeType.Generic,
                        required = true,
                        ownerTypeId = "type-owner",
                        genericParamId = "param-t",
                    },
                },
            };

            var roundTripped = (CustomTypeInfo)JsonConvert.DeserializeObject<TypeInfo>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual("type-box", roundTripped.typeId);
            Assert.IsNotNull(roundTripped.typeArguments);
            var generic = (GenericTypeInfo)roundTripped.typeArguments!["param-t"];
            Assert.AreEqual("type-owner", generic.ownerTypeId);
            Assert.AreEqual("param-t", generic.genericParamId);
        }

        [Test]
        public void TypeInfo_InterfaceRoundTripsReferencedId()
        {
            var source = new InterfaceTypeInfo
            {
                type = AttributeType.Interface,
                required = true,
                interfaceId = "interface-entity",
            };

            var roundTripped = (InterfaceTypeInfo)JsonConvert.DeserializeObject<TypeInfo>(
                JsonConvert.SerializeObject(source))!;

            Assert.AreEqual(AttributeType.Interface, roundTripped.type);
            Assert.IsTrue(roundTripped.required);
            Assert.AreEqual("interface-entity", roundTripped.interfaceId);
        }

        [Test]
        public void InterfaceExport_RoundTripsMembersTypeInfoAndImplementsList()
        {
            Assert.AreEqual(22, (int)AttributeType.Interface);

            var source = new ProjectData
            {
                interfaces = new Dictionary<string, Interface>
                {
                    ["interface-damageable"] = new Interface
                    {
                        id = "interface-damageable",
                        projectId = "project",
                        name = "IDamageable",
                        members = new Dictionary<string, InterfaceMember>
                        {
                            ["Health"] = new InterfaceMember
                            {
                                kind = "property",
                                typeInfo = new PrimitiveTypeInfo
                                {
                                    type = AttributeType.Int,
                                    required = true,
                                },
                                settable = true,
                            },
                            ["FindTarget"] = new InterfaceMember
                            {
                                kind = "function",
                                returnTypeInfo = new InterfaceTypeInfo
                                {
                                    type = AttributeType.Interface,
                                    required = false,
                                    interfaceId = "interface-damageable",
                                },
                                argumentTypes = new List<FunctionArgumentTypeInfo>
                                {
                                    new FunctionArgumentTypeInfo
                                    {
                                        name = "candidate",
                                        type = AttributeType.Interface,
                                        required = true,
                                        interfaceId = "interface-damageable",
                                    },
                                },
                                deferred = true,
                            },
                        },
                        memberKeyOrder = new List<string> { "Health", "FindTarget" },
                        extendsInterfaceIds = new List<string> { "interface-entity" },
                        createdAt = 1000d,
                        updatedAt = 2000d,
                    },
                },
                types = new Dictionary<string, CustomType>
                {
                    ["type-enemy"] = new CustomType
                    {
                        id = "type-enemy",
                        projectId = "project",
                        name = "Enemy",
                        schema = new Dictionary<string, string>(),
                        implementsInterfaceIds = new List<string> { "interface-damageable" },
                    },
                },
            };

            var json = JsonConvert.SerializeObject(source);
            var roundTripped = JsonConvert.DeserializeObject<ProjectData>(json)!;

            var declaration = roundTripped.interfaces["interface-damageable"];
            CollectionAssert.AreEqual(
                new[] { "Health", "FindTarget" },
                declaration.memberKeyOrder);
            CollectionAssert.AreEqual(
                new[] { "interface-entity" },
                declaration.extendsInterfaceIds);
            Assert.AreEqual(true, declaration.members["Health"].settable);

            var function = declaration.members["FindTarget"];
            Assert.AreEqual(true, function.deferred);
            var returnType = (InterfaceTypeInfo)function.returnTypeInfo!;
            Assert.AreEqual("interface-damageable", returnType.interfaceId);
            Assert.AreEqual(
                "interface-damageable",
                function.argumentTypes![0].interfaceId);
            CollectionAssert.AreEqual(
                new[] { "interface-damageable" },
                roundTripped.types["type-enemy"].implementsInterfaceIds);
        }

        [Test]
        public void MissingInterfacesMap_DeserializesToEmptyDictionary()
        {
            var export = Deserialize(@"{
  ""project"": {},
  ""attributes"": {},
  ""values"": {},
  ""types"": {},
  ""enums"": {}
}");

            Assert.IsNotNull(export.interfaces);
            Assert.AreEqual(0, export.interfaces.Count);
        }

        [Test]
        public void InterfaceMember_RejectsIncompleteAndUnsupportedSignatures()
        {
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""function"",
  ""returnTypeInfo"": { ""type"": 2, ""required"": true },
  ""argumentTypes"": []
}"));

            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<InterfaceMember>(@"{
  ""kind"": ""function"",
  ""returnTypeInfo"": { ""type"": 2, ""required"": true },
  ""argumentTypes"": [
    {
      ""name"": ""value"",
      ""type"": 21,
      ""required"": true,
      ""ownerTypeId"": ""type-owner"",
      ""genericParamId"": ""param-t""
    }
  ],
  ""deferred"": false
}"));
        }

        [Test]
        public void CallFunctionPointer_RequiresOneTargetAndCallSiteId()
        {
            var concrete = (CallFunctionPointer)JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""attributeId"": ""attribute-function"",
  ""callSiteId"": ""call-1"",
  ""thisPointer"": { ""type"": ""reference"", ""valueId"": ""value"" },
  ""args"": []
}")!;
            Assert.AreEqual("attribute-function", concrete.attributeId);
            Assert.IsNull(concrete.memberKey);

            var dynamicMember = (CallFunctionPointer)JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""memberKey"": ""TakeDamage"",
  ""callSiteId"": ""call-2"",
  ""thisPointer"": { ""type"": ""reference"", ""valueId"": ""value"" },
  ""args"": []
}")!;
            Assert.IsNull(dynamicMember.attributeId);
            Assert.AreEqual("TakeDamage", dynamicMember.memberKey);

            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<Pointer>(@"{
  ""type"": ""callFunction"",
  ""attributeId"": ""attribute-function"",
  ""memberKey"": ""TakeDamage"",
  ""callSiteId"": ""call-3"",
  ""thisPointer"": { ""type"": ""reference"", ""valueId"": ""value"" },
  ""args"": []
}"));
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<CallFunctionPointer>(@"{
  ""type"": ""callFunction"",
  ""callSiteId"": ""call-4"",
  ""thisPointer"": { ""type"": ""reference"", ""valueId"": ""value"" },
  ""args"": []
}"));
            Assert.Throws<JsonSerializationException>(() =>
                JsonConvert.DeserializeObject<CallFunctionPointer>(@"{
  ""type"": ""callFunction"",
  ""attributeId"": ""attribute-function"",
  ""thisPointer"": { ""type"": ""reference"", ""valueId"": ""value"" },
  ""args"": []
}"));
        }

        // --------------------------------------------------------------
        // Synthesized fixture — exercises every IR variant.
        // --------------------------------------------------------------

        [Test]
        public void SynthFixture_DeserializesIntoProjectExport()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));

            Assert.IsNotNull(export);
            Assert.IsNotNull(export.project);
            Assert.IsNotNull(export.attributes);
            Assert.IsNotNull(export.values);
            Assert.IsNotNull(export.types);
            Assert.IsNotNull(export.enums);
            Assert.IsNotNull(export.dialogues);
            Assert.IsNotNull(export.dialogueGroups);
            Assert.IsNotNull(export.priorityGroups);
            Assert.Greater(export.attributes.Count, 0);
        }

        [Test]
        public void SynthFixture_TimestampsRoundTripAsEpochNumbers()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));

            Assert.AreEqual(0d, export.project.createdAt.EpochMilliseconds);
            Assert.AreEqual(0d, export.attributes["attr-name"].updatedAt.EpochMilliseconds);
            Assert.AreEqual(0d, export.values["v-num"].createdAt.EpochMilliseconds);

            var serialized = JObject.Parse(JsonConvert.SerializeObject(export.project));
            Assert.AreNotEqual(JTokenType.String, serialized["createdAt"]!.Type);
            Assert.AreEqual(0d, serialized["createdAt"]!.Value<double>());
        }

        [Test]
        public void MissingDialogueMaps_DeserializeToEmptyDictionaries()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Older Export"",
    ""rootAssetsAttributeId"": ""assets-root"",
    ""rootSaveFileAttributeId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""attributes"": {},
  ""values"": {},
  ""types"": {},
  ""enums"": {}
}";
            var export = Deserialize(json);
            Assert.IsNotNull(export.dialogues);
            Assert.IsNotNull(export.dialogueGroups);
            Assert.IsNotNull(export.priorityGroups);
            Assert.IsNotNull(export.files);
            Assert.IsNotNull(export.textureTemplates);
            Assert.IsNotNull(export.audioClipTemplates);
            Assert.IsNull(export.tileGridContents);
            Assert.AreEqual(0, export.dialogues.Count);
            Assert.AreEqual(0, export.dialogueGroups.Count);
            Assert.AreEqual(0, export.priorityGroups.Count);
            Assert.AreEqual(0, export.files.Count);
            Assert.AreEqual(0, export.textureTemplates.Count);
            Assert.AreEqual(0, export.audioClipTemplates.Count);
        }

        [Test]
        public void LegacyTileGridContents_ParseIntoTheGuardTokenForLoudRejection()
        {
            // Exports at schema version 3+ never carry tileGridContents; the
            // field survives only as a legacy detector so NeoClient can throw
            // a pinpointed error instead of silently dropping tile data.
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Legacy Export"",
    ""rootAssetsAttributeId"": ""assets-root"",
    ""rootSaveFileAttributeId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""attributes"": {},
  ""values"": {},
  ""types"": {},
  ""enums"": {},
  ""tileGridContents"": {
    ""town-grid"": { ""schemaVersion"": 1, ""regions"": [] }
  }
}";

            var export = Deserialize(json);

            Assert.IsNotNull(export.tileGridContents);
            Assert.AreEqual(1, export.tileGridContents!.Count);
            Assert.IsNotNull(export.tileGridContents["town-grid"]);
        }

        [Test]
        public void VersionedExport_DeserializesRecordsWithoutMongoIds()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Versioned Export"",
    ""rootAssetsAttributeId"": ""assets-root"",
    ""rootSaveFileAttributeId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""attributes"": {
    ""attr-a"": {
      ""id"": ""attr-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Title"",
      ""type"": 4,
      ""locked"": false,
      ""required"": true,
      ""isStatic"": false,
      ""valueId"": ""value-a"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""values"": {
    ""value-a"": {
      ""id"": ""value-a"",
      ""value"": ""Hello"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""types"": {},
  ""enums"": {},
  ""files"": {}
}";

            var export = Deserialize(json);

            Assert.IsNotNull(export.attributes["attr-a"]);
            Assert.IsNotNull(export.values["value-a"]);
        }

        [Test]
        public void FileAttributeExport_DeserializesFileMetadataTemplatesAndValues()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Files"",
    ""rootAssetsAttributeId"": ""assets-root"",
    ""rootSaveFileAttributeId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""attributes"": {
    ""sprite-attr"": {
      ""_id"": ""sprite-attr"",
      ""id"": ""sprite-attr"",
      ""projectId"": ""project-a"",
      ""name"": ""Portrait"",
      ""type"": 11,
      ""locked"": false,
      ""required"": true,
      ""isStatic"": false,
      ""templateId"": ""texture-template-1"",
      ""valueId"": ""sprite-value"",
      ""defaultValue"": { ""value"": { ""fileId"": ""file-1"", ""sliceIndex"": 2 } },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    },
    ""audio-attr"": {
      ""_id"": ""audio-attr"",
      ""id"": ""audio-attr"",
      ""projectId"": ""project-a"",
      ""name"": ""Voice"",
      ""type"": 12,
      ""locked"": false,
      ""required"": false,
      ""isStatic"": false,
      ""templateId"": ""audio-template-1"",
      ""valueId"": ""audio-value"",
      ""defaultValue"": { ""value"": { ""fileId"": ""file-2"" } },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""values"": {
    ""sprite-value"": {
      ""_id"": ""sprite-value"",
      ""id"": ""sprite-value"",
      ""value"": { ""fileId"": ""file-1"", ""sliceIndex"": 2 },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    },
    ""audio-value"": {
      ""_id"": ""audio-value"",
      ""id"": ""audio-value"",
      ""value"": { ""fileId"": ""file-2"" },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""types"": {},
  ""enums"": {},
  ""files"": {
    ""file-1"": {
      ""_id"": ""file-1"",
      ""id"": ""file-1"",
      ""projectId"": ""project-a"",
      ""status"": ""uploaded"",
      ""name"": ""portrait.png"",
      ""fileType"": ""image"",
      ""mimeType"": ""image/png"",
      ""byteLength"": 3,
      ""storageKey"": ""projects/project-a/files/file-1"",
      ""storageETag"": ""etag-1"",
      ""unityTextureSettings"": { ""templateId"": ""texture-template-1"", ""type"": ""texture-2d"", ""overridePaths"": [], ""values"": {} },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-02T00:00:00.000Z""
    },
    ""file-2"": {
      ""_id"": ""file-2"",
      ""id"": ""file-2"",
      ""projectId"": ""project-a"",
      ""status"": ""uploaded"",
      ""name"": ""voice.wav"",
      ""fileType"": ""audio"",
      ""mimeType"": ""audio/wav"",
      ""byteLength"": 4,
      ""storageKey"": ""projects/project-a/files/file-2"",
      ""storageETag"": ""etag-2"",
      ""audioDurationSeconds"": 1.25,
      ""unityAudioClipSettings"": { ""templateId"": ""audio-template-1"", ""overridePaths"": [], ""values"": {} },
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-02T00:00:00.000Z""
    }
  },
  ""textureTemplates"": {
    ""texture-template-1"": {
      ""_id"": ""texture-template-1"",
      ""id"": ""texture-template-1"",
      ""projectId"": ""project-a"",
      ""name"": ""Sprites"",
      ""type"": ""texture-2d"",
      ""textureType"": ""sprite"",
      ""textureShape"": ""2d"",
      ""sRGBTexture"": true,
      ""alphaSource"": ""input-texture-alpha"",
      ""alphaIsTransparency"": true,
      ""nonPowerOfTwoScale"": ""none"",
      ""ignorePngGamma"": false,
      ""readWriteEnabled"": false,
      ""virtualTextureOnly"": false,
      ""generateMipMaps"": false,
      ""borderMipMaps"": false,
      ""mipMapFiltering"": ""box"",
      ""mipMapsPreserveCoverage"": false,
      ""alphaCutoffValue"": 0.5,
      ""fadeOutMipMaps"": false,
      ""mipMapFadeDistanceStart"": 1,
      ""mipMapFadeDistanceEnd"": 3,
      ""anisoLevel"": 1,
      ""wrapMode"": ""clamp"",
      ""filterMode"": ""point"",
      ""maxTextureSize"": 2048,
      ""resizeAlgorithm"": ""mitchell"",
      ""textureCompression"": ""none"",
      ""compressionQuality"": 50,
      ""crunchedCompression"": false,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-03T00:00:00.000Z""
    }
  },
  ""audioClipTemplates"": {
    ""audio-template-1"": {
      ""_id"": ""audio-template-1"",
      ""id"": ""audio-template-1"",
      ""projectId"": ""project-a"",
      ""name"": ""Voice"",
      ""forceToMono"": false,
      ""normalize"": true,
      ""loadInBackground"": false,
      ""ambisonic"": false,
      ""loadType"": ""decompress-on-load"",
      ""compressionFormat"": ""vorbis"",
      ""quality"": 0.7,
      ""sampleRateSetting"": ""preserve-sample-rate"",
      ""preloadAudioData"": true,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-04T00:00:00.000Z""
    }
  }
}";
            var export = Deserialize(json);

            var spriteAttr = (SpriteAttribute)export.attributes["sprite-attr"];
            var spriteDefault = (SpriteAttributeValueBase)spriteAttr.defaultValue!;
            Assert.AreEqual(AttributeType.Sprite, spriteAttr.type);
            Assert.AreEqual("texture-template-1", spriteAttr.templateId);
            Assert.AreEqual("file-1", spriteDefault.value!.fileId);
            Assert.AreEqual(2, spriteDefault.value.sliceIndex);
            Assert.IsInstanceOf<SpriteAttributeValue>(export.values["sprite-value"]);

            var audioAttr = (AudioAttribute)export.attributes["audio-attr"];
            var audioDefault = (FileAttributeValueBase)audioAttr.defaultValue!;
            Assert.AreEqual(AttributeType.Audio, audioAttr.type);
            Assert.AreEqual("audio-template-1", audioAttr.templateId);
            Assert.AreEqual("file-2", audioDefault.value!.fileId);
            Assert.IsInstanceOf<FileAttributeValue>(export.values["audio-value"]);

            Assert.AreEqual("portrait.png", export.files["file-1"].name);
            Assert.AreEqual("texture-template-1", export.files["file-1"].unityTextureSettings!.templateId);
            Assert.AreEqual("Sprites", export.textureTemplates["texture-template-1"].name);
            Assert.AreEqual("Voice", export.audioClipTemplates["audio-template-1"].name);
        }

        [Test]
        public void DialogueMaps_DeserializeDialogueGroupPriorityAndActionShapes()
        {
            var json = @"
{
  ""project"": {
    ""_id"": ""project-a"",
    ""id"": ""project-a"",
    ""name"": ""Dialogue Project"",
    ""rootAssetsAttributeId"": ""assets-root"",
    ""rootSaveFileAttributeId"": ""save-root"",
    ""createdAt"": ""1970-01-01T00:00:00.000Z"",
    ""updatedAt"": ""1970-01-01T00:00:00.000Z""
  },
  ""attributes"": {},
  ""enums"": {},
  ""types"": {},
  ""values"": {},
  ""dialogues"": {
    ""dialogue-a"": {
      ""_id"": ""dialogue-a"",
      ""id"": ""dialogue-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Hello"",
      ""description"": null,
      ""nodes"": {
        ""text-a"": {
          ""id"": ""text-a"",
          ""type"": 1,
          ""layout"": { ""x"": 0, ""y"": 0, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""text"": ""Hello there"",
          ""optionSettings"": {
            ""saveChoice"": true,
            ""options"": [
              {
                ""id"": ""option-a"",
                ""text"": ""Continue"",
                ""toNodeId"": ""actions-a"",
                ""settings"": {
                  ""conditions"": [],
                  ""selectableConditions"": []
                }
              }
            ]
          }
        },
        ""actions-a"": {
          ""id"": ""actions-a"",
          ""type"": 2,
          ""layout"": { ""x"": 0, ""y"": 140, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""actions"": [
            {
              ""id"": ""action-a"",
              ""type"": 0,
              ""logic"": {
                ""type"": 1,
                ""code"": ""Save.Score += 1;"",
                ""action"": {
                  ""parameters"": [],
                  ""typeInfo"": { ""type"": 0, ""required"": true },
                  ""instructions"": [
                    {
                      ""type"": ""assign"",
                      ""target"": {
                        ""pointer"": { ""type"": ""reference"", ""valueId"": ""score-value"" },
                        ""typeInfo"": { ""type"": 2, ""required"": true },
                        ""writability"": ""save""
                      },
                      ""operator"": ""+="",
                      ""pointer"": {
                        ""type"": ""value"",
                        ""value"": {
                          ""typeInfo"": { ""type"": 2, ""required"": true },
                          ""value"": 1
                        }
                      }
                    },
                    {
                      ""type"": ""collectionCall"",
                      ""target"": {
                        ""pointer"": { ""type"": ""reference"", ""valueId"": ""visited-value"" },
                        ""typeInfo"": {
                          ""type"": 8,
                          ""required"": true,
                          ""entryTypeInfo"": { ""type"": 4, ""required"": true }
                        },
                        ""writability"": ""save""
                      },
                      ""mutation"": ""Add"",
                      ""args"": [
                        {
                          ""type"": ""value"",
                          ""value"": {
                            ""typeInfo"": { ""type"": 4, ""required"": true },
                            ""value"": ""Earth""
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          ]
        },
        ""conditions-a"": {
          ""id"": ""conditions-a"",
          ""type"": 3,
          ""layout"": { ""x"": 0, ""y"": 280, ""width"": 320, ""height"": 120, ""isOpen"": true },
          ""linkedValues"": [],
          ""outcomes"": [
            {
              ""id"": ""outcome-a"",
              ""name"": ""Ready"",
              ""conditions"": [
                {
                  ""type"": 0,
                  ""getter"": {
                    ""parameters"": [],
                    ""typeInfo"": { ""type"": 1, ""required"": true },
                    ""instructions"": [
                      {
                        ""type"": ""return"",
                        ""pointer"": {
                          ""type"": ""value"",
                          ""value"": {
                            ""typeInfo"": { ""type"": 1, ""required"": true },
                            ""value"": true
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      },
      ""linkedValues"": [
        { ""valueId"": ""npc-value"", ""source"": 0 }
      ],
      ""settings"": { ""defaultSaveOptionChoices"": true },
      ""triggerNode"": {
        ""id"": ""trigger-a"",
        ""type"": 0,
        ""layout"": { ""x"": 0, ""y"": -140, ""width"": 320, ""height"": 120, ""isOpen"": true },
        ""linkedValues"": [],
        ""conditions"": [],
        ""dialogueGroupSettings"": {
          ""dialogueGroupId"": ""group-a"",
          ""lookupValueId"": ""npc-value"",
          ""priority"": { ""priorityTypeId"": ""urgent"", ""relativeOrder"": 1 }
        }
      },
      ""primaryLinkedValueId"": ""npc-value"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""dialogueGroups"": {
    ""group-a"": {
      ""_id"": ""group-a"",
      ""id"": ""group-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Talk"",
      ""type"": 1,
      ""parentDialogueGroupId"": null,
      ""conditions"": [],
      ""priorityGroupIdOverride"": ""priority-a"",
      ""collectionAttributeId"": ""npcs-attribute"",
      ""collectionValueId"": ""npcs-value"",
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  },
  ""priorityGroups"": {
    ""priority-a"": {
      ""_id"": ""priority-a"",
      ""id"": ""priority-a"",
      ""projectId"": ""project-a"",
      ""name"": ""Default"",
      ""options"": [
        { ""id"": ""urgent"", ""name"": ""Urgent"" },
        { ""id"": ""low"", ""name"": ""Low"" }
      ],
      ""system"": null,
      ""createdAt"": ""1970-01-01T00:00:00.000Z"",
      ""updatedAt"": ""1970-01-01T00:00:00.000Z""
    }
  }
}";

            var export = Deserialize(json);
            var dialogue = export.dialogues["dialogue-a"];
            Assert.AreEqual("Hello", dialogue.name);
            Assert.AreEqual(DialogueLinkedValueSource.Manual, dialogue.linkedValues[0].source);
            Assert.AreEqual("npc-value", dialogue.primaryLinkedValueId);

            var textNode = (DialogueTextNode)dialogue.nodes["text-a"];
            Assert.AreEqual("Hello there", textNode.text);
            Assert.AreEqual("Continue", textNode.optionSettings!.options[0].text);
            Assert.IsNotNull(textNode.optionSettings.options[0].settings);
            Assert.AreEqual(0, textNode.optionSettings.options[0].settings!.conditions!.Length);
            Assert.AreEqual(0, textNode.optionSettings.options[0].settings!.selectableConditions!.Length);

            var actionsNode = (DialogueActionsNode)dialogue.nodes["actions-a"];
            var action = (DialogueLogicEditAttributeAction)actionsNode.actions[0];
            var logic = (CodeLogicAction)action.logic;
            Assert.AreEqual("Save.Score += 1;", logic.code);
            Assert.IsInstanceOf<AssignInstruction>(logic.action.instructions[0]);
            Assert.IsInstanceOf<CollectionCallInstruction>(logic.action.instructions[1]);
            Assert.AreEqual("+=", ((AssignInstruction)logic.action.instructions[0]).operatorValue);

            var conditionsNode = (DialogueConditionsNode)dialogue.nodes["conditions-a"];
            var condition = (UILogicCondition)conditionsNode.outcomes[0].conditions[0];
            var returnInstruction = (ReturnInstruction)condition.getter.instructions[0];
            Assert.IsNotNull(returnInstruction.pointer);

            var group = (LookupDialogueGroup)export.dialogueGroups["group-a"];
            Assert.AreEqual("npcs-attribute", group.collectionAttributeId);
            Assert.AreEqual("npcs-value", group.collectionValueId);

            var priority = export.priorityGroups["priority-a"];
            Assert.AreEqual("Urgent", priority.options[0].name);
        }

        [Test]
        public void DialogueAction_Pause_Deserializes()
        {
            var json = @"
{
  ""id"": ""pause-a"",
  ""type"": 1,
  ""reason"": ""cutscene"",
  ""autoResumeDurationSeconds"": 1.25
}";

            var action = (DialoguePauseAction)JsonConvert.DeserializeObject<DialogueAction>(json)!;

            Assert.AreEqual("pause-a", action.id);
            Assert.AreEqual(DialogueActionType.Pause, action.type);
            Assert.AreEqual("cutscene", action.reason);
            Assert.AreEqual(1.25, action.autoResumeDurationSeconds);
        }

        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""autoResumeDurationSeconds"": null }", "reason")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": -1 }", "greater than or equal to zero")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": NaN }", "finite")]
        [TestCase(@"{ ""id"": ""pause-a"", ""type"": 1, ""reason"": """", ""autoResumeDurationSeconds"": Infinity }", "finite")]
        public void DialogueAction_Pause_RejectsInvalidShape(
            string json,
            string expectedMessage)
        {
            var exception = Assert.Throws<JsonSerializationException>(
                () => { JsonConvert.DeserializeObject<DialogueAction>(json); });

            StringAssert.Contains(expectedMessage, exception!.Message);
            StringAssert.Contains("pause-a", exception.Message);
        }

        [Test]
        public void SynthFixture_ProjectFields_RoundTrip()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            Assert.AreEqual("Test Project", export.project.name);
            Assert.IsNotEmpty(export.project.id);
            Assert.IsNotEmpty(export.project.rootAssetsAttributeId);
            Assert.IsNotEmpty(export.project.rootSaveFileAttributeId);
        }

        [Test]
        public void SynthFixture_StringAttribute_DefaultValueIsString()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            // Cast to the concrete typed subclass — `defaultValue`
            // lives on Attribute<TValue>, so the typed view is
            // `AttributeValueBase<string?>?` directly.
            var name = (StringAttribute)export.attributes["attr-name"];
            Assert.AreEqual(AttributeType.String, name.type);
            // Context dispatch resolves the typed subclass directly.
            var def = (StringAttributeValueBase)name.defaultValue!;
            Assert.AreEqual("Hero", def.value);
        }

        [Test]
        public void SynthFixture_IntAttribute_DefaultValueIsInt()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var health = (IntAttribute)export.attributes["attr-health"];
            // Int and Float share AttributeValueBase<double?>;
            // disambiguate via the parent attribute's type when needed.
            var def = (NumberAttributeValueBase)health.defaultValue!;
            Assert.AreEqual(100, (int)def.value!.Value);
        }

        [Test]
        public void SynthFixture_FloatAttribute_DefaultValueIsFloat()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var speed = (FloatAttribute)export.attributes["attr-speed"];
            var def = (NumberAttributeValueBase)speed.defaultValue!;
            Assert.AreEqual(7.5f, (float)def.value!.Value, 0.0001f);
        }

        [Test]
        public void SynthFixture_BoolAttribute_DefaultValueIsBool()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var alive = (BoolAttribute)export.attributes["attr-isalive"];
            var def = (BoolAttributeValueBase)alive.defaultValue!;
            Assert.AreEqual(true, def.value);
        }

        [Test]
        public void SynthFixture_DictionaryAttribute_DefaultValueIsRecord()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var inv = (DictionaryAttribute)export.attributes["attr-inventory"];
            var def = (ObjectAttributeValueBase)inv.defaultValue!;
            Assert.AreEqual("v-sword", def.value!["sword"]);
            Assert.AreEqual("v-shield", def.value["shield"]);
            Assert.AreEqual("attr-name", inv.entryAttributeId);
        }

        [Test]
        public void SynthFixture_ListAttribute_DefaultValueIsStringArray()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var tags = (ListAttribute)export.attributes["attr-tags"];
            var def = (ArrayAttributeValueBase)tags.defaultValue!;
            CollectionAssert.AreEqual(new[] { "v-a", "v-b" }, def.value);
            Assert.AreEqual("attr-name", tags.entryAttributeId);
        }

        [Test]
        public void SynthFixture_NSGetterReturnTypeInfo_IsCollectionTypeInfo()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyAttribute)export.attributes["attr-score"];
            // The synth fixture's Score returns Int, so returnTypeInfo is
            // PrimitiveTypeInfo. Subclass assertion via `is`.
            Assert.IsInstanceOf<PrimitiveTypeInfo>(score.returnTypeInfo);
            Assert.AreEqual(AttributeType.Int, score.returnTypeInfo.type);
            Assert.IsTrue(score.returnTypeInfo.required);
        }

        [Test]
        public void SynthFixture_NSGetterCompiledIR_DispatchesAllInstructionKinds()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyAttribute)export.attributes["attr-score"];
            var getter = score.getter;
            Assert.IsNotNull(getter);
            Assert.IsNotEmpty(getter.instructions);

            // The synth fixture's getter walks: variable, variable, if
            // (with nested arithmetic + isCheck + force-unwrap +
            // coalesce + keyOf + listLiteral + where + count), and a
            // bare `return null;`.
            Assert.IsInstanceOf<VariableInstruction>(getter.instructions[0]);
            Assert.IsInstanceOf<VariableInstruction>(getter.instructions[1]);
            Assert.IsInstanceOf<IfInstruction>(getter.instructions[2]);
            Assert.IsInstanceOf<ReturnInstruction>(getter.instructions[3]);

            // The if-instruction's `else` field is renamed to
            // `elseInstructions` on the C# side via [JsonProperty].
            var ifInstr = (IfInstruction)getter.instructions[2];
            Assert.IsNotEmpty(ifInstr.branches);
            Assert.IsNotEmpty(ifInstr.elseInstructions);
            Assert.IsInstanceOf<ThrowInstruction>(ifInstr.elseInstructions[0]);

            // Bare `return;` → wire `pointer: null` → C# null.
            var returnInstr = (ReturnInstruction)getter.instructions[3];
            Assert.IsNull(returnInstr.pointer);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesArithmeticOperationPointer()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyAttribute)export.attributes["attr-score"];

            // First instruction: `local int x = 1 + 2;`
            var firstVar = ((VariableInstruction)score.getter.instructions[0]).variable;
            var opPointer = (OperationPointer)firstVar.pointer;
            var arithOp = (ArithmeticOperation)opPointer.operation;
            Assert.AreEqual(ArithmeticOpKind.Addition, arithOp.arithmetic.type);
            Assert.AreEqual(2, arithOp.arithmetic.pointers.Length);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesForceUnwrapCoalesceKeyOfChain()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyAttribute)export.attributes["attr-score"];

            // Second instruction's pointer chain:
            // forceUnwrap(coalesce(keyOf, "Unknown"))
            var secondVar = ((VariableInstruction)score.getter.instructions[1]).variable;
            var force = (ForceUnwrapPointer)secondVar.pointer;
            var coalesce = (CoalescePointer)force.pointer;
            var keyOfPtr = (KeyOfPointer)coalesce.left;
            // `optional` is `bool?` to mirror TS-side `optional?: boolean`.
            // Compare against the boxed value rather than via Assert.IsTrue
            // (which only accepts `bool`).
            Assert.AreEqual(true, keyOfPtr.optional);
            // keyOf wraps a KeyOf body — `pointer.key` is the key
            // expression.
            Assert.IsNotNull(keyOfPtr.keyOf.pointer);
            Assert.IsNotNull(keyOfPtr.keyOf.key);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesFunctionAndListLiteralChain()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var score = (NSPropertyAttribute)export.attributes["attr-score"];

            // Inside the if branch:
            //   return [1, 2, 3].Where((n) => n != 0).Count();
            var ifInstr = (IfInstruction)score.getter.instructions[2];
            var ret = (ReturnInstruction)ifInstr.branches[0].instructions[0];
            var fnPtr = (FunctionPointer)ret.pointer;
            var countFn = (CountFunction)fnPtr.function;

            // Count's collectionPointer wraps the Where call.
            var whereFnPtr = (FunctionPointer)countFn.info.collectionPointer;
            var whereFn = (WhereFunction)whereFnPtr.function;

            // Where's collectionPointer wraps the list literal.
            var listLit = (ListLiteralPointer)whereFn.info.collectionPointer;
            Assert.IsNotNull(listLit.typeInfo);
            Assert.AreEqual(3, listLit.entries.Length);

            // The lambda body asserts boolean operation.
            var lambdaReturn = (ReturnInstruction)whereFn.info.function.instructions[0];
            var boolOpPtr = (OperationPointer)lambdaReturn.pointer;
            Assert.IsInstanceOf<BooleanOperation>(boolOpPtr.operation);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesStringifyAndDictLiteral()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var manifest = (NSPropertyAttribute)export.attributes["attr-manifest"];
            var ret = (ReturnInstruction)manifest.getter.instructions[0];
            var stringify = (StringifyPointer)ret.pointer;
            var dictLit = (DictLiteralPointer)stringify.pointer;
            Assert.IsNotNull(dictLit.typeInfo);
            Assert.AreEqual(1, dictLit.entries.Length);
            Assert.IsNotNull(stringify.sourceType);
        }

        [Test]
        public void SynthFixture_NSGetterIR_PreservesCallGetterAndToBool()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var active = (NSPropertyAttribute)export.attributes["attr-active"];
            var ret = (ReturnInstruction)active.getter.instructions[0];
            var toBool = (ToBoolPointer)ret.pointer;
            var callGetter = (CallGetterPointer)toBool.pointer;
            Assert.AreEqual("attr-score", callGetter.attributeId);
            // `optional` is `bool?` — absent on the wire means "non-optional";
            // GetValueOrDefault collapses absent / explicit-false to false.
            Assert.IsFalse(callGetter.optional.GetValueOrDefault());
            Assert.IsInstanceOf<VariablePointer>(callGetter.thisPointer);
        }

        [Test]
        public void SynthFixture_AttributeValues_CoverAllValueShapes()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var values = export.values;

            // Each value dispatches to a polymorphic subclass via
            // AttributeValueConverter — typed `value` fields drop the
            // JToken hop. Per-subclass `value` is nullable (a
            // not-required attribute admits a null payload), so unwrap
            // via .Value for value-typed payloads.
            Assert.AreEqual(42, (int)((NumberAttributeValue)values["v-num"]).value!.Value);
            Assert.AreEqual("hello", ((StringAttributeValue)values["v-str"]).value);
            Assert.AreEqual(true, ((BoolAttributeValue)values["v-flag"]).value);
            Assert.AreEqual(
                3.14f,
                (float)((NumberAttributeValue)values["v-float"]).value!.Value,
                0.0001f);

            var listVal = (ArrayAttributeValue)values["v-list"];
            CollectionAssert.AreEqual(new[] { "wood", "stone" }, listVal.value);

            var dictVal = (ObjectAttributeValue)values["v-dict"];
            Assert.AreEqual("v-name", dictVal.value!["Name"]);
            Assert.AreEqual("type-hero", dictVal.typeId);

            // Null wire shape (or absent value field) → NullAttributeValue.
            Assert.IsInstanceOf<NullAttributeValue>(values["v-null"]);
        }

        [Test]
        public void SynthFixture_CustomTypeSchema_DeserializesAsDictionary()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var hero = export.types["type-hero"];
            Assert.AreEqual("Hero", hero.name);
            Assert.AreEqual("attr-name", hero.schema["Name"]);
            Assert.AreEqual("attr-health", hero.schema["Health"]);
        }

        [Test]
        public void SynthFixture_EnumOptions_DeserializeAsDictionary()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var element = export.enums["enum-element"];
            Assert.AreEqual("Element", element.name);
            Assert.AreEqual("Fire", element.options["fire"].text);
            Assert.AreEqual("Ice", element.options["ice"].text);
            CollectionAssert.AreEqual(
                new[] { "fire", "ice" },
                element.optionKeyOrder);
        }

        // --------------------------------------------------------------
        // Real-world fixture — captured from a live authoring session.
        // --------------------------------------------------------------

        [Test]
        public void RealWorldFixture_DeserializesIntoProjectExport()
        {
            var export = Deserialize(LoadFixture("project-example.json"));
            Assert.IsNotNull(export);
            Assert.AreEqual("Test", export.project.name);
            Assert.Greater(export.attributes.Count, 0);
            Assert.Greater(export.values.Count, 0);
            Assert.Greater(export.types.Count, 0);
        }

        [Test]
        public void RealWorldFixture_NSPropertyAttributes_HaveCompiledGetters()
        {
            var export = Deserialize(LoadFixture("project-example.json"));
            int nsGetterCount = 0;
            // C# 7+ pattern-match each Dictionary value against the
            // NSPropertyAttribute subclass — the converter dispatch made
            // this typed, so iterating the typed projection beats
            // re-reading the discriminator + casting at every site.
            foreach (var pair in export.attributes)
            {
                if (!(pair.Value is NSPropertyAttribute nsGetter)) continue;
                nsGetterCount++;
                Assert.IsNotNull(
                    nsGetter.getter,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) lost its compiled getter");
                Assert.IsNotEmpty(
                    nsGetter.getter.instructions,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) has no instructions");
                Assert.IsNotNull(
                    nsGetter.getter.typeInfo,
                    $"NSProperty {nsGetter.id} ({nsGetter.name}) lost its typeInfo");
            }
            Assert.Greater(nsGetterCount, 0,
                "Real-world fixture should contain at least one NSProperty");
        }

        [Test]
        public void RealWorldFixture_RoundTripsThroughJsonConvert()
        {
            // Round-trip: deserialize → re-serialize → deserialize again.
            // Verifies Newtonsoft can round-trip our shape without
            // structural drift. (The default-serialize output won't be
            // byte-identical because field ordering / null elision
            // differ, but the rehydrated object graph stays equivalent.)
            var original = LoadFixture("project-example.json");
            var first = Deserialize(original);
            var reserialized = JsonConvert.SerializeObject(first);
            var second = Deserialize(reserialized);

            Assert.AreEqual(first.project.id, second.project.id);
            Assert.AreEqual(first.project.name, second.project.name);
            Assert.AreEqual(first.attributes.Count, second.attributes.Count);
            Assert.AreEqual(first.values.Count, second.values.Count);
            Assert.AreEqual(first.types.Count, second.types.Count);
            Assert.AreEqual(first.enums.Count, second.enums.Count);
        }

        // --------------------------------------------------------------
        // Null-value paths.
        //
        // The shape-dispatch converter routes wire `value: null` to a
        // *Null* concrete (NullAttributeValue / NullAttributeValueBase),
        // never to a typed subclass with a null payload. The typed
        // subclasses' `value` properties are still nullable for type-
        // system honesty (the domain admits null when an attribute is
        // not required, and you can construct a typed instance with
        // `value = null` in C# code), but on the wire null is always a
        // Null* concrete. These tests pin both behaviors down so future
        // refactors don't accidentally regress either side.
        //
        // The tests also confirm `default!` initialization on the
        // generic `TValue value { get; set; } = default!;` doesn't
        // force-unwrap — `default!` is a compile-time annotation only
        // (the `!` is the null-forgiving operator), and at runtime the
        // property reads as null / HasValue=false depending on TValue.
        // --------------------------------------------------------------

        [Test]
        public void TypedSubclass_DefaultInitialization_DoesNotForceUnwrap()
        {
            // For nullable value-type TValues (bool? / double?) the
            // property reads as HasValue=false; for nullable
            // reference-type TValues (string? / string[]? / Dictionary?)
            // it reads as null. Either way: no NullReferenceException,
            // no InvalidOperationException, no "force-unwrap of
            // default" landmine.
            Assert.IsFalse(new BoolAttributeValueBase().value.HasValue);
            Assert.IsFalse(new NumberAttributeValueBase().value.HasValue);
            Assert.IsNull(new StringAttributeValueBase().value);
            Assert.IsNull(new ArrayAttributeValueBase().value);
            Assert.IsNull(new ObjectAttributeValueBase().value);

            // Same on the stored-row side — confirms the parallel
            // AttributeValue<TValue> intermediate also default-inits
            // cleanly.
            Assert.IsFalse(new BoolAttributeValue().value.HasValue);
            Assert.IsFalse(new NumberAttributeValue().value.HasValue);
            Assert.IsNull(new StringAttributeValue().value);
            Assert.IsNull(new ArrayAttributeValue().value);
            Assert.IsNull(new ObjectAttributeValue().value);
        }

        [Test]
        public void NullValueOnWire_DispatchesToNullAttributeValue_AndPopulatesMetadata()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            var v = export.values["v-null"];
            Assert.IsInstanceOf<NullAttributeValue>(v);
            // Metadata still flows through Populate even when the shape
            // dispatches to the Null subclass — id / timestamps were
            // present on the wire, so they must be present on the
            // deserialized object.
            Assert.AreEqual("v-null", v.id);
            Assert.IsNotNull(v.createdAt);
            Assert.IsNotNull(v.updatedAt);
        }

        [Test]
        public void Attribute_AbsentDefaultValue_FieldIsNull()
        {
            var export = Deserialize(LoadFixture("synth-example.json"));
            // attr-score is an NSProperty — the synth fixture doesn't
            // emit a defaultValue for it. Cast first because
            // `defaultValue` lives on the typed Attribute<TValue>.
            var score = (NSPropertyAttribute)export.attributes["attr-score"];
            Assert.IsNull(score.defaultValue);
        }

        [Test]
        public void Attribute_DefaultValueWithWireNullValue_DispatchesToTypedConcrete()
        {
            // Context-aware dispatch: a typed StringAttribute (TValue =
            // string?) with wire `defaultValue: { value: null }` should
            // produce a StringAttributeValueBase carrying value=null —
            // NOT a NullAttributeValueBase. The converter resolves the
            // concrete from the field's closed-generic type, ignoring
            // the wire's null shape. This preserves type-system
            // identity even when the payload is missing.
            const string json = @"{
                ""_id"": ""attr-x"",
                ""id"": ""attr-x"",
                ""projectId"": ""p"",
                ""name"": ""X"",
                ""type"": 3,
                ""locked"": false,
                ""required"": false,
                ""isStatic"": false,
                ""defaultValue"": { ""value"": null, ""typeId"": ""carrier-type"" },
                ""createdAt"": ""1970-01-01T00:00:00.000Z"",
                ""updatedAt"": ""1970-01-01T00:00:00.000Z""
            }";
            var attr = (StringAttribute)JsonConvert.DeserializeObject<Attribute>(json)!;
            Assert.IsInstanceOf<StringAttributeValueBase>(attr.defaultValue);
            var def = (StringAttributeValueBase)attr.defaultValue!;
            Assert.IsNull(def.value);
            Assert.AreEqual("carrier-type", def.typeId);
        }

        [Test]
        public void TypedSubclass_RoundTripWithNullValue_DispatchesToNullSubclass()
        {
            // Document and pin the shape-dispatch behavior: a typed
            // subclass with `value = null` serializes as
            // `"value": null`, and on read the converter shape-dispatches
            // that to a Null* concrete — NOT a typed subclass with null
            // payload. Metadata still survives the round-trip.
            var src = new StringAttributeValue
            {
                id = "v-x",
                createdAt = "1970-01-01T00:00:00.000Z",
                updatedAt = "1970-01-01T00:00:00.000Z",
                value = null,
            };
            var json = JsonConvert.SerializeObject(src);
            var deser = JsonConvert.DeserializeObject<AttributeValue>(json);
            Assert.IsInstanceOf<NullAttributeValue>(deser);
            Assert.AreEqual("v-x", deser.id);
        }

        [Test]
        public void GenericInterface_BridgesEmbeddedAndStoredForms()
        {
            // IAttributeValueBase<TValue> is the contract that lets one
            // helper reach into either a defaultValue carrier or a
            // values-map row for the same shape. Confirms typed get +
            // set work on both sides, including assigning null.
            IAttributeValueBase<double?> carrier =
                new NumberAttributeValueBase { value = 42.0 };
            IAttributeValueBase<double?> row = new NumberAttributeValue
            {
                id = "v",
                createdAt = "x",
                updatedAt = "x",
                value = 42.0,
            };
            Assert.AreEqual(42.0, carrier.value);
            Assert.AreEqual(42.0, row.value);

            carrier.value = null;
            row.value = null;
            Assert.IsNull(carrier.value);
            Assert.IsNull(row.value);
        }
    }
}
